openhab/openhab1-addons

bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/internal/engine/RuleEngine.java, distribution/openhabhome/configurations/rules/demo.rules
This pull request results from the analysis of #1742:
- Improved robustness of RuleEngine against NullPointerExceptions (if ScriptExecutionException contains no cause or no cause message).
- Fix log error caused by demo.rules when no weather history exists yet. Before the fix it could happen that toString was called on a null value.
=> Improve logging and handling of null values in RuleEngine

bundles/io/org.openhab.io.multimedia.tts.speechdispatcher/src/main/java/org/openhab/io/multimedia/internal/tts/SpeechDispatcherConnection.java
Currently the SpeechDispatcher TTS plugin only connects to the speech dispatcher server once.  If that connection is dropped, it never retries to gain - just logs the following error:
`ERROR o.o.i.m.i.t.SpeechDispatcherConnection[:67]- Error sending text to SpeechDispatcher Host 127.0.0.1: not connected to server`
The only existing recovery was to restart openhab.
This simple Pull Request adds a check to see if the plugin has been disconnected from the server and reconnects automatically.
=> SpeechDispatcher:  Reconnect to server if connection is dropped.

bundles/archetype/org.openhab.archetype.binding/src/main/resources/archetype-resources/src/main/java/internal/__binding-name__Binding.java
nothing big, just a wrong debug message in the binding archetype. I didn't check if it is there in the bindings.
=> fixed cut&paste mistake in binding archetype

bundles/binding/org.openhab.binding.zwave/database/products.xml
Chris,
there is a typo in the products.xml for the newly added zwave.me WALLC-S device.
Regards,
Matt
=> Zwave: Update products.xml: typo

bundles/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBinding.java
There are cases when no transformation of the response is needed.
Therefore put the transformation into a separate function and call it
only if there is a transformation specified in the configuration.
Signed-off-by: domidimi
=> Allow a direct response without transformation

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/filter/SendPageUpdateFilter.java
see #765 , this will help not throw a npe in the logs, but I don't think it fixes anything else.
=> Fixed np check, log exceptions correctly

bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/chart/ChartServlet.java
The log level DEBUG makes it quite hard to find a problem with wrong
parameters in charts. (Particularly as even logback_debug.xml sets the
level of messages from everything below org.openhab.ui to INFO.)
I am not completely sure if ERROR is the right level to use here, perhaps
WARNING (or even INFO) could be enough. But DEBUG is definitely too
low IMHO.
=> changed log level of fatal errors in charts

bundles/binding/org.openhab.binding.fs20/src/main/java/org/openhab/binding/fs20/internal/FS20Command.java, bundles/binding/org.openhab.binding.fs20/src/test/java/org/openhab/binding/fs20/internal/FS20CommandHelperTest.java
fixes issue: FS20 - Converting Value to raw-message fails #1635
openhab/openhab#1635
=> use uppercase strings to compare two hex-value strings

bundles/binding/org.openhab.binding.exec.test/src/test/java/org/openhab/binding/exec/internal/ExecGenericBindingProviderTest.java
Add a simple test to verify the correct parsing of an input exec
configuration.
Signed-off-by: domidimi
=> Add a test for parsing exec binding IN config

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelBinding.java, bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConfigReader.java
If refresh rate is not set in anel-configuration, the default rate for refresh thread (60s) was not read properly, so it used 0s instead. This caused the refresh rate to call 'execute()' every 0s which results in 100% cpu usage.
=> Bugfix #1980: anel-binding caused 100% cpu usage

bundles/binding/org.openhab.binding.http.test/src/test/java/org/openhab/binding/http/internal/HttpGenericBindingProviderTest.java, bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpGenericBindingProvider.java
This fixes [this issue](https://groups.google.com/forum/#!searchin/openhab/string$20http$20not/openhab/SRLsk-A0Mnc/gcU6mk0DGSkJ) where wildcard outgoing commands are never triggered in the http binding. Seems the wildcard command was not considered when the actual command was not directly bound.
=> Fix for http binding not responding to wildcard outgoing commands

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java
influxdb persistence bugfix for issue #1225: log warnings not errors
=> influxdb persistence bugfix for issue #1225

bundles/action/org.openhab.action.xmpp/src/main/java/org/openhab/action/xmpp/internal/XMPPConnect.java
JavaxResolver does not get automatically set. This prevents connection to XMPP services where DNS SRV RR lookups are required in order to connect.
Please also cherry pick into 1.6.
=> Add workaround for SMACK-635 to XMPP action

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java
Fixes issue #1036.
Problem was that if the RRD4jService.query() method was executed at exactly midnight, it would use 00:00:00 as the start time and 23:59:59 of the previous day as the end time. This caused an IllegalArgumentException.
A concern was that the end date was set to currentTime - 1 in the current implementation because the rrd4j library was not able to handle a date in the future (or a date very very close to this).
Therefore I've run a test version without substracting one second (this PR) and another test version with actually adding 10 seconds (to make sure the end date is in the future) on my system for about one week, both of which worked fine.
Possibly it was an old version of the rrd4j library which was not able to handle dates in the future.
=> Fix RRD4J error at midnight

bundles/action/org.openhab.action.xmpp/src/main/java/org/openhab/action/xmpp/internal/XMPPConsole.java
Some messages of Type.chat contain no body, as in "xyz is typing..." notifications. These cause exceptions in the split later on. Returning on those keeps the logs clean.
=> Catch null message bodies caused by status updates

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java
The HOME variant of Anel NET-PwrCtrl device sends only 16 fields in UDP communication packages. Data parser adjusted to support both formats. When only 16 fields are received, the remaining data (IO and temperature) remains unset.
=> Bugfix #2068: support for HOME variant of Anel NET-PwrCtrl device

bundles/binding/org.openhab.binding.mios/examples/transform/miosZWaveStatusIn.map
These status's come from this document:
http://wiki.micasaverde.com/index.php/ZWave_Status
This prevents Mapping-errors from occurring in the openHAB Logs during the nightly MiOS Heal operation.
=> MiOS: Use formal ZWave status names.

bundles/binding/org.openhab.binding.mios/examples/scripts/README.md, bundles/binding/org.openhab.binding.mios/examples/scripts/miosLoad.sh, bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.sh, bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.xslt
This is the initial checkin for a Tool that can extract Metadata from a live MiOS Unit, and generate an appropriate openHAB Items file.  It uses various rules, in the form of an XSLT file, to perform the common translations.
`README.md` included for usage information.
This tool is a formalization of the work at:
* http://forum.micasaverde.com/index.php/topic,30367.0.html
It's gone through several rounds of tuning, and is now being used to build working Items files of 1500-5000 Items from running MiOS systems.
=> MiOS Item file Generator tools (command-line extraction from MiOS Unit)

bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/Modbus.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ASCIIInputStream.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/SerialConnection.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSerialSlave.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java
such that one is able to setup the serial encoding (e.g. ascii, rtu, bin)
along with the other "connection" port settings via the openhab.cfg
First pull request since.. quite a time via github, be nice ;)
=> modbus:serial added "SerialEncodings" selectability 

bundles/binding/org.openhab.binding.pilight.test/.classpath, bundles/binding/org.openhab.binding.pilight.test/.project, bundles/binding/org.openhab.binding.pilight.test/.settings/org.eclipse.jdt.core.prefs, bundles/binding/org.openhab.binding.pilight.test/.settings/org.maven.ide.eclipse.prefs, bundles/binding/org.openhab.binding.pilight.test/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.pilight.test/build.properties, bundles/binding/org.openhab.binding.pilight.test/pom.xml, bundles/binding/org.openhab.binding.pilight.test/src/test/java/org/openhab/binding/pilight/internal/PilightGenericBindingProviderTest.java, bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBinding.java, bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBindingConfig.java, bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightGenericBindingProvider.java, bundles/binding/pom.xml
Number values received from pilight would have the decimal point in the wrong position for some devices. This fixes that and adds a testcase. It also makes sure the initial state is fetched.
=> Fix for scaling decimal values in pilight binding

bundles/binding/org.openhab.binding.zwave/database/products.xml, bundles/binding/org.openhab.binding.zwave/database/swiid/SW-ZCS-1.xml
Added definition for the Swiid ZCS-1 Cord Switch to the product database.
=> Added support for Swiid ZCS-1 Cord Switch to the db

bundles/binding/org.openhab.binding.zwave/META-INF/MANIFEST.MF
The OSGi specification mandates that a bundle declare all package
depenencies using either Import-Package or Require-Bundle. The one
exception to this rule is the java.* packages which is always delegated
to the boot classpath. All other packages dependencies must be declared
in the bundle's manifest file.
This OSGi bundle bundles a xstream jar file that is added to the
classpath. So the MANIFEST.MF of the xstream jar is not evaluated by the
OSGi framework. We have to add the packages, that are necessary for the used
xstream functionality to the import section of the MANIFEST.MF of this bundle.
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
=> zwave: add missing imports (for bundled jar files)

bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBinding.java
Handle the case when the numeric zone code is a hex number.
=> AlarmDecoder binding: handle hexadecimal zone code

bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.xslt, bundles/binding/org.openhab.binding.mios/examples/transform/miosDeviceStatusUI.map
This bug fix is to align with how the documentation shows Contact Item's should be handled for their Label.  It's part of a wider set of changes that will evolve the MiOS Configuration transformation scripts to be more i18n compliant, so users can perform less editing after their initial generation.
Also, for generated *DeviceStatus Items, use a _new_ MAP file (`miosDeviceStatusUI.map`) to map the internal Device Status values into their UI equivalents (under i18n when needed) for display purposes.
=> MiOS Binding Tools - Generate Contact Item values using MAP Transform for i18n (BugFix)

bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/AbstractWidgetRenderer.java
With JVM argument `-DdisableHtmlCache` or `-DdisableHtmlCache=true` you can disable the HTML snippet cache. This is very useful for developing the web parts. Otherwise you always have to restart the runtime to see the changes on html files.
=> Add system property `disableHtmlCache`

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBusReaderScheduler.java
Currently, the interrupted thread status is cleared and swallowed for no reason.
When that catch block is executed (and it is sometimes on my machine), e.g., by the Calimero Link Notifier thread, it causes https://github.com/calimero-project/calimero/issues/14.
=> Restore interrupted status to keep state

distribution/openhabhome/start.sh, distribution/openhabhome/start_debug.sh
With line breaks, its more transparent, which flags are set on startup.
=> More readable startup scripts

bundles/binding/org.openhab.binding.zwave/database/aeon/doorsensor.xml
Fixing as length 4 int (see: http://www.pepper1.net/zwavedb/device/120)
=> Parameter 121 for doorsensor incorrectly defined as byte

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveThermostatModeCommandClass.java
This treats a SET as a REPORT. This can happen on the HRT4 systems that have a separate
thermostat controller that controls a boiler controller. The thermostat is sending the SET MODE
command to the boiler, and by handling this command here we find out as well.
https://github.com/openhab/openhab/issues/2170
=> Treat thermostat mode SET as a REPORT

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBinding.java
If openhab.cfg has a wrong IP set for Hue bridge, openHAB tries to fetch the json, which is null. The HueBinding::execute did not handle this correctly.
=> Hue Binding throws NPE on invalid IP

bundles/binding/org.openhab.binding.maxcul/src/main/java/org/openhab/binding/maxcul/internal/MaxCulBinding.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/CULHandler.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/CULManager.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULNetworkHandlerImpl.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULSerialHandlerImpl.java
Current CUL binding only supports only Cul-Devices with 9600 8E1.
At http://busware.de/ there are several more devices basing on the same firmware (culfw) bu using different configurations. e.g. SCC which is used with the Rasberry PI uses different serial settings (36400 8N1).
So I made some changes to be able to setup the serialport in the CUL-Binding configuration.
The properties baudrate and parity are now forwarded from the org.openhab.binding.maxcul config to the org.openhab.io.transport.cul module.
In the org.openhab.binding.maxcul there was a problem converting the parameters "baudrate" to integer.
Added parse method instead of cast operation.
All changes are backward compatible (if there is no property in config-file, the defaults (which are unchanged) are taken)
What is the …
=> Max binding cul config

bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/Device.java
If actualTemp cannot be extracted (because of vacation or boost mode or if message is invalid/empty), don't publish an invalid actual temperature of 0 °C. This can happen if a window state is changed and the setpoint temperature of a thermostat is set to a new value.
=> Ignore invalid actual temperature reading

bundles/action/org.openhab.action.mios/.classpath, bundles/action/org.openhab.action.mios/.project, bundles/action/org.openhab.action.mios/META-INF/MANIFEST.MF, bundles/action/org.openhab.action.mios/OSGI-INF/action.xml, bundles/action/org.openhab.action.mios/README.md, bundles/action/org.openhab.action.mios/build.properties, bundles/action/org.openhab.action.mios/pom.xml, bundles/action/org.openhab.action.mios/src/main/java/org/openhab/action/mios/internal/MiosAction.java, bundles/action/org.openhab.action.mios/src/main/java/org/openhab/action/mios/internal/MiosActionService.java, bundles/action/org.openhab.action.mios/src/main/java/org/openhab/action/mios/internal/MiosActivator.java, bundles/action/org.openhab.action.mios/src/main/resources/readme.txt, bundles/action/pom.xml, bundles/binding/org.openhab.binding.mios/OSGI-INF/activebinding.xml, bundles/binding/org.openhab.binding.mios/OSGI-INF/genericbindingprovider.xml, bundles/binding/org.openhab.binding.mios/README.md, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/MiosActionProvider.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/MiosBindingProvider.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBinding.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBindingProviderImpl.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnit.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnitConnector.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceBindingConfig.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/MiosBindingConfig.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/ParameterDefaults.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/RoomBindingConfig.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/SceneBindingConfig.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/SystemBindingConfig.java, distribution/pom.xml
This PR contains the initial set of changes to get Action/Rule support for the MiOS Bridge Binding.  Submitting the PR to get functional feedback, and there are a few items that are still on the todo list like:
* #2144 adding queue-limit support, on all HTTP callouts, so-as not to overwhelm the MiOS Unit under control
* ~~refactoring the code (if needed) to use the `org.openhab.io.mios` style/structure (if needed)~~ [Discussion] (https://groups.google.com/forum/#!searchin/openhab/org.openhab.io/openhab/shwaKCdEW68/oafrVa8F1WUJ)
* #2145 work out why the syntactic-sugar version (eg. `GuestBedroom2LightsId.sendMiosAction(...)`) doesn't work when the regular form does (eg. `sendMiosAction(GuestBedroom2LightsId, ...)`)
The changes are as follows:
* Reformatting codebase to new 120 character …
=> MiOS Add initial Action/Rule support for the MiOS Bridge Binding.

bundles/binding/org.openhab.binding.novelanheatpump/OSGI-INF/heatpumpbinding.xml, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/HeatpumpCommandType.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/HeatpumpOperationMode.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpGenericBindingProvider.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatpumpConnector.java
I added for the binding 'org.openhab.binding.novelanheatpump' the feature for changing the operation mode for heating and warmwater. The items are:
Number heatpump_heating_operation_mode   "Heizung Betriebsart [%.0f]"  (gHeatpump) { novelanheatpump="heating_operation_mode" }
Number heatpump_heating_temperatur   "Heizung Temperatur [%.1f]"  (gHeatpump) { novelanheatpump="heating_temperatur" }
Number heatpump_warmwater_operation_mode   "Warmwasser Betriebsart [%.0f]"  (gHeatpump) { novelanheatpump="warmwater_operation_mode" }
Number heatpump_warmwater_temperatur   "Warmwasser Temperatur [%.1f]"  (gHeatpump) { novelanheatpump="warmwater_temperatur" }
I'm new heare. Where can I update the documentation?
Best regards
Michael
=> Support for changing operation mode of novelanheatpump

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBinding.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnitConnector.java
Bug fix for issue #2117 MiOS Binding - Reduce # of changed Items per MiOS Long-poll response
Only emit the Device Id IF at least one state-variable has been changed on the MiOS Device _and_ move the Device Id "device:nnnn/id" to the end of the list of attributes changed, in a given batch of changes for a Device.  This allows users to process Rules off the "batch of changes" as needed.  This can be handy if cross-Item validation Rules are present.
Reduce the # of log lines emitted during Debug mode, making the logs easier to read.
There are cases that MiOS sends out Device change records that contain no UPnP State Variable changes, they're effectively empty with the exception of the "device:nnnn/status" entry.  These are generating noise in the log files.
Use local Device and Scene caches …
=> MiOS Binding: Bugfix for #2117 (Reduce logs/change events)

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceBindingConfig.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/MiosBindingConfig.java
For the most part, this was removing the restriction that would error/exception when users Bound MiOS StateVariables against a Color Item.
This is the bugfix for #2116
=> MiOS Binding - Add support for Color Item for Device Bindings (Bugfix #2116 )

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/RESTApplication.java
On chatty systems, this pool would grow a lot. So limit it.
Signed-off-by: Sebastian Janzen <sebastian@janzen.it>
=> Limit thread pool sizes of Atmosphere

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java
Waiting for test results from Michael issue #2208
=> Influxdb bugfix for issue #2208 (restoring switch or contact state)

bundles/binding/org.openhab.binding.zwave/database/products.xml, bundles/binding/org.openhab.binding.zwave/database/schlage/be468.xml
Note that this is more or less untested, as the Schlage lock seems to require the Security command class to do much of anything, which is not yet implemented in OpenHAB.  Configuration values come from the manufacturer datasheet:
http://www.schlage.com/content/dam/sch-us/documents/pdf/installation-manuals/24352403.pdf
=> Schlage zwave configs

bundles/action/org.openhab.action.mios/README.md
Change the MiOS Action binding example to [correctly] use `sendMiosAction` (from `sendMios`)
Change the TCP Port# used in MiOS API references to `3480` (from `49451`)
=> MiOS Action Binding - Documentation fixes

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
This PR intends to correct a misspelled device feature name on InsteonPLM binding.
I've introduced this error on another PR and as reported by Charles Spirakis (https://groups.google.com/forum/#!category-topic/openhab/insteon/tVq1CmLYD-U) it is causing errors.
=> [InsteonPLM] Correcting misspelled device feature name I've introduced by mistake

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java
When communicating with a DSC alarm system over the IT-100 interface, a user code is required to disarm the system. This user code was being sent when using an envisalink connection to DSC, and we reuse that code for the serial connection with this change. The code is also padded to 6 digits per the IT-100 Developer Guide.
This fixes #2202
=> DSC alarm now sends user code over serial interface

bundles/binding/org.openhab.binding.zwave/database/dragontech/pa100.xml, bundles/binding/org.openhab.binding.zwave/database/dragontech/wd100.xml, bundles/binding/org.openhab.binding.zwave/database/dragontech/ws100.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
I think the BOM on the products.xml file is actually needed by some tool I use, so I put it back with this change.  It should not be needed (as per the unicode spec), but I was getting very weird conflicts on utf8 characters,  and will probably affect others, so backing out that part of my previous change.
=> ZWave configs for Dragon Tech products PA-100, WD-100, WS-100

pom.xml
When I want to change java compiler version I only need overwrite  this properties. 
I needn't overwrite whole plugin configuration.
=> Properties for java compiler version.

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/listeners/ResourceStateChangeListener.java
The rest code was broadcasting both update and changed events, we only want to push changed message. Note, i did no cleanup or formatting changes as the already commented out code may prove useful as a guide for later debugging.  This was in reference to PR #2233 and a conversation around caching.
=> Only listen to changed events, not updates.

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java
If the <SetToController> tag is set to true, and the value is set to 0, and it's not set to the controller
then we set it to 1 hour (3600 seconds).
This covers an initialisation case where the wakeup interval is defaulted to 0
=> Change wakeup logic during initialisation

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java
This fixes a bug where initialisation of a new device doesn't read back the
association and ultimately retries out.
=> Request association group on startup

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java, bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java
Signed-off-by: Kai Kreuzer <kai@openhab.org> (github: @kaikreuzer)
=> adapted rrd4j chart servlet to be compatible with openHAB 2

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModel.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModelRequest.java
Added last_connection property to Nest binding to retrieve when binding last communicated with Nest API servers.  The binding configuration string is 
```
{ nest="<[last_connection]" }
```
=> Nest Enh: item binding for last time binding received from Nest API servers

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java
All three bindings were using an unsynchronized collection to track events to ignore, between the `execute()` thread and a different thread.  This presented the possibility that the collection would fail to properly track events to ignore.  The bindings in this pull request use `Collections.synchronizedList(new ArrayList<String>())` to avoid concurrency problems, and use a single synchronized `remove` call instead of `contains` followed by `remove`.  This has the added benefit of requiring a single linear search instead of two linear searches.
Additionally, the Ecobee and Nest bindings were incorrectly using a `Set` to track item updates to ignore, missing the possibility that multiple of the same item updates could be outstanding and all needing to be ignored.
=> Ecobee-Binding, KNX-Binding, Nest-Binding: Fix ignoreEventList concurrency risk

bundles/binding/org.openhab.binding.zwave/database/philio/pst02.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Configuration of the PST02 is similar to, but not compatible with, the PSM02.
* To receive PIR Motion and Contact updates in OpenHAB set the notification type to "Sensor Binary Report" (set bit 4 to 1 of configuration parameter 7 Customer Function)
=> [Z-Wave] Philio PST02 Slim-Multisensor correction.

bundles/binding/org.openhab.binding.dscalarm/.classpath, bundles/binding/org.openhab.binding.dscalarm/README.md, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmItemType.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmItemUpdate.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/DSCAlarmDeviceProperties.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Keypad.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Panel.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Partition.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Zone.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APICode.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
*Features
-Renamed item 'panel_time_date' to 'panel_time'
-Added item 'panel_time_stamp' to allow the receiving of time stamped messages from the DSC Alarm system.
-Added item 'panel_time_broadcast' to allow the reception of DSC Alarm system time broadcasts for viewing.
*Fixes
-Item 'panel_time_date' (renamed to 'panel_time') was not working.
-Added several methods to binding class to eliminate extra 'for' loop in message receive thread.
-Merged user code fix for the IT-100 serial interface from @beowulfe.
=> DSCAlarm Binding Features and Fixes

bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.xslt
The double-percent (`%%`) characters need to go inside the square-brackets of the Item's label (`"... [    %%]"`) instead of outside.
If they're outside, they mess up the rendering on iPhone/iPad apps.  This happens for Humidity Items that are carried over from the MiOS system.
=> MiOS Tools - For Percentages, the %% should be inside the String/Format of the Item

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveDbProduct.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveProductDatabase.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveNode.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveVersionCommandClass.java
This changes the version comparison from a double to a string. The double was previously used when it was thought that the version was a simple number - it's not - the minor and major parts need to be considered separately and here the double causes problems.
This converts all usage of versions to strings. The actual string comparison hasn't changed as that used the OSGi version classes since the minor/major issue was discovered.
=> Zwave device version comparisson

bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxSynchronizer.java, distribution/src/assemble/resources/README_DROOLS.TXT, distribution/src/assemble/resources/README_addons.TXT, distribution/src/assemble/resources/README_greent.TXT, distribution/src/assemble/resources/README_runtime.TXT
some links to wiki pages were still pointing to the former project wiki on code.google.com
=> fix wiki links

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
implement bindingChanged and allBindingsChanged to reset lastUpdateMap and itemCache
Background: I have a http binding with a long refresh interval (only refreshing once a day), if i change any items file, my http items get reset to "undefined" state and may stay in this state for one more day. 
With this fix items get scheduled for immediate refresh when the the item model is reloaded/changed so the items get re-populated faster
=> reset lastUpdateMap and itemCache on binding change

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
Fixed resetting of items *partition_in_alarm* and *partition_arm_mode* when a user code is used to disarm a partition that is in alarm.
=> Items not being updated when a partition is disarmed while in alarm state

bundles/binding/org.openhab.binding.networkhealth/src/main/java/org/openhab/binding/networkhealth/internal/NetworkHealthBinding.java, distribution/openhabhome/configurations/openhab_default.cfg
The online state of all devices is cached for a certain period of time so that non-changing status updates are not sent every 'refresh' seconds. If a device state changes, this changes is immediately sent to the event bus. Default is 0 (off), so that existing behavior is unchanged if this option is not set.
=> New option for networkhealth binding: cachePeriod.

distribution/openhabhome/configurations/openhab_default.cfg
Make mysql persistent documentation more clear to avoid multiple hours of bug hunting
=> Make mysql persistent documentation more clear

bundles/binding/org.openhab.binding.ecobee/OSGI-INF/binding.xml, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/Selection.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/Thermostat.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/ThermostatRequest.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/ThermostatResponse.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/UpdateSensorFunction.java
This PR fixes a problem using the binding across two or more accounts #2367, removes interrogation of the item registry to suppress updates (based on recent discussions), and implements access to the wireless remote temperature/occupancy sensors that can be added to the ecobee3.  Issue #2366.
=> Add support for ecobee3 remote sensors + bug fixes

bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/IhcBindingProvider.java, bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBinding.java, bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcGenericBindingProvider.java
This modification allows to specify different resources and the wanted value related to the called command.
```
ihc=">123456"
```
Only a single resourceId could be referenced. Values were automatically determined based on the item state.
```
ihc=">[UP:12345:100],>[DOWN:0x9bcd:100],>[STOP:99999]"
```
Syntax:  >[COMMAND:RESOURCE_ID(:VALUE)]
1. Command which is called
2. The resource id to use (hex or int)
3. optional
* if not specified the value will be determined like before
* 1: OnOffType.ON is sent to the resource
* 0: OnOffType.OFF is sent to the resource
* value > 1: Sequence is sent: OnOfType.ON, sleep(value), OnOffType.OFF
=> Ihc command specific outbinding

bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java
Changed GenericItemProvider to catch all exceptions caused by badly behaving bindings.
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: )
=> Improved GenericItemProvider

bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/MaxCubeBinding.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/Device.java
as .equals(null) is not a correct check
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>
=> Small fix to avoid NullPointerException

bundles/binding/org.openhab.binding.mqttitude/src/main/java/org/openhab/binding/mqttitude/internal/MqttitudeConsumer.java
There are some new versions of the Owntracks app in the pipeline which use a slightly different topic for publishing. Along with sending lat/lons as floats (real types) rather than strings as they currently do.
This PR ensures the Mqttitude binding is backward compatible with the current versions of the app but will also work with the new version.
Only change required to binding configuration for the new versions of the Owntracks app, is to add `/event` to the binding topic.
=> Updates to Mqttitude binding in preparation for new iOS/Android apps

bundles/ui/org.openhab.ui.webapp/snippets/main.html
Fixes #2210 .
Caused by a bug in (at least) Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=664720) the onmouseup is not triggered if a synchronous Ajax request made in the onmousedown does not complete soon enough.
Anyway the use of synchronous HTTP Requests seems to be deprecated.
Would be great if this pull request could be reviewed by @sja
=> Make changing of state asynchronous to fix continous sending of dimmer commands

bundles/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/cli/Parser.java, bundles/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBinding.java, bundles/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
- adds pulseaudio 6.0 support (volume format has changed)
I don´t know why the whole files are marked as changes here. I tried this three times from scratch, everytime with the same result. I know that this makes the code-review hard/impossible, but I can´t change it.
All I can do is to describe what has changed:
in cli/Parser.java lines 35/36 (volumePattern), and the parseVolume()-method in line 369
in PulseaudioBinding.java: the activate()/deactivate() methods, and in line 454ff the "if (itemType.isAssignableFrom(SwitchItem.class))" block has been moved before "if (itemType.isAssignableFrom(SimmerItem.class))"
in PulseaudioClient.java in line 437/438 has changes.
Hope this helps to review it and that it is merged before next release as is is a pure bugfix PR
=> - fixes broken refresh/update

bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java
changes discussed in Issue #1934. Adding errCnt to getTable Method
and check connection with JDBC isValid method, before a broken
connection is used to store values, which will result in data loss.
=> MySQL-Persistence: Add errCnt++ to getTable and check connection

bundles/binding/org.openhab.binding.maxcube.test/src/test/java/org/openhab/binding/maxcube/internal/message/MessageProcessorTest.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/MaxCubeBinding.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/IncompleteMessageException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/IncorrectMultilineIndexException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/MessageIsWaitingException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/NoMessageAvailableException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/UnprocessableMessageException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/exceptions/UnsupportedMessageTypeException.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/MessageProcessor.java
I added the support for multiline messages, received from MAX!Cube.
When a MAX!Cube has configured many devices with long names and long room names (I have 54 devices with nice german names configured) the configuration data does not fit into one single M_Message. In this case, the cube splits the message into multiple lines. This was not supported by the former implementation.
Now there is a new class "MessageProcessor" that does the job. All messages received from MAX!Cube are passed to an instance of MessageProcessor. The MessageProcessor recignizes when there are additional lines required for a complete message.
=> Bugfix: Handle multiline messages from MAX!Cube

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMActiveBinding.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceFeature.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceFeatureListener.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceType.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceTypeLoader.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/InsteonDevice.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageDispatcher.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/RequestQueueManager.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Poller.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/SerialIOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/message/Msg.java, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
- use ConcurrentHashMap to avoid synchronized() sections in InsteonPLMActiveBinding class
- fixes for iMeter calculations
- the concept of "related" devices is introduced. When a device
changes its state, all related devices are polled as well. This is
useful for 3-way switch configurations
- a DeviceFeature can now act as a group of other
DeviceFeatures. These feature groups allow for consolidated polling
when one message can query multiple features' values at the same
time.
- added protecting synchronized statements around m_devices in
InsteonPLM binding
- added explicit expiration time to request queue entries to control
message delay better
=> Various fixes and improvements to InsteonPLM

bundles/persistence/org.openhab.persistence.rrd4j/OSGI-INF/rrd4j.xml, bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java, bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java, distribution/openhabhome/configurations/openhab_default.cfg
This will add functionality as requested by issue #180 and allow configurable RRD-archives for all datasource types supported by RRD4J.
rrd4j:ctr5min.def=COUNTER,900,0,U,300
rrd4j:ctr5min.archives=AVERAGE,0.5,1,365:AVERAGE,0.5,7,300
rrd4j:ctr5min.items=Item1,Item2
The old defaults will be used if no special configuration can be found. The names for these defintions are default_numeric and default_other and must not be used in own definitions.
=> Add extended configuration to rrd4j persistence

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
Added a device type for an Insteon device that did not exist. I tested this on my 2457D2.
=> Added Insteon Device Type model 2457D2  - LampLinc Dimmer

bundles/binding/org.openhab.binding.tinkerforge/model/tinkerforge.xcore, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/config/ConfigurationHandler.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/DigitalActorDigitalOut4.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/IndustrialDigitalOutSubIDs.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/MBrickletIndustrialDigitalOut4.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/MIndustrialDigitalIn.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/MIndustrialQuadRelay.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/ModelPackage.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/DigitalActorDigitalOut4Impl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletIndustrialDigitalOut4Impl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MIndustrialDigitalInImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MIndustrialQuadRelayImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/ModelFactoryImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/ModelPackageImpl.java
Fix handling of device aliases for: dual_relay, quad_relay, joystick_xposition, joystick_yposition, digital_4in and digital_4out.
=> TF binding: Fix for configuration handling of device aliases

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMeterConverter.java
Very minor change, just improves the debug messages if a METER_RESET request is made on a device which doesn't support it.
=> Improve log messages when attempting a meter reset

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Removed workaround for KNX DPT_TIME. KNX time of type "no-day, HH:MM:SS"
will now be translated to current weekday: "Fri, HH:MM:SS" instead of
omitting the weekday part.
=> Bug fix for KNX binding, Time update from ntp in March #2330

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Removed tests for multiple time zones. Reason: tests failed for some
time zones like "Europe/Brussels", since setting the default time zone
in java had unexpected consequences.
These tests were introduced to check if the date/time conversion from
KNX to openHAB would work in different time zones due to the initial
#1344 observations.
=> Attempt to fix for bug #1344 (again)

bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/internal/FritzboxBinding.java
Clean Commit. Old PR #2445 was messed up while rebasing.
=> Fix issue #1845, try 2

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
Some logging statements in the KNX binding contained a typo and did not contain a placeholder for the supplied parameter 'datapoint".
=> Fixed error in KNX logging statements (used for autoRefresh).

bundles/binding/org.openhab.binding.autelis/.classpath, bundles/binding/org.openhab.binding.autelis/.project, bundles/binding/org.openhab.binding.autelis/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.autelis/OSGI-INF/binding.xml, bundles/binding/org.openhab.binding.autelis/OSGI-INF/genericbindingprovider.xml, bundles/binding/org.openhab.binding.autelis/README.md, bundles/binding/org.openhab.binding.autelis/build.properties, bundles/binding/org.openhab.binding.autelis/pom.xml, bundles/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/AutelisBindingProvider.java, bundles/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisBinding.java, bundles/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisGenericBindingProvider.java, bundles/binding/pom.xml, distribution/openhabhome/configurations/openhab_default.cfg
Signed-off-by: Dan Cunningham <dan@digitaldan.com> (github: digitaldan)
=> Initial Commit of the Autelis Pool Control binding for openHAB

bundles/action/org.openhab.action.prowl/src/main/java/org/openhab/action/prowl/internal/Prowl.java
During looking around who to implement Actions i stumbled across a method remaining from the skeleton build. I think it can be deleted.
@teichsta Is it ok for you to do pull request for such small cleanups or do you prefer to have a bigger pull request with a collection of them? I am just asking, to fit better into your way of development.
=> code cleanup, remove skeleton Action from Prowl that does nothing

bundles/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBinding.java
- Fixed bug where defining the "numberOfSprinklers" parameter makes the add-on silently fail to load.
- Added number of stations parameter validation.
=> OpenSprinkler Bugfix: Addon Silently Fails to Load When numberOfSprinklers is Defined

bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java
Extended night mode support to the newer RGBW bulbs.
The white Milight bulbs have 10 levels of brightness + Off so there are 11 possible settings between 0 and 100%. It was at 10 settings and so a disparity between desired brightness setting vs. actual brightness would accrue during use. Also, to engage the desired bulb, an on signal needed to be sent before the brightness setting. Lastly, white bulbs are powered to lowest setting before off, and when powering on this is taken into account. All these fixes combined finally allows the brightness to be very accurate and reliable for the white bulbs.
=> Milight Binding: Added Nightmode support for the newer RGBW bulbs, Fixed brightness setting for White.

bundles/binding/org.openhab.binding.systeminfo.test/.classpath, bundles/binding/org.openhab.binding.systeminfo.test/.project, bundles/binding/org.openhab.binding.systeminfo.test/.settings/org.eclipse.jdt.core.prefs, bundles/binding/org.openhab.binding.systeminfo.test/.settings/org.maven.ide.eclipse.prefs, bundles/binding/org.openhab.binding.systeminfo.test/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.systeminfo.test/SysteminfoBindingTests.launch, bundles/binding/org.openhab.binding.systeminfo.test/build.properties, bundles/binding/org.openhab.binding.systeminfo.test/pom.xml, bundles/binding/org.openhab.binding.systeminfo.test/src/test/java/org/openhab/binding/systeminfo/internal/SysteminfoGenericBindingProviderTest.java, bundles/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoGenericBindingProvider.java, bundles/binding/pom.xml, bundles/model/org.openhab.model.item/src/org/openhab/model/item/binding/AbstractGenericBindingProvider.java
This fixes the absolute path problem from #2430 and adds a package of unit tests for the systeminfo binding.
=> Fix absolute path problem in systeminfo Binding and add unit tests

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveController.java
This provides a function within HABmin to allow a node to be reinitialised without restarting the binding.
=> Zwave reinitialise node

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBinding.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBulb.java
FIx for issue #2470.
Introduced constants for max brightness and saturation and changes both max values from 255 to 254.
=> Set max value of saturation and brightness to 254 as defined by Hue API

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/IOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Port.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/hub/OldHubIOStream.java, distribution/openhabhome/configurations/openhab_default.cfg
The InsteonPLM binding now also supports the "old" InsteonHub via its raw tcp port. (The 2014 Hub is already supported, but only through its http interface). The following line in openhab.cfg will connect to the raw tcp feed of the insteonhub:
insteonplm:port_0=/hub/localhost:9761
=> InsteonPLM binding: support the standard pre-2014 InsteonHub

bundles/binding/org.openhab.binding.withings/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.withings/OSGI-INF/authenticator.xml, bundles/binding/org.openhab.binding.withings/OSGI-INF/binding.xml, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/WithingsBindingConfig.java, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/WithingsBinding.java, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/WithingsGenericBindingProvider.java, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAccount.java, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsApiClient.java, bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAuthenticator.java
this PR supersedes #1695
The main change lies in parsing the openhab.cfg file differently. One can simply add the needed parameters like this
```
withings-oauth:userid=4866592
withings-oauth:consumerkey=74c0e77021ef5be1ec8dcb4dd88c1xckusadwe92f9541c86799dcbbfcb8fc8b236
withings-oauth:consumersecret=25f1098209xns511711b3287288f90740ff45532cef91658c5043db0b0e0c851c
withings-oauth:token=e587df2b08fec066c7643081c649e8517987f6c25d8089d4230987399e28d6
withings-oauth:tokensecret=7c16e5f2f1f5fd784211bfff7c1435jh2d9419e503c5d079e114719b66dcef9
```
or additionally add an user id to which this credentials belong to like:
```
withings-oauth:thomas.token=74c0e77021ef5be1ec8dcb4dd88c1xckusadwe92f9541c86799dcbbfcb8fc8b236
withings-oauth:thomas.tokensecret=25f1098209xns511711b3287288f90740ff45532cef91658c …
```
=> [Withings] allow multiple withings accounts

bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/internal/engine/RuleEngine.java
See Issue #2362 for details.
I unravel any sharing of contexts, occurring within the file, so a unique `RuleEvaluationContext` is used in all cases.  Changes mostly relate to changing `executeRules(...)` calls, so they don't take a [shared] `RuleEvaluationContext`
The rest of the diffs are due to formatting changes (use of newer Eclipse openHAB profile)
After the change, the testcase from Issue #2362 is running correctly (tweaked TC to run every second instead of every 10)
```log
10:53:26.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
10:53:26.005 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
10:53:26.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
10:53:26.006 DEBUG o.o.m.r.i.engine.RuleEngine[:305]- Executing rule …
```
=> Issue#2362 Core-Rules: Rule threading/Context corruption issue (Thread Safety)

bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/items/ItemUIRegistryImpl.java
Fixes #2617.
I don't think this is the best solution as there is no reason to try looking up the item if we already know it is not there (because it is null) and also possible 'real' errors are now logged on debug level.
But then again the previous solution (`label.contains("[")`) wasn't so neat either and the if-check was probably removed for a reason so I didn't want to change it back.
Therefore the logging on debug level is probably a good compromise until somebody comes up with a better solution :-)
=> Change logging for not found item from error to debug

bundles/persistence/org.openhab.persistence.jpa/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
An NPE is thrown if no user/password is supplied. This might be the case if an embedded database is used where the user/pass is not needed as it's linked in with no net access (or I guess if you're silly enough to have a server with no password, but I guess not too many people do that!)...
=> JPA persistence: Avoid null pointer exception if no user/password defined

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/resources/SitemapResource.java
URLs for WebView using /proxy are missing the anchor/fragment attribute.
Check e.g. rest/sitemaps/ours/0102 (which must contain a webview with anchor (alias fragement) specified using #
In my case:
Webview url="http://www.sample.com/?test&sp=IGERS72#forecast"
becomes
http://192.168.0.78:93/proxy?sitemap=ours.sitemap&widgetId=01020300
however, it should be:
http://192.168.0.78:93/proxy?sitemap=ours.sitemap&widgetId=01020300#forecast
This is fixed by this tiny PR.
Please test first! I was not able to compile openHAB due to some weird mvn errors...
Without this, the Android client cannot handle the anchors. (Browser view is not affected.)
=> Add anchor to proxy URL

bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/FritzboxBindingProvider.java, bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/internal/FritzboxBinding.java
Hi
This is my first try with both github and openhab... The changes are not tested, but intend to add support for the second wlan ap in a FritzBox, such as the 7490.
Thanks for considering.
Best,
Chris
=> Add support for second wlan AP in fritzbox binding

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModel.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Thermostat.java
Users check [the wiki page](https://github.com/openhab/openhab/wiki/Nest-Binding) (updated shortly) for a note about changing permissions to Thermostat read/write v3, reauthorizing your client and updating `nest:pin_code` in `openhab.cfg`.  
Closes #2658.
=> [Nest] Enh: Add hvac_state property to thermostat object

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/msg_definitions.xml
The message template for ALLLinkCleanupFailureReport (code 0x56) is incorrect due to documentation error.
This bug fix addresses parsing errors reported here:
https://groups.google.com/forum/#!category-topic/openhab/insteon/S3uncGTopKo
=> InsteonPLM: fixed faulty message definition for 0x56 

bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonConnector.java
Some devices do not support the device info URL, this change makes the binding continue nevertheless.
=> Small tweak for the Denon binding

bundles/binding/org.openhab.binding.yamahareceiver/META-INF/MANIFEST.MF
This somehow got missed and in the current 1.7 release the Yamaha binding is stamped as v1.5! Whoops!
=> Fix to YamahaReceiver binding MANIFEST.MF bundle-version

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/RESTApplication.java
Support for Cross-Origin Resource Sharing (CORS) in the REST API was lost in 1.7.0 because of the update of Atmosphere. This again adds the necessary interceptor.
=> Re-enable CORS for REST API

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveThermostatModeCommandClass.java
Hi, I'm trying to integrate my StellaZ thermostatic valves. I just realized that the "Manual" ModeType is missing in OpenHab Thermostat Mode Z-Wave binding. Manual mode is fundamental when using these kind of valves because without setting the Thermostat Mode to manual one could not adjust the dimming point apart from using the valve's internal mechanism (which is based on the valve temperature sensor).
Setting the dimming point on these valves is possible only after having set their thermostat mode to "Manual", which is an option currently unsupported in OpenHab's Z-Wave binding. This commit adds the missing ModeType to make it work.
=> Add support for "Manual" ModeType (StellaZ)

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/CULManager.java
I have created a fix to patch issue #2671. Please see also https://groups.google.com/forum/#!category-topic/openhab/discussions/430B_IhTXDw
BR
André
=> Fix for issue #2671: Added empty property list to getCulHandler method

bundles/binding/org.openhab.binding.piface/scripts/ohpiface.py, bundles/binding/org.openhab.binding.piface/src/main/java/org/openhab/binding/piface/internal/ErrorResponseException.java, bundles/binding/org.openhab.binding.piface/src/main/java/org/openhab/binding/piface/internal/PifaceBinding.java
Here is proposed fix for #2679. Has been discussed with Ben Jones (@sumnerboy12).
Some of the changes involves migrating from the use of an -1 error return code to the use of an Exception in the sendCommand method. The method only returns a byte and we need the whole byte for the output pin state.
=> PiFace binding reads wrong state for output pins upon startup (#2679)

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
For users of the Ecobee binding who have more than one thermostat that are managed under the same account at ecobee.com, this is an important bugfix that ought to be in 1.7.1.  The `readEcobee` method was iterating through all in-bound items from that account and setting their states, even if the thermostat that that item refers to had not changed and was therefore not in the payload returned from ecobee, resulting in sometimes Uninitialized items.
=> Ecobee bug: Only update item if we know we retrieved the thermostat it refers to.

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java
Some thermostats (Trane) do not support setpoint values other than integers.  This change will strip any trailing zeros on BigDecimal numbers to ensure a minimum scale.
=> Increase compatibility with some thermostats

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/SerialIOStream.java
=> InsteonPLM: attempted fix for incompatibility with Z-Wave binding

bundles/action/org.openhab.action.squeezebox/src/main/java/org/openhab/action/squeezebox/internal/Squeezebox.java
seems that without this option, google api has problems with proper handling of non-ascii characters in query string
=> added indication of input encoding for google tts service

bundles/ui/org.openhab.ui.webapp/web/WebApp/Design/Firefox.css, bundles/ui/org.openhab.ui.webapp/web/WebApp/Design/Render.css
As of 2015, the majority of browsers supports `border-radius` CSS property [without any vendor-specific prefixes](http://caniuse.com/#feat=border-radius). Moreover, modern Firefox versions do not support this property with `-moz-` prefix. Therefore, non-prefixed versions were added. I think it's probably safe to remove all prefixed values (thus getting rid of firefox.css), but as for now this works too.
Also, there is a fix for “back” button display in Firefox.
=> Webui CSS fixes for non-webkit browsers

bundles/binding/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/client/constants/OutputModeEnum.java, bundles/binding/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/client/entity/impl/JSONDeviceImpl.java
Small change to support LED dimmers which have another output mode on Digitalstrom than "normal" dimmers.
=> added outputmode 51 for led dimmers like GE-UMV200

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/messages/Temperature.java
Avert ArithmeticExceptions for non-terminating decimal expansion when converting to/from Celsius.  I imagine very few Ecobee binding users are using Celsius, but for those that are, this fix would be required.
=> Ecobee binding bug: BigDecimal needs precision/rounding when converting to/from Celsius

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
Do not mistakenly log errors when `http:timeout` or `http:granularity` are specified in openhab.cfg.  Addresses #2814 .
=> [http] False error logged when timeout or granularity given in openhab.cfg

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java
This just moves the error to only be displayed if configuration is required, and the configuration class isn't supported.
=> Check if configuration is needed before reporting error

bundles/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxBinding.java
Please find a fix for the issue #2789.
=> Fix for Freebox in bridge mode (issue 2789)

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoPressureUnit.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoUnitSystem.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/DeviceListRequest.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/DeviceListResponse.java, distribution/openhabhome/configurations/openhab_default.cfg
Implemented both unit system and pressure unit in the same manner as implemented by the Netatmo apps (web, Android). Unit systems supported are Metric and US. Pressure units supported are mbar, inHg, and mmHg.
=> Added support to Netatmo for unit system and pressure unit

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
_Problems:_ (1) Discovered that some users were not entering their OAuth PIN at ecobee.com within the [9-minute window](https://github.com/openhab/openhab/wiki/Ecobee-Binding#authentication), which was causing an auth token to be persisted that was not usable.  When this happens, there is no way to retrieve a new PIN unless the user knew how to find and move or delete the absurdly named and platform-specific Java Preferences file where the bad auth token was stored.  (2) Users would then attempt to [create a new app at ecobee.com](https://www.ecobee.com/developers/) and enter the new `ecobee:appkey` in openhab.cfg.  The binding would not realize that the `ecobee:appkey` had changed from when the old tokens had been stored, so this was not the solution the user was hoping it would be. …
=> Ecobee: two cases where tokens should be ignored or discarded.

bundles/action/org.openhab.action.mios/README.md
Sync documentation with Wiki version, so we always have the latest with the codebase.
Include a hyperlink reference for the MiOS Documentation for UPnP Calls,
since the Actions / Parameters aren't always obvious.
=> MiOS Action: Modify the README.md to reference to the MiOS Doc for UPnP Calls.

bundles/binding/org.openhab.binding.energenie/src/main/java/org/openhab/binding/energenie/internal/EnergenieBinding.java
Maybe through a new Firmware version on the device the state response changed. (a wide space was removed) so the search string has to be changed as well. 
Also the if condition could be improved. lastIndexOf() returns -1 if it fails so the if condition was executed anyway because there was tested on !=0 and later on a null pointer exception happened. Now this is solved with the new condition.
=> [Energenie] State response changed? 

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexBinding.java
The latest release of the Plex Media Server (PMS, version 0.9.12.4) slightly changed the format of the machine ID in the session information. Because of this properties like state, title, etc. were no longer working in the binding. This PR fixes this. 
Could this be included in 1.7.1? Bug is also referenced here: https://groups.google.com/d/msg/openhab/-xkZGLY_zOs/Ekd-t11c4TYJ
=> Fix state properties Plex binding latest PMS

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java
Without this handling my CUNO lost the connection every 24h. This bug is tested for about a half year and no more connection failures occures.
=> Error handling for cul network devices

bundles/binding/org.openhab.binding.zwave/database/aeon/zw096.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ConfigurationParameter.java
removed maximum settings where they did not make sense
added additional international Type ID codes for US, EU, AU, CN
=> z-wave binding zw096 - added additional international Type ID codes for US, EU, AU, CN

products/org.openhab.designer.product/org.openhab.designer.product.product
See discussion at https://groups.google.com/forum/#!topic/openhab/WpbdsFUGCug. This parameter seem to have a longer history through the Eclipse versions since it has been valid as a workaround got invalid and valid meanwhile (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=404776 for more details of the underlying bug).
=> remove -Dorg.eclipse.swt.browser.DefaultType=mozilla startup parameter again

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/ConnectionStatusBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelGenericBindingProvider.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/ConnectionStatusEvent.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR replaces #2865 
copied description: This PR allows to define items for connection status to the module. Currently there are 3 new binding configurations added:
module:connected - simple binary flag active when there is connection established,
module:connected_since - a timestamp describing when connection has been established,
module:connection_errors - a number describing number of connection errors in a row; it is cleared after connection has been established.
=> [satel] Connection status implemented

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmItemType.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/SerialConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/TCPConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/DSCAlarmDeviceProperties.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Panel.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Partition.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
Here are some feature additions made to the DSC Alarm binding:
1. The following new items were added to display panel trouble conditions which was not possible previously.
* **panel_trouble_led**
* **panel_service_required**
* **panel_ac_trouble**
* **panel_telephone_trouble**
* **panel_ftc_trouble**
* **panel_zone_fault**
* **panel_zone_tamper**
* **panel_zone_low_battery**
* **panel_time_loss**
* **panel_trouble_message**
2. The item **partition_opening_closing_mode** was added to show which opening/closing method was used, and to separate those messages from the **partition_status** item.  This was by request from openHAB Google Group as seen here: https://groups.google.com/d/msg/openhab/71Ku6VOf16o/GpI0t25wWXcJ.
3. A new configuration option was added to suppress the display of …
=> DSC Alarm Binding - Feature Additions

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java
This code change attempts to suppress rare cases where an attempt to cancel an update echo fails.  An update echo is when the `execute()` method polls the Nest API and sends updates on the event bus for bound items.  The binding's `internalReceiveUpdate` method, which is intended to handle updates from all other sources, consults a dynamic list of events to ignore and upon finding and removing a matching event, does not forward the update back to the Nest API.  In rare cases and as yet unexplained, the echo cancellation fails and the binding sends the update back to the Nest API.
This code change employs two approaches to suppress this behaviour:
1. Instead of using a string concantenation of the `itemName` and string version of the new `State` as previously, it places `Update` objects on …
=> Nest-Binding: Suppress occasionally failing update echo cancellations.

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
Identical problem as in #2930.  I had implemented a lesser-quality workaround already in the PR for the ecobee action bundle (#2755) but I will merge this one into that PR instead.
=> Ecobee-Binding: Suppress occasionally failing update echo cancellations.

distribution/pom.xml
=> debfiles: remove execute bits from openhab.service file

distribution/openhabhome/configurations/openhab_default.cfg
Panasonic TV was missing in default config file.
=> Add Panasonic TV to default configuration file

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
1.7.1 fix for issue https://github.com/openhab/openhab/issues/1820, if the token was expired, the token was refreshed and a recursive call was made to re-execute the binding, this would cause null pointer exceptions in the original execute call to the binding.
=> Netatmo: 1.7.1 fix for issue #1820

bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/calls/PlayerGetItem.java
Properties returned as lists were only processed if there also was an indexer property available. However, some properties come back as a list without an indexer. For those, instead of not processing them at all, return the first in the list.
This fixes the problem where the artist is never displayed, while the album name and song title are displayed.
=> [XBMC] Fixes properties like Player.Artist always being empty.

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
The user number has been added to the message shown in the PANEL_MESSAGE item when the alarm system is armed (closed) or disarmed (opened) by the User Opening/Closing Methods.  This is per request from issue #2951.  Also, the partition number has been added to the message.  The event log will show the following entries for item PANEL_MESSAGE when it is updated:
2015-07-26 11:04:26 - PANEL_MESSAGE state updated to 700: Partition 1 has been armed by user 0040.
2015-07-26 11:04:43 - PANEL_MESSAGE state updated to 750: Partition 1 has been disarmed by user 0040.
Thanks,
Russell
=> DSC Alarm: Adds User Number to User Opening/Closing Messages

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/resources/SitemapResource.java, bundles/model/org.openhab.model.sitemap/src/org/openhab/model/valueconverter/SitemapConverters.java
This fixes the root cause of the Classic UI not supporting double quotes in Mapping commands.
When enclosing the command in double quotes, the double quotes become part of command. This causes two problems:
* HTML gets formatted as ""the command"" instead of "the command"
* "the command" != the command so there can never be a match and as a result the switch and selection item do not work properly when the command is wrapped in double quotes
Reported problems/issues:
* This fixes the problem reported [here](https://groups.google.com/forum/#!category-topic/openhab/sitemaps/wFbXRT1LWxg) with the Harmony Hub Binding.
* #1414
* Probably #1837 as well.
Discussion topic can be found [here](https://groups.google.com/forum/#!category-topic/openhab/sitemaps/D-PpPY-ixns).
=> Strip off the double quotes from the mapping command in case they exist.

bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/RulesRuntimeModule.java, bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/valueconverter/RuleConverters.java
In rules, double quotes should not be part of the state/command string. This fix removes them.
Item <item> received command "Armed Away"
Item <item> received update "Armed-Away"
Item <item> changed from Disarmed to "Armed-Away"
Without removing the double quotes, the rule will never trigger because Armed-Away != "Armed-Away".
Fixes issue #2552 Rule trigger 'changed from to' does not work for string items
Replaces PR #2578 quick-fix for issue #2552, as suggest as option 2
I tested this using a String item which I changed to "Armed Away", "Armed-Away", "Disarmed" and Disarmed using both sendCommand() and postUpdate(). It would be good if the reporter of issue #2552 could verify the fix.
=> Fix for #2552. Allow the use of double quotes around state/commands in rules

bundles/binding/org.openhab.binding.zwave/database/eco/tiltzwave2.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Added tiltzwave2 to database and updated product file per Issue #1411. I
recognize this was probably unnecessary but I had the xml created with help
in CDATA consistent with OH2 parameters before I realized the
products.xml had been updated to incorporate the existing XML. Decided
to push as the issue is still open.
=> Update Eco Link Database

distribution/openhabhome/configurations/openhab_default.cfg
openhab_default.cfg is not consistent with
https://github.com/openhab/openhab/wiki/Modbus-Tcp-Binding
"modbus:slave1.host" seems not to work, while
"modbus:tcp.slave1.connection" in fact does.
=> Corrected the Modbus parameters in openhab_default.cfg

bundles/binding/org.openhab.binding.zwave/database/enerwave/zw20r.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
This pull request is to add the Enerwave zw20r duplex receptacle to the zwave binding
=> z-wave: add Enerwave as a vendor (011a) and add device zw20r

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveMultiCommandCommandClass.java
=> Fix incorrect endpoint when MULTI_CMD command class used

bundles/binding/org.openhab.binding.zwave/database/linear/ngd00z.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Attempting to add a new zwave item for a Linear garage door opener controller.
Please verify that this looks ok as this is my first attempt at doing this.
Details here: http://www.pepper1.net/zwavedb/device/684
File eco/tiltzwave2.xml used as an example
=> Add linear garage door opener controller

bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java
When communication with the Pushover API fails, a null exception is through producing a confusing message with a useless stacktrace. Brought up in #2943 with discussions about Pushover service.
=> Pushover: Added A Clean Error Message to the Pushover Service API Not Responding

bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/LocationItem.java, bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/PointType.java
* Location items could not receive any commands; now they can receive PointType commands.
* Location items could not receive PointType updates because PointType had no zero-arg (nullary) constructor, which [this code](https://github.com/openhab/openhab/blob/master/bundles/core/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemUpdater.java#L59) requires of State classes.
I have not yet tested these changes.  @clinique and @teichsta, please comment when you can.
This code diff looks wrong because these two files previously had Windows CR/LF line endings.  They now have LF line endings.  Here is the readable diff output:
```
$ git diff --ignore-space-at-eol
diff --git a/bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/LocationItem.java …
```
=> Allow Location items to receive commands and updates (ref #3104)

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java
If there is an error polling the Nest API (usually due to network issues), the failed poll would log as an ERROR and dump a stacktrace to openhab.log which is typically unhelpful.  Since network issues are usually temporary, this PR changes the log to WARN and the stacktrace is now not dumped (only the exception message is logged).  However, at the DEBUG level the stacktrace is dumped to the log for the non-typical failure situation.  @mrguessed, do you agree that this would be better?
=> [Nest] Quiesce logging on status poll

bundles/action/org.openhab.action.mqtt/.classpath, bundles/action/org.openhab.action.mqtt/.project, bundles/action/org.openhab.action.mqtt/META-INF/MANIFEST.MF, bundles/action/org.openhab.action.mqtt/OSGI-INF/action.xml, bundles/action/org.openhab.action.mqtt/build.properties, bundles/action/org.openhab.action.mqtt/pom.xml, bundles/action/org.openhab.action.mqtt/src/main/java/org/openhab/action/mqtt/internal/Mqtt.java, bundles/action/org.openhab.action.mqtt/src/main/java/org/openhab/action/mqtt/internal/MqttActionService.java, bundles/action/org.openhab.action.mqtt/src/main/java/org/openhab/action/mqtt/internal/MqttActivator.java, bundles/action/org.openhab.action.mqtt/src/main/java/org/openhab/action/mqtt/internal/MqttMessagePublisher.java, bundles/action/org.openhab.action.mqtt/src/main/resources/readme.txt, bundles/action/pom.xml, features/org.openhab.designer.feature/feature.xml
This is a small enhancement adding MQTT Action to OH. It can be used in rules to simply publish the MQTT message to topic using configured broker. I can see it useful to work with the project like mqttwarn simplifying MQTT message routing.
=> MQTT Action bundle

bundles/binding/org.openhab.binding.zwave/database/products.xml
The device I have has a different device ID than what was in the xml and on pepper1 database. I have added it.
=> Added new Reference for Linear NGD00Z-4

bundles/io/org.openhab.io.multimedia.tts.googletts/src/main/java/org/openhab/io/multimedia/internal/tts/TTSServiceGoogleTTS.java, distribution/openhabhome/configurations/openhab_default.cfg
Fix URL of GoogleTTS by adding a `client` parameter to the URL as discussed in the [openHAB forum](https://groups.google.com/forum/#!msg/openhab/Sb8CuHDDCBk/O2OulKYCAwAJ) and on [stackoverflow](http://stackoverflow.com/a/31791632/3049015).
=> Fix URL of GoogleTTS service after API changes

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/AbstractRequest.java
Ecobee's API servers are producing very frequent HTTP request timeouts, so the previously hard-coded 10-second timeout is proving to be too short to complete many polls.  By adding 
```
ecobee:timeout=20000
```
to your openhab.cfg file, you will increase the HTTP request timeout from the default 10 seconds to 20 seconds.  There is no way to know if this is long enough for the HTTP request to succeed, but this gives the binding user the chance to extend the timeout as they see fit.
Also incorporated's @mrguessed's advice on having a single log message (with optional stack trace if in DEBUG logging mode).
=> [Ecobee] Added optional ecobee:timeout config param

bundles/binding/org.openhab.binding.zwave/database/benext/doorsensor.xml, bundles/binding/org.openhab.binding.zwave/database/benext/switch.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Add BeNext Power Switch as supported Z-Wave device, based on http://www.pepper1.net/zwavedb/device/299, but with Product ID 0x0101 instead of Product ID 0x0100
=> Add BeNext Power Switch and Door Sensor as supported Z-Wave devices

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBridge.java
The error described in https://community.openhab.org/t/hue-pairing-error/2969 is difficult to analyze because the logging output is not sufficient.
Therefore this pull request improves logging output when retrieving JSON settings from the hue bridge.
=> Improve logging output for HueBinding when retrieving settings

bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/DateTimeItem.java
Some time ago I made DateTimeType a command, but forgot to add this type to accepted commands in DateTimeItem, which prevents sending commands as String. This PR fixes this issue.
=> Fix for DateTimeItem to accept DateTimeType commands.

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexActivator.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexBinding.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnectionProperties.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/User.java, distribution/openhabhome/configurations/openhab_default.cfg
If you're using Plex Home the binding needs to know additional credentials to access the Plex server. This fixes #3120.
=> Update Plex binding to support Plex Home

bundles/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisGenericBindingProvider.java, bundles/binding/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/DigitalSTROMBindingProvider.java, bundles/binding/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/DigitalSTROMGenericBindingProvider.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmGenericBindingProvider.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnoceanGenericBindingProvider.java, bundles/binding/org.openhab.binding.freeswitch/src/main/java/org/openhab/binding/freeswitch/internal/FreeswitchGenericBindingProvider.java, bundles/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubBinding.java, bundles/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubGenericBindingProvider.java, bundles/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmniLinkGenericBindingProvider.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireGenericBindingProvider.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelGenericBindingProvider.java, bundles/binding/org.openhab.binding.xpl/src/main/java/org/openhab/binding/xpl/internal/XplGenericBindingProvider.java, bundles/model/org.openhab.model.item/src/org/openhab/model/item/binding/AbstractGenericBindingProvider.java
Trying to find the proper fix for #2842 and #1419.  Found lack of thread safety around protected `contextMap` member of `AbstractGenericBindingProvider`.  Also found bindings performing unnecessary and bug-inducing changes in their overrides of `processBindingConfiguration` calls.
Please review this code carefully (as I'm sure you would anyway).  I've added line comments in the changes to explain my thinking.  These changes are not tested, but here to spur others' thinking about the origins of #2842 and #1419.
=> Improve thread safety around contextMap

bundles/binding/org.openhab.binding.hue/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBinding.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBridge.java
Probably caused by a recent hue API change, the hue binding incorrectly shows the message that pairing would be necessary on each startup (as discussed [here](https://community.openhab.org/t/openhab-continiously-loosing-connection-to-hue-bridge/3013))
Instead of just parsing the json result for "error", this pull requests checks if the JSON response is the one defined by the API for authorization error.
=> Fix incorrect pairing message for hue binding

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/ConnectionStatusBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBinding.java
This PR fixes the way initial refresh is done for items added after connection is established. 
Since items are updated only when appropriate state in the alarm system changes, items require initial poll of current state when new item added. This is done through additional flag in binding configuration.
=> [Satel] Items initial poll fix

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java
This patch adds support for hue devices that offer only on/off switching, no dimming. They deliver no brightness information so without this change, an exception is thrown. The patch returns 0 or 254 based on the "on" state of the hue device.
=> Add support for 'On/Off plug-in unit' in hue binding

bundles/binding/org.openhab.binding.zwave/database/products.xml
Added an additional Z-Wave Device Reference Type/ID for Fibaro FGFS101 for ID 2001
=> Added additional device Type/ID for Fibaro FGFS101

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/Thermostat.java
Access to properties like `runningEvent.type`, `runningEvent.name`, `runningEvent.holdClimateRef` and any fields present in the [Event object](https://www.ecobee.com/home/developer/api/documentation/v1/objects/Event.shtml).
Access to events was already possible by indexing the list of events, but it was difficult in openHAB to locate the running event without this new property.  When there is no running event, this property set returns `UnDefType.NULL`.
=> [Ecobee] Add runningEvent property for simpler access.

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestActivator.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Camera.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModel.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Structure.java
The Nest Cloud API recently released support for the [Nest Cam](https://nest.com/camera/meet-nest-cam/).  This PR adds support for it.  The new API lets you start and stop the camera streaming, effectively turning the camera off an on.  All other values are read-only.
New binding strings available (full set available only if you set the proper permissions in your Nest Client, authorize the binding with new PIN, and subscribe to Nest Aware with Video History):
```
String CamDeviceId "CamDeviceId [%s]" { nest="<[cameras(Dining Room).device_id]" }
String CamSWVersion "CamSWVersion [%s]" { nest="<[cameras(Dining Room).software_version]" }
String CamName "CamName [%s]" { nest="<[cameras(Dining Room).name]" }
String CamNameLong "CamNameLong [%s]" { nest="<[cameras(Dining Room).name_long]" } …
```
=> [Nest] Enh: Added support for Nest Cam

bundles/binding/org.openhab.binding.insteonplm/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.insteonplm/src/main/docs/insteoplm_v1.7.md, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/CommandHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceFeature.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/FeatureTemplate.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/FeatureTemplateLoader.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/InsteonDevice.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageDispatcher.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/ModemDBBuilder.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/PollHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/RequestQueueManager.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/IOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Poller.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Port.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/SerialIOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/hub/HubIOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/hub/ReadByteBuffer.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/message/Msg.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/utils/Utils.java, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
Improved InsteonPLM binding:
- cleaner exit of binding for faster shutdown (it doesn't shut down any faster though)
- better diagnostic output in case Hub2 fails to connect
- added support for FAST On/Off
- added new device: 2456S3 Appliance link
- complete rewrite and expansion of the thermostat support
- removed modem control commands (no longer needed, use insteon terminal for that)
- shorter timeout for faster manipulation of switches that don't respond with ACK
- added feature to send group broadcasts directly from modem
Minor fix to the Alarmdecoder binding:
- cleaner exit
=> InsteonPLM binding: better thermostat support, FAST On/Off, bug fixes and new devices

bundles/binding/org.openhab.binding.zwave/database/aeon/minimote.xml
This param allows putting the remote into "Scene" mode which is necessary to use it properly with openHAB.
=> Add param 250 to Aeon Labs minimote

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/ForecastIoProvider.java
The weather binding uses unencrypted http:// for the forecast.io API.
This stopped working two days ago.
Changing the URL from http:// to https:// solves the issue.
See also https://community.openhab.org/t/problem-with-weather-binding-and-forecast-io/3405
=> Use https:// instead of http:// in forecast.io API

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/InsteonDevice.java, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
InsteonPLM binding bug fix: no wait for reply when sending X10 messages. This fixes the 10sec delay when sending X10 commands.
Here is a compiled jar file with the fix. Should be drop-in for OH 1.7 and 1.8:
https://drive.google.com/open?id=0B8OtzwATWQSWN0RTdG1Wb0Q5VUk
=> InsteonPLM binding bug fix: no wait for reply when sending X10 messages

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBridge.java
Added logging output when openHAB tries to authenticate with the hue bridge. Should make it easier to analyse some recently reported issues (e.g. comments in pull request #3259)
=> Add logging output when authentication with hue bridge

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/NetatmoBindingProvider.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoGenericBindingProvider.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoMeasureType.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoPressureUnit.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoScale.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoUnitSystem.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/DeviceListRequest.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/MeasurementRequest.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/NetatmoError.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/RefreshTokenRequest.java
Added support to Netamato binding for *min_*, *max_*, sum_rain for the intervals 30 minutes, 1 hour, 3 hours, 1 day, 1 week and 1 month. The interval is configurable and defaults to 1 day.
The pull request https://github.com/openhab/openhab/pull/2820 that I created didn't have any scaling of converted values, this was giving the false impression of higher precision than is actually available (many digits of precision). The values are treated as intermediate vales scaled according to the Significant Figures and Significant Arithmetic rules which is widely used with scientific data.
Fix for issue https://github.com/openhab/openhab/issues/1820, if the token was expired, the token was refreshed and a recursive call was made to re-execute the binding, this would cause null pointer exceptions …
=> Netatmo: Added additional types, fix for #1820, #3242, and other improvements

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
This pull request fixes a bug that causes outliers in thermostat temperature data due to incorrect parsing of status messages (0x6E).
I have tested the fix with my thermostat and the temperature status messages are now parsed correctly.
=> InsteonPLM: fixed bug with handling of thermostat temperature status messages

bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/actions/Timer.java
The JSR223 TImer management code was not checking the Quartz reschedule return value when returning openHAB status. This change adds the check. 
Quartz will not reschedule a trigger that has expired. Previously, the failed Quartz reschedule would not result in a failed status from openHAB.
Note, there is a similar issue with the Timer management code used by Xtext rules.
=> Added error checking for JSR223 timer reschedule.

bundles/binding/org.openhab.binding.enigma2/src/main/java/org/openhab/binding/enigma2/internal/Enigma2Binding.java, bundles/binding/org.openhab.binding.enigma2/src/main/java/org/openhab/binding/enigma2/internal/Enigma2Command.java, bundles/binding/org.openhab.binding.enigma2/src/main/java/org/openhab/binding/enigma2/internal/Enigma2Node.java
I use my Dreambox in two separate rooms. One room with stereo and one with 5.1 speakers. I've added this setting to the binding to be able to fast switch between the two speaker configurations. Please merge this into the master branch.
=> Binding Enigma2: Downmix switch

bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/engine/scriptmanager/ScriptUpdateWatcher.java
Otherwise, the script watcher thread dies. This causes rules to no no longer be reloaded automatically. Currently, the workaround is to restart the bundle.
=> Added try/catch for rule exceptions in the JSR223 ScriptWatcher.

bundles/core/org.openhab.core.library.test/src/test/java/org/openhab/core/library/items/DimmerItemTest.java, bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/DimmerItem.java
DimmerItem.getStateAs(PercentType) always returned PercentType.ZERO as
returned by its parent class SwitchItem.
=> Fix implementation of DimmerItem#getStateAs

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/ModemDBBuilder.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Driver.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/hub/HubIOStream.java, distribution/openhabhome/configurations/openhab_default.cfg
- improved documentation in openhab.cfg to make it clear which username/pwd to use for hub2
- better error message when providing incorrect password
- longer default timeout for modem database download
This addresses Issue #3327
=> InsteonPLM: improved error messages, longer timeouts for hub2

bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.xslt, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBinding.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/MiosBindingConfig.java
Bugfix for Issue #3317 Tracking last used pin on locks.
MiOS Item Generator (XSLT) incorrectly generated the `sl_UserCode` UPnP attribute as `Number` type instead of `String` type.
Fix involves:
a) Emitting original value as `String` type, which is of the form:
"UserID=".+" UserName=".*"
b) Emitting new Item declaration `*UserCode_userid` representing the _UserID_ value encoded in the original value (`Number`).
c) Emitting new Item declaration `*UserCode_username` representing the _UserName_ value encoded in the original value (`String`).
d) When transforming multiply-bound source values, avoid destroying the original/untransformed value.
e) Tighten the parse logic to work better with Transformations (like `REGEX`) that have complex parameters.
Note: Online docs will be updated once the …
=> MiOS Binding: Issue #3317 Tracking last used pin on locks.

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
I've tested this over the last several days (only one heartbeat/day). The item status is being updated (based on events.log) and the lastheardfrom timestamps are being updated correctly. This feature is useful for the leak sensor because there is no battery life indicator and it sends very few messages unless there is a status change. Thanks to @berndpfrommer for his help.
=> InsteonPlm: Added support for leak sensor heartbeat messages.

bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdBinding.java, bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdGenericBindingProvider.java, bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/PlayerCommandTypeMapping.java
I´ve added a command to the binding, so you can select a song that will be played.
```
Switch Radio_Station_1 {mpd="ON:<MPD_HOST>:playsong=<song_name>"}
```
I use this on my installation to start streaming internet radio. I´ve also changed binding provider to allow a numeric type.
Items:
```
Number Radio_Select {mpd="0:<MPD_HOST>:playsong=1Live, 1:<MPD_HOST>:playsong=WDR2"}
```
Sitemap:
```
Selection item=Radio_Select label="Choose a Radio Station" mappings=[0="1 Live", 1="WDR 2"]
```
I´ve tested this stuff with OH 1.7, 1.7.1 and 1.8 with forked-daapd as mpd server.
This is my first pull request so I really hope I did everything right.
Patrick
=> MPD Binding extension to play a specific song

bundles/binding/org.openhab.binding.alarmdecoder/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBinding.java, distribution/openhabhome/configurations/openhab_default.cfg
This PR allows users of the alarmdecoder binding to configure the port speed, and changes the default speed to 115200.
Related to this:
https://community.openhab.org/t/ad2usb-not-sending-messages-to-openhab/4086
For testing, here is a pre-build jar file that should work for OH 1.8 and 1.7:
https://drive.google.com/file/d/0B8OtzwATWQSWUUZfZEFyZUdoRlU/view?usp=sharing
=> AlarmDecoder binding: port speed now configurable , new default of 115200

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/TCPBinding.java
Use Apache `StringEscapeUtils.unescapeJava` to correctly parse the preamble and postamble config strings.  To address issue #3201.
=> [TCP-Binding] correctly parse postamble and preamble strings

bundles/binding/org.openhab.binding.benqprojector/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorBinding.java, bundles/binding/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/transport/BenqProjectorSerialTransport.java
This adds a serial transport for the benqprojector binding. Verified working with my Benq W1070 projector!
It is largely copied from the network transport but uses NRSerial to communicate directly over a serial port. The NRSerial library is already included in OpenHAB and used by other modules so I figured it was a no-brainer to rely on it over other modules (I actually thought of jssc before realising that something was included).
This is my first contribution to OpenHAB so apologies if I've missed to follow some contribution guidelines or similar.
=> Add serial transport for benqprojector binding

bundles/binding/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorSourceMapping.java
The first valid number is actually 0 so we have to be inclusive when
checking the range of valid numbers. The code would previously consider
1 to be first lowest valid number.
It's possible to set the source either referring to its numeric index or using a string and while using a string has worked, the code to map index into a string was broken as it would consider 1 to be the lowest valid number when it in fact should be 0.
=> benq: Allow minimum source number 0

bundles/core/org.openhab.core.library.test/src/test/java/org/openhab/core/library/types/LocationItemTest.java, bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/LocationItem.java, bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/PointType.java
Addition:
* `distanceFrom(PointType otherPoint)` returns distance in meters from this point to another point.  Useful for geofencing and for other purposes in rules.
Fixes:
* `toString()` method would return nicely formatted string version of `PointType`, but the formatted version was useless from the REST API, and therefore unusable by clients.  Now returns 3 decimal numbers separated by commas without rounding or other formatting.  @clinique, is this OK with you?
* The `String` constructor would take any non-empty string and construct the object regardless of the string contents if it had no commas in the string.  Following the example of the `HSBType` `ComplexType`, the string is now sanity checked in the constructor, and `IllegalArgumentException`s are thrown if the string is not in …
=> Fixes for PointType; added distanceFrom(otherPoint)

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConverterHandler.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveSwitchAllConverter.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveController.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveSwitchAllCommandClass.java
Added support for Switch All Command Class.
To use add a new switch item 
Switch AllOnOff "All On/Off" {zwave="4:command=SWITCH_ALL"}
When user toggles this switch an All On or All Off message will be sent to ALL Z-Wave nodes that support the Switch All Command Class 
The node ID used in the zwave binding MUST be the ID of any one node that supports the SwitchAll command class. 
Then on the sitemap you could do:
Frame {
Group item=gGF label="Ground Floor" icon="groundfloor"
Group item=gFF label="First Floor" icon="firstfloor"
Group item=Outdoor icon="garden" 
Switch item=AllOnOff icon="" mappings=[ON="All On", OFF="All Off"]
}
Added support for the SWITCH_ALL_SET message although it is not needed in OpenHab operation but would be needed to configure nodes.
How could it be added to Habmin …
=> SupportSwitchAllCommandClass

bundles/binding/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/NtpBinding.java
I extracted part of the execute method and called it from the bindingChanged callback. I manually tested it by updating my items file and verifying the NTP-bound item was updated immediately after the items file was reloaded rather than waiting for the next timer callback. Re: #3390
=> Fix for #3390. Refreshes NTP-bound items when binding changes (items reloaded).

bundles/core/org.openhab.core.transform/META-INF/MANIFEST.MF, bundles/core/org.openhab.core.transform/src/main/java/org/openhab/core/transform/actions/Transformation.java
The `transform` action was not being recognized in the Designer.  This PR adds 
`Bundle-ActivationPolicy: lazy` to bundles/core/org.openhab.core.transform/META-INF/MANIFEST.MF, and adds ActionDoc and ParamDoc annotations to the `transform` static method.
Tested on Designer on Mac.  Not tested in runtime or on Windows.
=> Fix for #3432

bundles/binding/org.openhab.binding.serial/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java
I’ve added support for Base64 communication because some bytes from
serial devices are causing problems in the rest api: (see
https://community.openhab.org/t/error-in-rest-service-when-serial-port-s
ends-stx-ack-eot-bytes/3932/2)
I also fixed an error when no regex is used.
(entry.getValue().type.isInstance(SwitchItem.class) was never true)
=> Base64 support and error comparing classes

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java
Modified the TcpBinding regular expressions to better handle binding delimiter
characters in a REGEX transformation. Modified the binding parsing code to
handle the different matching groups. Changed a Command StringItem comparison
from an identity check (==) to "equals". During testing I found that sending
commands through the REST API didn't work because the StringItem instances
where equal but not the same instance. Re: #728
=> Fix for #728. REGEX Expression in TCP binding.

bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBitemSerializer.java
openHAB Issue #3437
In openHAB, `PercentType` is derived from `DecimalType`.  The
MapDB Persistence is pre-parsing the value, assuming it's an `Integer`,
and failing when it wasn't an Integer.
In some cases, this would cause the openHAB startup process to enter a never ending loop, since the Persistence-Restore functionality was failing.
With this change, we simply hand the String value to `PercentType.valueOf()` and let it perform any necessary conversions.
=> MapDB Persistence: PercentType restore needs to allow Decimal values (Issue #3437)

bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/SappUpdatePendingRequestsProvider.java, bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/SappBinding.java, bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/configs/SappBindingConfig.java, bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/configs/SappBindingConfigUtils.java, bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/model/SappAddressDecimal.java
This version adds capability to interpret words and bytes as signed.
Existing unsigned bindings data types are:
* \* (unsigned word, 0 to 65535)
* H (unsigned high byte, 0 to 255)
* L (unsigned low byte, 0 to 255)
New signed correspondent data types bindings are:
* + (signed word, -32768 to 32767)
* H+ (unsigned high byte, -128 to 127)
* L+ (unsigned low byte, -128 to 127)
=> sapp binding: added signed intepretation for words and bytes

distribution/src/deb/bin/setpermissions.sh
This PR is related to https://github.com/openhab/openhab/issues/3451
With this change the openhab user will be the owner of the /etc/openhab/configurations directory and all files below. Thus bindings will be able to change the openhab configuration. It means somewhat lesser security, but better usability.
=> apt installation: openhab user as owner of /etc/openhab/configurations directory

bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/SappBinding.java, bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/model/SappAddressDecimal.java
While scaling values to and from Pnmas hardware, double precision has been substituted by BigDecimal.
New DecimalType are allocated and posted directly with BigDecimal constructor instead of using double constructor.
=> [Sapp Binding] BigDecimal precision in scaling vs double

bundles/io/org.openhab.io.net/src/main/java/org/openhab/io/net/exec/ExecUtil.java
Currently, the ExecUtil silently ignores exceptions caught by the Apache Commons Exec utilities. The `executor.execute` does not throw an exception so the existing implementation doesn't log the error. The exception is returned in the result handler. The change in this PR looks for an exception in the result handler and logs a warning with the exception message. This will apply to both the Exec transformation service and the Exec action and will help users diagnose problems with the external programs.
=> Log execution failures in ExecUtil.

bundles/binding/org.openhab.binding.tinkerforge/model/tinkerforge.xcore, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/config/ConfigurationHandler.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/MBrickletTemperature.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/ModelFactory.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/ModelPackage.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/TFTemperatureConfiguration.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletTemperatureImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/ModelFactoryImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/ModelPackageImpl.java, bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/TFTemperatureConfigurationImpl.java
This change was requested on the TinkerForge forum:
http://www.tinkerunity.org/forum/index.php?topic=3349.new
I'm awaiting feedback from there.
=> Tinkerforge binding: add I2CMode setting to the BrickletTemperature configuration

bundles/persistence/org.openhab.persistence.jdbc/META-INF/MANIFEST.MF
This is in addition to #3248 and #3490 
I don't fully understand why the "optional" resolution of org.sqlite breaks the build, but to avoid breaking the nightly build, I have temporarily disabled it.
@lewie , could you please have a look at the sqlite stuff?
=> Temporarily disable sqlite persistence to fix build

bundles/binding/org.openhab.binding.zwave/database/products.xml
Looks like an copy/paste error was made when adding the sensor, the catalog.xml points to some completely unrelated controller instead.
=> Fix D-Link DCH-Z110 product catalog entry

bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/PointType.java
On trying to use `PointType` in a unit test, I discovered that it doesn't implement equals, so `assertEquals` always fails.
=> PointType needs hashCode and equals to be used in tests

bundles/io/org.openhab.io.multimedia.tts.googletts/about.html
As suggested by @kaikreuzer in #2567
=> Add about page for googleTTS addon including 3rd party license information

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
sendTelegram crashes when extended characters are sent.
Character encoding changed from the default ISO-8859-1 to UTF-8
problem addressed here: https://community.openhab.org/t/new-telegram-action/4459/2
=> [Telegram action] UTF-8 messages bug fix

bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/connection/OneWireConnection.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyBindingConfig.java
Added a new parameter "ignoreReadErrors" to supress read-error log entries, if an iButton
is not present.
=> OneWireBinding - Support for iButtons

bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java
Signed-off-by: hmerk <hans-joerg.merk@t-online.de
fixes #1400
=> Milight Binding - map a saturation value of 0 to WhiteMode, fixes #1400

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMActiveBinding.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/DeviceFeature.java
Improve error logging by logging the known features when an unknown feature is accidentally used. The previous error message was:
item foo references unknown feature: dimmer, item disabled!
It now is:
item foo references unknown feature: dimmer, item disabled! Known features for F00.00.15 are: fastonoff, keypadbuttonA, keypadbuttonB, keypadbuttonC, keypadbuttonD, lastheardfrom, loaddimmer, manualchange.
@berndpfrommer does this look OK?
=> InsteonPLM: Include known features when an item is configured with an unknown feature

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgs221.xml
I happened to stumble across a mismatch of this param's description with Fibaro docs.
I guess it has been unspotted for a long time (maybe a copy 'n paste error from a single device template), or is there any reason to believe that param #7 does not work as documented ?
FGS-221 does have S2 input and O2 output to physical device.
If you agree, I would also change && issue another PR for FGS-222.
=> Update param #7

bundles/action/org.openhab.action.telegram/META-INF/MANIFEST.MF, bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Added method to send pictures to Telegram.
Pictures are downloaded from a URL and sent to Telegram
An optional caption can be added to the picture.
Can be used to send surveillance systems screenshots.
Usage example
```
rule "Send telegram with image"
when
Item Light_GF_Living_Table changed
then
sendTelegramPhoto("bot1", "http://www.openhab.org/assets/images/openhab-logo-top.png", "sent from openHAB")
end
```
The third  parameter (caption) can be null (no caption is sent)
=> [Telegram action] enhancement: added send photo capability

bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonConnector.java, bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonListener.java, bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonUpdateReceivedCallback.java
This fixes #3412:
* Graceful handling of connection timeouts (supports receivers that are not always on)
* Better detect telnet disconnects
=> Denon binding telnet connection fix

distribution/src/deb/etc/init.d/openhab
=> Specify pid file when checking process status

distribution/openhabhome/configurations/openhab_default.cfg
Several people did not remove the comment behind the port configuration line in openhab_default.cfg. Fixed this to avoid users reporting the port does not work.
=> InsteonPLM: removed comments after port configuration in openhab_default.cfg

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, distribution/openhabhome/configurations/openhab_default.cfg
*Summary:* added optional `ecobee:granularity` and `ecobee:quickpoll` config properties; polling the Ecobee API will occur much sooner after the binding has sent an update, command or action call to Ecobee in order to give quicker feedback to the binding.
Changed the polling logic in the Ecobee binding to invoke the `execute()` method based on optional `ecobee:granularity` config property (default 5000ms).  On each of those, check to see if it's time to poll the Ecobee API.  Normal polling continues to use the optional `ecobee:refresh` config property (default 180000ms).  However, after a successful update, command or action call to the Ecobee API, the next poll will occur after `ecobee:quickpoll` milliseconds have passed (optional, defaults to 6000).  So existing configurations are …
=> [ecobee] Added quick poll after update, command or action.

bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/Constants.java, bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/SoulissT54.java, bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/SoulissT55.java, bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/SoulissT56.java, bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/SoulissT58.java, bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/TypicalFactory.java
Simple addition of Souliss types that are missing in the analog input typicals.
=> Add Souliss types 54, 55, 56 and 58 (light, voltage, current, pressure).

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMActiveBinding.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/ModemDBBuilder.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/ModemDBEntry.java
Improved logging of items that match devices in modem database by including groups that the modem controls and responds to with the device. Also log info about devices that are not configured with any items. For example:
2015-12-28 08:55:29.402 [INFO ] [.o.b.i.InsteonPLMActiveBinding] - device 21.F7.C8 found in the modem database and the modem controls groups [0xFE].
2015-12-28 08:55:29.406 [INFO ] [.o.b.i.InsteonPLMActiveBinding] - device 23.A0.51 found in the modem database and the modem controls groups [0xFE] and responds to groups [0x01].
2015-12-28 08:55:29.412 [INFO ] [.o.b.i.InsteonPLMActiveBinding] - device 22.F6.88 found in the modem database and the modem controls groups [0xFE,0x03,0x04,0x05,0x06] and responds to groups [0x01,0x03,0x04,0x05,0x06].
2015-12-28 08:55:29.416 [INFO ] …
=> InsteonPLM: Improved logging of items that match devices in modem database

bundles/binding/org.openhab.binding.zwave/database/greenwave/ns310.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
The Greenwave PowerNode NS310 seems to be a new version of the NS210. The device reports itself as NS210 (version 4), however according to the manual it's called NS310 (also see [this zwaveeurope manual](http://manuals.zwaveeurope.com/make.php?lang=en&type=mini&sku=GWRENS310-F)).
Also it seems that the configuration parameters and association groups between these two versions are quite different.
I have created this zwave device file using the NS-310 manual and tested it with an actual device (well except for some functionality like the over-current protection)
I was not sure about the NS210 devices but I assume they would use a version <=3, as the NS310 is version 4.
=> Add ZWave configuration for Greenwave PowerNode NS-310

distribution/openhabhome/configurations/openhab_default.cfg
Since we actually have a working direct serial binding for BenQ
projectors it's only appropriate we also update the default
configuration to reflect this!
=> Update default config for BenQ binding

bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/EBusBinding.java, bundles/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBinding.java, bundles/binding/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnBinding.java, bundles/core/org.openhab.core/src/main/java/org/openhab/core/binding/AbstractActiveBinding.java, bundles/core/org.openhab.core/src/main/java/org/openhab/core/binding/AbstractBinding.java
Declarative Service components expect the interface to be the parameter to these methods and not a generified subtype of it.
=> Corrected signature for add and remove methods of BindingProviders

bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatpumpConnector.java, distribution/openhabhome/configurations/openhab_default.cfg
Added port config parameter for #3607.
=> [novelanheatpump] Add port config parameter (for #3607)

bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBinding.java, bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightConnector.java
This fixes #3531
* Close existing connections on binding update or deactivation
* More modest logging
=> Better connection handling in pilight binding

bundles/binding/org.openhab.binding.maxcube.test/src/test/java/org/openhab/binding/maxcube/internal/message/ConfigurationTest.java, bundles/binding/org.openhab.binding.maxcube.test/src/test/java/org/openhab/binding/maxcube/internal/message/L_MessageTest.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/BindingType.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/MaxCubeBinding.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/MaxCubeGenericBindingProvider.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/Device.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/HeatingThermostat.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/ShutterContact.java, bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/UnsupportedDevice.java
The Max!Cube reports connection errors for each single device in a L-Message. This flag was not evaluated in the max binding yet, so I have added it. It will map to a Switch-Item if the item is defined with type=connectionError.
I had the situation that one of my devices didn't react to openHAB commands anymore (which I only found out after several days), even though in openHAB everything was displayed correctly. Only when I checked in the MAX! software a connection problem with one of my thermostats were displayed. 
With this PR it will be possible to react on connection errors of any of the MAX devices (e.g. display in UI or send an according e-mail).
If this PR gets merged, I will also update the wiki to add the new type.
=> Add type for maxCube binding to get informed about connection errors

bundles/binding/org.openhab.binding.maxcube.test/src/test/java/org/openhab/binding/maxcube/internal/message/L_MessageTest.java
Fixes build issues introduced with #3640
=> Make maxCube tests compatible with Java 1.6

bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusASCIITransport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusBINTransport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusSerialTransport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransaction.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/SerialConnection.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTcpSlave.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusUdpSlave.java
The following closes the connections when configuration changes (updated method). In addition, all resetConnection methods now properly close the connection.
Previously changes in openhab.cfg left old connections unclosed.
=> Modbus binding to close connections on configuration refresh

bundles/binding/org.openhab.binding.zwave/database/products.xml
Fibaro Roller Shutter 2 with label V2.5 is reported as Type 302 and ID 1000.  Config remains the same.
=> Update products.xml - Fibaro Roller Shutter 2 v2.5

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBulb.java
Implemented workaround code to correctly manage On/Off Switching of
Osram Par16 50 TW bulbs.
I dont know why git thinks that I deleted the complete content of both files. I did the following changes:
* [HueSettings.java](https://github.com/openhab/openhab/blob/b15d832a3195947a20bd7534cfbe8e0dbf2f138a/bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java#L84-L102)
* [HueBulb.java](https://github.com/openhab/openhab/blob/b15d832a3195947a20bd7534cfbe8e0dbf2f138a/bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBulb.java#L49-L52)
* [HueBulb.java](https://github.com/openhab/openhab/blob/b15d832a3195947a20bd7534cfbe8e0dbf2f138a/bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab …
=> Osram-Par16-50-Workaround

bundles/persistence/org.openhab.persistence.cosm/src/main/java/org/openhab/persistence/cosm/internal/CosmService.java
modify Cosm Persistence for compatibility with actual Cosm, named Xively, where items alias ==null
=> modify Cosm Persistence for compatibility with Xively

bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/chart/ChartServlet.java
I just realized the scale factor for the chart servlet is restrictet from 0.5 to 1.0.
Is there a particular reason for that?
I am using a Sasmung Galaxy S6 with a 575 dpi display.
I can use a scale of 0.5, but it would be more readable with a value of ~0.3 - 0.4.
The next generation of smartphones will be having evan higher resolution display (e.g. Sony Z5 Premium)
=> allow lower chart scale values

bundles/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/ipcontrolprotocol/IpControlCommand.java
Not sure why this works. I replicated the zone1 configuration, which seemed to do the trick.
=> [pioneeravr] Fix zone2 power query response not being picked up by openhab

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java
=> Modbus binding: writing open/closed types now work with registers too

bundles/binding/pom.xml, distribution/pom.xml
as discussed [here] (https://github.com/openhab/openhab/pull/3569#issuecomment-167629598) I tried to add the binding into the automatic build process for addons.
=> Include binding fritzboxtr064 into build process

bundles/core/org.openhab.core/src/main/java/org/openhab/core/types/UnDefType.java
=> remove the special toString() in order to sync with ESH

bundles/binding/org.openhab.binding.sallegra/.classpath, bundles/binding/org.openhab.binding.sallegra/.project, bundles/binding/org.openhab.binding.sallegra/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.sallegra/OSGI-INF/binding.xml, bundles/binding/org.openhab.binding.sallegra/OSGI-INF/genericbindingprovider.xml, bundles/binding/org.openhab.binding.sallegra/build.properties, bundles/binding/org.openhab.binding.sallegra/pom.xml, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/SallegraBindingProvider.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/SallegraBinding.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/SallegraBindingConfig.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/SallegraCommand.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/SallegraGenericBindingProvider.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/SallegraNode.java, bundles/binding/org.openhab.binding.sallegra/src/main/java/org/openhab/binding/sallegra/internal/xml/XmlUtils.java, bundles/binding/org.openhab.binding.sallegra/src/main/resources/readme.txt, bundles/binding/pom.xml, distribution/openhabhome/configurations/openhab_default.cfg, distribution/pom.xml
* Sallegra Dimmer DA-ET-4, Sallegra Relay R-ET-4 and Sallegra Input ADI-ET-8/8 are currently supported
* Syncs the Openhab status with the actual status on the Sallegra Module
See [wiki](https://github.com/openhab/openhab/wiki/Sallegra-Binding) here.
Changed from copy of #3520 by formatting changes, resolve merge conflicts, etc.
=> [sallegra] Added Sallegra binding (replaces #3520)

bundles/ui/org.openhab.ui.webapp/snippets/button.html, bundles/ui/org.openhab.ui.webapp/snippets/colorpicker.html, bundles/ui/org.openhab.ui.webapp/snippets/group.html, bundles/ui/org.openhab.ui.webapp/snippets/main.html, bundles/ui/org.openhab.ui.webapp/snippets/rollerblind.html, bundles/ui/org.openhab.ui.webapp/snippets/selection_row.html, bundles/ui/org.openhab.ui.webapp/snippets/setpoint.html, bundles/ui/org.openhab.ui.webapp/snippets/switch.html, bundles/ui/org.openhab.ui.webapp/snippets/text_link.html, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ColorpickerRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/PageRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/SetpointRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/SliderRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/SwitchRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/servlet/BaseServlet.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/servlet/CmdServlet.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/servlet/WebAppServlet.java
This fixes #2742.
* All assets are moved from URL Path `/` to `/classicui`
* Moved all classicui related assets below `/classicui` (BaseServlet.java)
* Moved CMD Servlet to `/classicui/CMD`
* Fixed all Widgets to use relative URLs
* HTML-Variable `%servletname&` is now replaced by full servlet URL.
* Fixed all image URLs to always use `/images/...`
* Fixed refresh handling to use relative URL
Testen on Chrom, IE 11 and Firefox.
Signed-off-by: Sebastian Janzen <sebastian@janzen.it>
=> Fix pollution of / URL space

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
=> Modbus binding: holding/input register state updates now support all the same item types as coil/discrete inputs

bundles/binding/org.openhab.binding.zwave/database/products.xml
Edited Label for Popp IP20 and IP44 Wall Plugs that use same
configuration.
Per Issue #3514
=> Updated Popp Product File

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveNode.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/serialmessage/ApplicationUpdateMessageClass.java
This just saves the NIF into the Node class so that it is saved into the XML file. This is useful for debugging as it helps describe the device.
=> Add node information frame into saved node XML file

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/AbstractRequest.java, distribution/openhabhome/configurations/openhab_default.cfg
[A user reports](https://community.openhab.org/t/how-to-access-the-nest/4310/13?u=watou) and I also see occasional request timeouts trying to query the Nest API.  The default 10-second timeout is occasionally not enough time to successfully query the API.  So this PR adds an optional `nest:timeout` config parameter to openhab.cfg, so the user can override the default 10000ms timeout with a different timeout value.
@teichsta, sorry for the late addition.  If you would prefer that this is deferred, OK!
=> [nest] Added optional nest:timeout config parameter

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
Added rampdimmer support for the KeypadLinc dimmers described in http://cache.insteon.com/developer/2672-222dev-052014-en.pdf. The button check in RampDimmerHandler was causing the state to not get updated for the load button. It is not needed since button commands for the non-load buttons are sent to groups, not to the actual device.
@steve-bate and @berndpfrommer can you please review?
=> InsteonPLM: add support for rampdimmer with KeypadLinc dimmers

bundles/binding/org.openhab.binding.zwave/database/leviton/vre06-1lz.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Electronic Low Voltage, trailing edge dimmer otherwise functionally identical
to VRMX1 Leviton dimmer. Based config off VRMX1, confirmed association group
works to set status updates back to controller.
=> Add Leviton VRE06-1LZ dimmer to DB

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java
openHAB 2 demo package starts with this log message
```
18:55:10.475 [WARN ] [sistence.rrd4j.internal.RRD4jService] - Unknown property name : org.openhab.persistence.rrd4j
```
This PR removes this.
Please also pick for the 1.8 release, thanks!
=> reduce log level

bundles/binding/org.openhab.binding.energenie/src/main/java/org/openhab/binding/energenie/internal/EnergenieBinding.java
As reported in the community, there is a bug in senLogOut() which will be fixed with this PR.
The bug only occurs when using the WebInterface or Smartphone App while openHAB is running.
Cause I only use openHAB for controlling my energenie devices, this never happend in my environment.
Signed-off-by: hmerk <hans-joerg.merk@t-online.de>
=> Fix a bug preventing proper logout from energenie devices

features/openhab-addons/src/main/feature/feature.xml
I think this fixes the build problem I introduced with #3720.  I did a full mvn clean install locally and it gave
```
[INFO] Verification of feature openhab-action-ecobee/1.8.0.SNAPSHOT succeeded
```
=> Corrected Ecobee action dependency

distribution/src/assemble/addons.xml
adds all bundles listed as dependency in distribution/pom.xml to addons assembly.
Fixes #3725 
=> changed include pattern to include all org.openhab.io bundles

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveAlarmCommandClass.java, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveVersionCommandClass.java
Fixes the enumeration of ZWave library types
@teichsta - can this go into 1.8 please (and thanks).
=> Fix bug with ZWave library types

distribution/src/deb/bintray-upload-debs.sh, distribution/src/deb/bintray-upload-fake-packages.sh
@teichsta I had to slightly change the bintray upload script for the 1.8.0RC1 release because the bintray api changed (deb upload script: add gpg passphrase header). You should also use this version of the script for the 1.8.0 release.
I've added a script for managing the fake package upload.
=> bintray helper scripts updates

bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/XbmcConnector.java
As it was impossible to determine the cause of a failed connection, I added the (formerly discarded) exception to the debug call so the user is able to see it.
=> Added cause of ConnectException to the log call

bundles/binding/org.openhab.binding.zwave/database/products.xml
=> Fixed device id and type id for Popp 004001 smoke detector

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcMariadbDAO.java
See: https://github.com/openhab/openhab/issues/3788
MariaDB-driver (tested with mariadb-java-client-1.3.4.jar) now works correct with MySql-Server and MariaDB-Server.
=> MariaDB compatibility update

distribution/openhabhome/configurations/openhab_default.cfg
Add 
```
#weather:location.<locationId1>.name=
#weather:location.<locationId2>.name=
```
to weather binding defaults in openhab_default.cfg.
From [forum request](https://community.openhab.org/t/openhab-1-8-default-cfg-weather-location-locationid1-name-missing/6333).
=> [weather] Add name examples to default weather binding config

bundles/persistence/org.openhab.persistence.influxdb08/.project
There were two projects named 'influxdb', this renames the second one to 'influxdb08'.
=> Rename duplicate influxdb project Eclipse

bundles/binding/org.openhab.binding.zwave/OSGI-INF/activebinding.xml, bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveController.java
This hopefully fixes the issues running the OH1 binding under OH2/Karaf. It adds some startup logging, but the main fix is adding immediate="true" in activebinding.xml (thanks @maggu2810)
=> Z-Wave: Added logging and set immediate="true" for activebinding

bundles/binding/org.openhab.binding.knx/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.knx/OSGI-INF/knxbinding.xml, bundles/binding/org.openhab.binding.knx/OSGI-INF/knxconnection.xml, bundles/binding/org.openhab.binding.knx/OSGI-INF/knxcoretypemapper.xml, bundles/binding/org.openhab.binding.knx/OSGI-INF/knxgenericbindingprovider.xml
fixes https://github.com/openhab/openhab2-addons/issues/631
=> made the KNX binding work by activating all components at bundle startup

bundles/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/ExecBindingProvider.java, bundles/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBinding.java, bundles/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecGenericBindingProvider.java
The existing exec binding contains a hardcoded list of item types that it can update: Number, Contact, Switch, Rollershutter, String (default case).  However openHAB 1.x and ESH have more item types than that, and there is no reason that the output of a commandLine (optionally transformed) should not be suitable for any type of item.  The goal and outcome is similar to #3504.
This PR addresses issue #3823.
This PR removes the binding's knowledge of specific item types, but instead uses the item's acceptedDataTypes list and the TypeParser.  I tested this change with the following items:
```
Group Test (All)
String ExecString "ExecString [%s]" (Test) { exec="<[echo I am a String:60000:REGEX((.*?))]" }
Number ExecNumber "ExecNumber [%.1f]" (Test) { exec="<[echo …
```
=> [exec binding] Allow all item types to be updated

bundles/io/org.openhab.io.net/src/main/java/org/openhab/io/net/exec/ExecUtil.java
Issue #3821. 
Forum [topic](https://community.openhab.org/t/openhab-1-8-and-2-0-beta1-release-is-out/6025/27).
=> ExecUtil: fixed incorrect exitValue configuration.

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
resolves https://github.com/openhab/openhab-distro/issues/101
=> added type exact add/remove methods.

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBinding.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceBindingConfig.java
Under openHAB 2.0, the `update()` method is called before the corresponding `config.cfg/mios.cfg` file is loaded.
We're called again, after these are correctly loaded, so we'll skip over the call if the properties are passed as `null`.
Also removed an unused variable that Eclipse highlighted.
=> MiOS: Work-around issue where update() called before config loaded (openHAB 2.0)

bundles/binding/org.openhab.binding.zwave/database/vision/zd2102.xml, bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft11.xml, bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft13.xml, bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft14.xml
These two commits fix several issues in the Z-Wave database:
1. Vision Security ZD2012 missed configuration command class
2. Vision Security ZD2012 configuration was badly aligned
3. Several Z-Wave.Me products had non-well-formed XML, at the same time removed empty help strings
Furthermore, I found about half a dozen other products not having the configuration command class, but having configuration items in their XML file. Is this an issue? If so, I'd fix them. I found this using a very basic automated check over all XML files, and I could easily add some further verification (and even automatic cleanup) if interested.
=> Several Z-Wave database fixes

bundles/binding/org.openhab.binding.zwave/.project
I would like to propose to change the project name of the OH1 ZWave binding to avoid workspace conflicts with the OH2 binding. 
@kaikreuzer Is there any downside to this? If not, it seems it would avoid problems...
=> Update project name for OH1 ZWave binding

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/mios.cfg, features/openhab-addons/src/main/feature/feature.xml
Expose the MiOS Binding to openHAB 2, add a default configuration file (`mios.cfg`), and extern the `feature.xml` entry.
See:
* https://community.openhab.org/t/mios-binding-1-8-not-working-in-openhab2/6439
=> MiOS: Externalize Binding to openHAB 2.0

bundles/binding/org.openhab.binding.dscalarm/README.md, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/DSCAlarmConnectorType.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/SerialConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/TCPConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java, distribution/openhabhome/configurations/openhab_default.cfg
As per the following discussion with @RSStephens 
https://community.openhab.org/t/dsc-alarm-binding-with-tcp-serial-server/5701
I have added support for the DSC Alarm binding to communicate with an IT-100 through a TCP/IP serial server.
Note that for some reason I'm getting a bad checksum when trying to send "partition disarm" from the web console, but everything else seems to work.
Also note that I have only tested this with my setup (IT-100 behind a Moxa N-Port tcp/serial server).
Let me know if there's anything you'd like changed.  Thanks!
=> DSC Alarm Binding: IT-100 TCP Connection Support

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/LocationConfig.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/YahooProvider.java, features/openhab-addons-external/src/main/resources/conf/weather.cfg
The Yahoo weather provider now requires a `woeid` location config parameter in openhab.cfg, since the [geo.placefinder service was discontinued by Yahoo](https://developer.yahoo.com/forums/#/discussion/7838/tahoo-geo-placefinder-does-not-work%3D%3D%3D%3D) in January, 2016.
@gerrieg, could you comment on this PR?
This PR addresses #3860.
=> [weather] workaround for #3860

bundles/binding/org.openhab.binding.frontiersiliconradio/src/main/java/org/openhab/binding/frontiersiliconradio/internal/FrontierSiliconRadioBinding.java
When the volume changes, updates of decimal typed items did contain the percentage of the volume, not the absolute value. Consequently, the volume was set to an absolute value way too high.
=> Bugfix in frontiersiliconradio: volume update posted from value on bus.

bundles/binding/org.openhab.binding.zwave/database/greenwave/np210.xml, bundles/binding/org.openhab.binding.zwave/database/greenwave/np310.xml, bundles/binding/org.openhab.binding.zwave/database/greenwave/ns210.xml, bundles/binding/org.openhab.binding.zwave/database/greenwave/ns310.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
- Create config for NP310
- Copy [improvements done by dominicdesu](https://github.com/openhab/openhab/pull/3603) to all greenwave products 
I have only a NP310, I need your help to test on NP210 and NS210
Fixes/improvement:
- the color wheel display is now correct on my NP310
- I receive new meter value without polling
Bugs:
- The meter received by notifications are not attached to the right socket
Not tested:
- State after power loss
- over-current related stuff
=> Testers wanted - Better support for GreenWave devices

distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/xbmc.cfg
Closes #3904
[Discussion on forum](https://community.openhab.org/t/xbmc-binding/6747).
Renaming to Kodi is for another day, and so as to not break existing user configurations.
=> [xbmc] Missing cfg file on Install

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/myq.cfg, features/openhab-addons/src/main/feature/feature.xml
Based on [report](https://community.openhab.org/t/chamberlain-myq-binding-in-openhab2/6894/2?u=watou) that the Chamberlain MyQ binding is working under recent OH2 build.
=> [myq] externalize binding to OH2

bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/XbmcConnector.java
Changed logging from info to debug, if playerID == -1 (PVR).
Forum Thread: https://community.openhab.org/t/xbmc-binding-logging-info-if-playerid-is-1-pvr/6879
=> XBMC-Binding - Log.debug if Player is PVR

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/mqtt-eventbus.cfg, features/openhab-addons-external/src/main/resources/conf/mqtt-persistence.cfg, features/openhab-addons-external/src/main/resources/conf/mqtt.cfg, features/openhab-addons/src/main/feature/feature.xml
Addresses #3925
@kaikreuzer, this PR fails on feature verification:
> [WARNING] Feature resolution failed for [openhab-persistence-mqtt/1.9.0.SNAPSHOT]
Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-persistence-mqtt; type=karaf.feature; version=1.9.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-persistence-mqtt)(type=karaf.feature)(version>=1.9.0.SNAPSHOT))" [caused by: Unable to resolve openhab-persistence-mqtt/1.9.0.SNAPSHOT: missing requirement [openhab-persistence-mqtt/1.9.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.persistence.mqtt; type=osgi.bundle; version="[1.9.0.201601301547,1.9.0.201601301547]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.persistence.mqtt/1.9.0.201601301547: missing requirement …
=> [mqtt] Make installable in OH2

bundles/action/org.openhab.action.mios/src/main/java/org/openhab/action/mios/internal/MiosAction.java
The MiOS Action binding uses a Rule API with an Item as the first parameter. This breaks under openHAB 2.x/ESH because they won't resolve to the ESH Item equivalent.
This change moves to declaring the first parameter as Object, and then dynamically calling getName() on this parameter, which resolves correctly in both OH 1.x and ESH.
This PR is to fix issue #3929 
=> MiOS Action - sendMiosAction() API non-functional under openHAB 2 compat

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceBindingConfig.java
Under openHAB 1.x, the `MAP` Transform returns `""` or `null`, when no transformation is performed.
Under the compat1x layer, the `MAP` Transform returns the input/source value.
This change addresses issue #3926, and ensures the MiOS Binding handles either type of result.
=> MiOS Binding - Dimming controls not working in openHAB2 #3926

bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java
From my commit 6f8fd06 on May 9, 2015 I had decreased the latency. Unfortunately, over time it's become clear to me with my lights that this decreased the reliability. The lights do need 100 msec, so I have rolled them back to the 100 msec timing to undo what I did then.
=> Reverted timing back to fix reliability.

bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransaction.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTcpSlave.java
We want to close connection after every transaction since some modbus
tcp servers can accept only single connection at a time. If we
would keep the connection open, the server would be blocked for other
users.
Fixes #3818
=> Modbus TCP connections closed after every transaction

bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/bus/HomematicBinding.java
no longer log messages about missing methods; `bundle:list` shows active
```
169 | Active   |  80 | 1.9.0.201601301304    | openHAB homematic Binding
```
=> [homematic] add add/removeBindingProvider methods

bundles/binding/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirBinding.java
Note for next PR that this binding depends on openhab-transport-serial.
=> [comfoair] add/removeBindingProvider

bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBinding.java
Fixes common issue in 1.x addons needed in 2.0, as reported [here](https://community.openhab.org/t/ihc-binding-in-2-beta/6793).
Please try a [test JAR here](https://dl.dropboxusercontent.com/u/4286376/ihc-addBindingProvider/org.openhab.binding.ihc-1.9.0-SNAPSHOT.jar).
=> [ihc] add/removeBindingProvider

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModel.java
Fixes #3944.  Reported working https://github.com/openhab/openhab/issues/3944#issuecomment-177942784.
=> [nest] Allow setting setpoints with decimals

features/openhab-addons-external/src/main/resources/transform/miosDimmerCommand.map, features/openhab-addons-external/src/main/resources/transform/miosShutterCommand.map, features/openhab-addons-external/src/main/resources/transform/miosSwitchIn.map, features/openhab-addons-external/src/main/resources/transform/miosUPnPRenderingControlVolumeCommand.map
The MiOS Binding ships with a number of `MAP` files to translate the MiOS supplied value into the equivalent openHAB value.
This change tweaks the defaults, based upon this community discussion with @lolodomo :
* https://community.openhab.org/t/fixed-mios-binding-1-8-not-working-in-openhab2/6439/36
=> MiOS Binding - Improve default MAP configuration files

bundles/binding/org.openhab.binding.zwave/database/products.xml
Type and ID were transposed. Now corrected.
=> Fibaro RGBW Controller

bundles/binding/org.openhab.binding.rfxcom/OSGI-INF/connection.xml
This patch is a fix for the RFXCOM 1.x binding fixing compatibility with openHAB2.
=> Fix openHAB2 compatibility for RFXCOM 1.x binding

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnectionProperties.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexProperty.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexSession.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/AbstractSessionItem.java
This adds a property to the Plex binding that holds the cover image for the media that is currently playing.
=> Plex binding: add cover image

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexProperty.java
This adds a play/pause property the to Plex binding to easily use one item for toggling between play and pause, depending on the state of the player.
=> Plex binding: add play/pause property

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoGenericBindingProvider.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/GetStationsDataResponse.java
This is a fix the defects:
https://github.com/openhab/openhab/issues/3891, Netatmo sends back lower case device and module id's.
https://github.com/openhab/openhab/issues/3995, The binding was reporting different wifi and rf values than Netatmo is reporting.
=> Netatmo: Fix for defect #3891 and #3995

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/AuthorizeResponse.java
Ecobee reverted this December API change. Fixes #4006
=> [ecobee] Change seconds back to minutes for PIN expiration

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessage.java
Add output support for this binding to make the doorbell sound.
Example : Number DoorbellSounder "Chime Sent [%.1f]" {rfxcom=">53:CHIME.BYRONSX:ChimeSound"}
Validated in #3058
=> RFXCOM Add output support for Chime sound

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/GetStationsDataResponse.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/NetatmoMeasureType.java, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/NetatmoWeatherBinding.java
Fix defect https://github.com/openhab/openhab/issues/4015, battery percentages are wrong.
Added support for BatteryStatus, which is similar to WifiStatus and RfStatus.
Added parameter BatteryPercentage which provides the same value as Batteryvp, but is more descriptive of what the parameter actually is used for.
=> Netatmo: Fix for defect #4015, added support for BatteryStatus and new BatteryPercentage parameter

bundles/binding/org.openhab.binding.davis/src/main/java/org/openhab/binding/davis/datatypes/DataTypeBarometer.java
Treat incoming barometric pressure unit as one thousandth of an inch of mercury, not a full inch of mercury (inHg), so that the resulting decimal value is a hectopascal (hPa), not a pascal (Pa).
To address [this discussion](https://community.openhab.org/t/davis-vantage-binding/5251).
=> [davis] correct barometric pressure conversion

bundles/action/org.openhab.action.ecobee/src/main/java/org/openhab/action/ecobee/internal/EcobeeAction.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/EcobeeActionProvider.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
Fixes #3963.
Rid action methods of Items, BigDecimal and Integer, in preference to selection string and Numbers.  Changes were required for compatibility with openHAB 2.  Both action and binding bundles must be upgraded together.
Method signatures have changed incompatibly.  The first parameter is no longer an Item but is now the thermostat(s) to which to target the action, such as "254319432" (one or more thermostat IDs separated with commas) or "condo.*" (all registered under condo account) or "/Toronto/BldgA" (a management set), just as it's done in the binding.
I will update the doc and example after merge.
=> [ecobee action] OH2 Compatibility (fixes #3963)

bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ColorpickerRenderer.java
This fixes #3864.
The code was rendering this javascript, which breaks the statement because of the double quotes in the span:
&lt;img src="/images/colorwheel.png" width="29" height="29" border="0" 
onclick="OH.colorpicker.setup('Fireplace', 'Chris' Fireplace &lt;span style="">Err</span>', '#ffffff')" />
This patch changes the double quotes to escaped single quotes.
=> Fixed javascript that was breaking the colorpicker.

bundles/persistence/org.openhab.persistence.jdbc/ESH-INF/config/config.xml, bundles/persistence/org.openhab.persistence.jdbc/OSGI-INF/jdbc.xml, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/persistence/org.openhab.persistence.jdbc/pom.xml, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/jdbc.cfg, features/openhab-addons/src/main/feature/feature.xml, pom.xml
Based on this [hints ](https://community.openhab.org/t/jdbc-persistence-heave-from-oh1-to-oh2-esh-choosing-a-namespace/7487/5)added JDBC to OH2 features and PaperUI service configuration.
The JDBC Persistence can be fully installed and configured by the PaperUI now.
=> Add jdbc Persistence to Paperui and features

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java
Modification of lighting4 code :
- Fix the ID and command field mappings : S1-S24 field is divided into S1-S20 for ID and S21-S24 for command
- Add new command IDs : 
OFF : 0,2,4
ON : 1,3,5,7,12
Validated in #3858
=> RFXCOM Add lighting4 fix and new commands

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComConnection.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComConnectorInterface.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComTcpConnector.java
This PR clear receiving buffer after sending reset command.
This solves problem when openhab was restated and messages are received from rfxcom during startup and the protocol becomes unsynchronized .
As the RFXCOM protocol does not have any king of start byte, any byte that is != 0 is considered as start.
Now everytime it starts in correct state.
=> RFXCOM clear buffer after reset command

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComEnergyMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRainMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUVMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComWindMessage.java
Fix message data lengths for the following sensor types : Current, Energy, Rain, UV, Wind.
Not really serious as it is mainly used as info for this kind of sensor, but it will be clearer.
=> RFXCOM Fix message data lengths

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentEnergyMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDateTimeMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting3Message.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComPowerMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureHumidityBarometricMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureRainMessage.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat2Message.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat3Message.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComWeightMessage.java
Add binding support for the following sensor types :
- CurrentEnergy (tested in #3854)
- DateTime (*)
- Fan (*)
- Lighting3 (*)
- Power (*)
- TemperatureHumidityBarometric (tested in #2557)
- TemperatureRain (tested in #3863)
- Thermostat2 (*)
- Thermostat3 (*)
- Weight (*)
(*) Untested sensor. Can be buggy ! But at least it gives a first draft for future fix.
=> RFXCOM Add binding support for 10 sensor types

distribution/openhabhome/configurations/openhab_default.cfg
Added a section to the default openHAB 1.x configuration file, matching the description in the MiOS Binding Wiki page.
This is an openHAB 1.8.x Cherry-Pick candidate (for ease-of-use)
Ref: https://community.openhab.org/t/mios-where-in-openhab-cfg/7695
=> MiOS Binding - Add default configuration entry for openHAB 1.x

bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBinding.java
Comm failures may return empty map of devices.  Skip variable poll in those cases to avoid NPE.
=> [garadget] avoid NPE if comm failure

bundles/binding/org.openhab.binding.zwave/database/products.xml
Devolo resells a number of Z-Wave devices. In this case a Danfoss theromstat and a Vision smoke detector.
The Danfoss theromstat has kept it manufacture id but has a no device reference.
The Vison smoke detector has been given the Devolo manufacture id.
In both cases the products.xml has a new entry for the device which simply reference the OEM ConfigFile.
=> Zwave product database entries for two Devolo devices

bundles/ui/org.openhab.ui.webapp/snippets/main.html, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ChartRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ImageRenderer.java
Users in issue #1584 recommend these changes to fix #1584.  I would like to see image and chart refresh in the 1.8 Classic UI as well, but not before verifying that this fix has no regressions.  Please comment here if you are willing to test this change and report results.  It's possible this won't be the fix.
=> Fix UI image and chart refresh per #1584

bundles/binding/org.openhab.binding.zwave/database/nodon/crw310x.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
see openhab/openhab/#4070
I added it as a seperate product, as in fact it is a different prodcut. 
The exising crc-3100 is a remote controll "Octan Remote" ( http://nodon.fr/en/z-wave/octan-remote_7-2 ) wheras the CRW-310x is a Wall Switch (http://nodon.fr/en/z-wave/z-wave-wall-switch-by-nodon_12-2). However, the parameters and association groups are equal, so the only difference appart the product id are the labels.
=> add support for the nodon crw 310x wall switch. 

bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/parser/EBusTelegramParser.java
If the value is out of min/max range the returned value can be null. This is okay, but need to be catched.
=> eBUS - Fix NullPointException if telegram value is invalid/out of range

bundles/ui/org.openhab.ui.webapp/snippets/chart.html, bundles/ui/org.openhab.ui.webapp/snippets/image.html, bundles/ui/org.openhab.ui.webapp/snippets/image_link.html, bundles/ui/org.openhab.ui.webapp/snippets/main.html, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ChartRenderer.java, bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/ImageRenderer.java
Support the `refresh=` parameter to Image and Chart widgets in all cases in the classic web UI.  Testing feedback should go in [this topic](https://community.openhab.org/t/please-help-test-fix-for-image-and-chart-refresh-in-classic-web-ui/8106).
Same change as in https://github.com/eclipse/smarthome/pull/1106.
=> ClassicUI: full image and chart refresh

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
I stumpled across a wrong usage of the operator "&" vs. "&&" in the fritzboxtr064 binding.
@gitbock can you confirm this fix?
=> fritzboxtr064 binding: fix wrong operators

pom.xml
Because of missing version of plugin org.vafer:jdeb maven generates many warnings on each build start.
=> Maven warnings on build start

distribution/src/deb/bin/setpermissions.sh
The mode of files and directories in $OPENHAB_HOME_DIR ( /var/lib/openhab) are not changed anymore, only the ownership is changed.
Fix for #3776 and #3601 .
=> don't change file mode of files in OPENHAB_HOME_DIR

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Helper.java
Use org.w3c.dom.ls.LSSerializer instead of org.apache.xml.serialize.XMLSerializer, which is deprecated.
Since this binding did not compile for me on the command line, I replaced some deprecated symbols.
=> fritzboxtr064 binding: fix compilation error

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusGenericBindingProvider.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java
Ensures that coil commands are written to the modbus slave no matter what the current state is.
Furthermore, now handling nicely if no poll is done but we receive a command.
=> Modbus binding: coil commands executed no matter current state

bundles/binding/org.openhab.binding.zwave/database/everspring/an181.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Please add support for the Everspring AN181 Mini-plug with meter function (Gen5). 
My pull request is slightly different from the database at www.cd-jackson.com:
- My xml-file is named an181.xml since "AN181" is the device name, not "AN1812" (AN181-2 means it is the german type plug, AN181-6 the French and so on)
- My file has maximum 4 allowed associations for group 2 (tested and also according to the manual)
=> Z-wave: New device Everspring AN181 Mini-plug with meter

bundles/binding/org.openhab.binding.onewire/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.onewire/build.properties
With these additions, the openHAB 1 binding appears as a binding in the Paper UI and can be configured through the UI:
fixes https://github.com/openhab/openhab/issues/4247
=> added configuration meta-data for onewire binding

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/gfx/WeatherTokenResolver.java
The weather binding can spam openhab.log with stack traces at ERROR level, when it would be sufficient to instead log the exception message at WARN level.
=> [weather] Quiesce repeatedly logged stacktraces

features/openhab-addons-verify/pom.xml, features/openhab-addons/src/main/feature/feature.xml
The MiOS Binding internally uses the MAP and REGEX transformation
services.  This change ensures that OH2 will install those deps
when the MiOS Binding is deployed.
Also tweaks #4308 to add the other component for complete feature
verification.  See discussion in openhab/openhab-distro#163
=> [mios] Install MAP and REGEX transformation dependencies for OH2

features/openhab-addons/src/main/feature/feature.xml
=> renamed feature from tts to voice to sync it with latest OH2 definition

bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.sh
The [MiOS Item Generator](https://github.com/openhab/openhab/wiki/MiOS-Binding#item-generation--mios-item-generator) builds an openHAB Items file using the metadata from a MiOS/Vera Unit.
In some cases, users were confused by the output of the tool and this lead to issues in the subsequent configuration steps.
This PR adds further logging/output to guide the user in the configuration.
=> [mios] Improve logging output of MiOS Item Generator output.

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProviderTest.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java
Don't do type guessing until it's needed. This allows binding multiple
datapoints for the DateTimeItem, resolving #3282.
=> Allow multiple KNX datapoints without type guessing.

distribution/src/deb/control-runtime/postinst
Related to issue #4246
Set `ENV OH_DOCKER_INSTALLATION true` for docker installations.
For example:
```
COPY files/openhab-runtime-1.8.2.deb /
ENV OH_DOCKER_INSTALLATION true
RUN dpkg -i /openhab-runtime-1.8.2.deb
```
=> deb packaging: docker support

bundles/binding/org.openhab.binding.fritzboxtr064/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
if network failure occurrs remediate from error properly. Close connections.
- Release connection after communicating SOAP to FritzBox
- Decrease "no TR064 service found" to warning
- Set Timeouts for SOAP response to 4 seconds
=> FritzBoxTR064 Binding: Update for network stability

bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/Iec6205621MeterGenericBindingProvider.java
IEC-62056-21 Binding: Support for ISKRA MT174 OBIS Codes 
OBIS code of the format A-B:C.D.E*F conflict with item configuration in which conflicts with separation string in item configuration
=> Fix issue reported in #4239

bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBinding.java
Fixes #4255 regarding problems with status updates when multiple devices are configured and fixes #4240 regarding advanced command status updates. There was no check to match the device ID against the device ID in the binding specification, so status updates from devices were being posted to items bound to different devices. A full comparison (instead of the first three characters) was also added for advanced command keys as three characters is not enough to distinguish advanced commands. This caused status updates to be written to the wrong item.
Signed-off-by: Pete Vavaroutsos<pete@vavaroutsos.com> (github: vavaroutsos)
=> Onkyo Binding multiple devices status update fix

bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java
The MyQ binding can bind to String items. This change allows it to accept String commands as well.
Signed-off-by: Andy Lintner <dev@beowulfe.com> (github: beowulfe)
=> Allow String commands in MyQ binding

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/DSCAlarmInterfaceType.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/SerialConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/TCPConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Panel.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
This fixes a bug where the binding could freeze or not initialize if the configuration parameter 'deviceType' was populated in the openhab.cfg file.  This fix has been tested by another user as mentioned in the OpenHAB Community Forum [here](https://community.openhab.org/t/dsc-binding-not-connecting-to-it-100/8510/10).  This PR is in reference to issue [#4158](https://github.com/openhab/openhab/issues/4158).
=> [DSC Alarm] Bug Fix - Could not handle 'deviceType' configuration parameter

bundles/binding/org.openhab.binding.fht/src/main/java/org/openhab/binding/fht/internal/FHTBinding.java
This patch allows openhab to control FHT8v valves directly without the need of a FHT80b controller. See also http://www.fhemwiki.de/wiki/FHT_8v_direkt_ansprechen (German page that describes doing so for/with the help of the FHEM project).
=> FHT: Implement support for valve FHT8v

bundles/binding/org.openhab.binding.zwave/database/products.xml
Z-Wave:
- Added new reference ID for Fortrezz MIMOlite (US 908 MHz) 
I purchased a new Fortrezz MIMOlite however after device inclusion, it's reported device reference ID was not listed in the Z-Wave device database.
=> Z-Wave: new reference ID for Fortrezz MIMOlite (US 908 MHz)

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/LocationConfig.java
Also added an early short circuit in the validation logic.
See [discussion](https://community.openhab.org/t/weather-binding-updateinterval-should-be-optional/10859/2).
=> [Weather] Add a default of 240 minutes for the updateInterval.

bundles/binding/org.openhab.binding.gpio/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.gpio/build.properties, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/gpio.cfg, features/openhab-addons/src/main/feature/feature.xml
Followed instructions here:
https://github.com/openhab/openhab-distro/blob/master/docs/sources/features/compatibilitylayer.md#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution
Included meta-information for Paper UI configuration.
Closes #4404
=> #4404 Added GPIO Binding and IO to 1.x compatibility bundle for OH2

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/DSCAlarmBindingConfig.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmGenericBindingProvider.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmItemUpdate.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/DSCAlarmConnectorType.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/SerialConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/connector/TCPConnector.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/DSCAlarmDevice.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Panel.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/model/Zone.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/APIMessage.java
The binding would prematurely set the item `PARTITION_ARM_MODE` when issuing a partition arm command.  This would sometimes show the partition as being armed when it actually wasn't.  This fixes that situation by only setting the item when a verification message is received from the alarm system.  This issue was brought to light on the openHAB community website [here](https://community.openhab.org/t/dsc-partition-arm-mode/11012).
=> DSC Alarm: Fix Premature Setting of Partition Arm Mode Item

bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBinding.java
Added m_writer initialization when used on Serial Port
This has been tested with an AD2USB device and now works like a charm, thanks to Bernd for his work on this plugin and to the rest of the OpenHAB community.
=> Fixed AD2USB Commands Send

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosBinding.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnit.java, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnitConnector.java
Under the compat1x layer of OH 2, the MiOS binding was seeing a different startup sequence than when run natively under OH 1.x.
This change adds a delay to the startup processing to allow Item loading to stabilize before attempting to load data from the MiOS Unit, to avoid the sequencing issues.
Community discussion:
* https://community.openhab.org/t/openhab2-new-issue-with-the-startup-process-mios-binding/8320
=> [mios] openHAB2 delayed startup/reload improvements under compat layer.

bundles/binding/org.openhab.binding.modbus.test/.classpath, bundles/binding/org.openhab.binding.modbus.test/META-INF/MANIFEST.MF
A test uses a JDK 1.7 AssertionError constructor, but project was set to require only Java6.  Clears error in Eclipse IDE.
=> [modbus test] Fix JDK version

bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/Messages.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/messages.properties, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/messages_de.properties, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java
The heatpump binding throws a "found new value for reverse engineering" for state 19 at my openhab system. My heatpump shows "Warmw. Nachheizung" at this time. So I added this information to the novelan binding.
=> add description to state 19 in novelan heatpump binding

bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiGenericBindingProvider.java, bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiMeasureType.java, bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogMessage.java, bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogValue.java
The TA CMI protocol supports 21 different analog value types according to the documentation. I found out that the documentation is not completely accurate, but by analyzing the network traffic I was able to figure out how to support at least kilowatt, kilowatthours and megawatthours. The code also adds generic dummy values for all other value types so that it is easy to add them as soon as somebody discovers them with their device.
Coments welcome; binding jar attached for testing
[org.openhab.binding.tacmi-1.9.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab/files/299288/org.openhab.binding.tacmi-1.9.0-SNAPSHOT.jar.zip)
=> [TA-CMI Binding]: Added support for more data types, rudimentary support for the whole protocol

bundles/binding/org.openhab.binding.networkhealth/src/main/java/org/openhab/binding/networkhealth/internal/NetworkHealthBinding.java
Previuosly the log message always stated, that a host is reachable, independent of the return code of the checkVitality function.
This could lead to confusion in trying to debug on error.
Also reformated a log message to fit into the general design of the package.
=> Network Health - Made log message more clear

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherBinding.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java
In order to prevent silent failures of the weather binding (see #4337), record appropriate log messages.
Also prevent duplicate warnings on binding change.
=> [WeatherBinding] Add log messages for invalid configurations

bundles/binding/org.openhab.binding.maxcul/src/main/java/org/openhab/binding/maxcul/internal/MaxCulMsgHandler.java
Add the raw message content to retry failure messages, allowing a level of diagnosis as to which valve is the one that is failing.
=> Extend error logging on retry failure

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/ModbusBindingProvider.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
This pull request Fixes #3558 by adding new value types that have the words swapped, such as uint32_swap, float32_swap, etc
(see https://github.com/openhab/openhab/issues/3558)
If this change is accepted the wiki will need to be updated to document these changes
=> MODBUS: Add support for int32_swap, uint32_swap and float32_swap data types

bundles/binding/org.openhab.binding.zwave/database/homeseer/hswd100.xml
Z-Wave: updated Homeseer HS-WD100+ device to support new config parameters for firmware version 5.14.
=> Z-Wave: update Homeseer HS-WD100+ for FW v5.14

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java, distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/src/main/resources/conf/http.cfg
For user-specified URLs that happen to contain sprintf-style formatting strings, the binding would attempt to substitute the current time and/or item state.  But this may not be what the user wants, instead preferring to use the URL as given.  A conflict can easily happen when the URL contains escaped characters, like "http://sample/?This%20string%20is$5%20a%problem," and so the user would want to suppress the sprintf-style formatting.
This PR adds an optional configuration property called `format` that is `true` by default, for backward compatibility.
See #4459 and [the forum](https://community.openhab.org/t/help-with-transforming-google-maps-distance-matrix-api-data/11390).
=> [http] allow String.format to be optional to avoid conflicts

bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiGenericBindingProvider.java
As discussed in #4515, this change fixes the NPE.
=> Fix #4515 (NPE for digital items in TA-CMI binding)

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/IOStream.java, bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/TcpIOStream.java
renamed OldHubIOStream to TcpIOStream to reflect its usability with programs such as ser2net.
refactored factory method in IOStream to allow tcp as a prefix within
config
=> refactor to reflect ability to connect to plm via tcp

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java, bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java
The Undecoded implementation only has one value selector, RawData. This updates the item state with the full message.
I'd like to introduce a "Data" value selector, which drops the header from the message. The bytes of the header are:
1. Length - not required as we get a byte array of the right length anyway.
2. Type (Undecoded) - Not required as we know the item is undecoded from the items file.
3. Subtype - This could potentially be of use to someone, but it wasn't in my case, and RawData is still an option.
4. Sequence number, this changes consistently, unlikely to be required.
I have devices that just spit out their ID as a message and nothing else, by using the Data selector instead of the RawData selector, I get a consistent output (without sequence), which means my rules file can …
=> Add a Data value selector that doesn't include RFXCOM headers

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ErroringQueriesTestCase.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
=> Modbus binding: do not read out-of-bounds discrete inputs/coils

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/WriteCoilsAndDiscreteTestCase.java, bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/WriteRegistersTestCase.java
Some of the failing modbus binding tests were skipped for performance reasons. Now that #3685 is fixed, those tests can be enabled once again. This PR implements just this.
=> Modbus: enable tests that used to fail

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
Minor fix for PR #4575 which was already merged in.
The index-out-of-bound should be of course checked before accessing `coils.getBit`.
=> [modbus] PR 4575 small fix

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ErroringQueriesTestCase.java, bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/TestCaseSupport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusConnectionException.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusGenericBindingProvider.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusUnexpectedTransactionIdException.java
Resolves #4552. 
This implementation emits Undefined state even with all read errors:
- connection establishment fails
- protocol errors (that is, modbus slave response is error response)
- IO errors
- transaction id mismatch (request's transaction id does not match response's transaction id)
Additionally, this PR will also implement transaction id check for writes, and in case of such mismatch, error is logged with WARN. Previously this case was not checked and not logged.
Pre-compiled jar available [here](https://github.com/ssalonen/openhab/releases/tag/modbus-error-detection-pr-2016-08-08)
=> [Modbus] Read errors now emit UNDEF (configurable)

bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10Binding.java
Wait 20 seconds before attempting to reconnect as otherwise the log gets full with thousands of reconnect attempt messages when mochad server is down.
=> [MochadX10] Introduce delay before trying to reconnect

bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdBinding.java, bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdGenericBindingProvider.java, bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/PlayerCommandTypeMapping.java
MPD enhancement. Added support for playing song with specified songID. It can be used as Selection to play specified stream
Item definition:
Number		Radio_GF_Salon_playitem		"Radio"		<none> 	(All) { mpd="NUMBER:p1:playsongid" }
Sitemap:
Selection item=Radio_GF_Salon_playitem mappings=[1="ZET Chilli",2="Radio Kolor",3="Radio 7",4="Złote Przeboje",5="EskaROCK",6="RMF Classic",7="RMF Maxxx",11="ESKA",9="RMF",10="MUZO.FM",8="PR 3",12="TOK FM" ]
=> Play songID from current playlist added

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java
Updated commands 040 and 070 to better accommodate the IT100 interface.
1. Fixed logical bug in command 040 so the binding would a append zeros
to the user code of the IT100 instead of the Envisalink.
2. Added ability in command 070 to send all allowable characters for the
IT100.
3. Implemented a long key press option in command 070 for the IT100.
Signed-off by: Russell Stephens rsstephens@gmail.com (github: @RSStephens)
=> DSC Alarm Command Updates for the IT100

bundles/action/org.openhab.action.satel/src/main/java/org/openhab/action/satel/internal/Satel.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelCommModule.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBinding.java
This PR adds ability to override user code configured in settings and required for some operations (controlling objects, etc).
There is one new action `satelSetUserCode(String newUserCode)` that changes current user code in the binding.
=> [satel] Added rule action to set user code

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ErroringQueriesTestCase.java, bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/TestCaseSupport.java, bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/pooling/EndpointPoolConfiguration.java, bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java, distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/src/main/resources/conf/modbus.cfg
Resolves #4595
The default connection timeout is zero which is basically matches the previous behavior (OS default or infinite).
Pre-compiled JAR available at https://github.com/ssalonen/openhab/releases/tag/modbus-timeout-pr-2016-09-07
TODO (once merged): wiki page update
=> [modbus] Connection timeout parameter for TCP slaves.

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
When using a lot of Plugwise devices, occasionally a `NullPointerException` may occur. The root cause is that multiple threads simultaneously sort and search the `plugwiseDeviceCache`. This causes the binary search to be searching in the wrong part of the cache. I've made things a bit simpler by removing the sorting. It did not affect performance for me with tens of configured devices.
=> [Plugwise] NullPointerException may occur when concurrent threads get PlugwiseDevice from Stick

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Fixes #4647
Please try [this test JAR](https://dl.dropboxusercontent.com/u/4286376/telegram-caption-utf-8/org.openhab.action.telegram-1.9.0-SNAPSHOT.jar) and report if it works to send Unicode characters in photo captions.
=> [telegram] sendTelegramPhoto caption should be UTF-8

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/command/ControlObjectCommand.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/ZoneControl.java
This PR adds a delay between sending command and refreshing current state, which allows correctly update state of bound items.
There is also minor improvement for refreshing zone states.
=> [satel] Fixed refresh after control command

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Circle.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/CirclePlus.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
Switching power states of Circles can sometimes takes several seconds or more. This is caused by the `sendQueue` being filled with messages of the Quartz jobs that poll Circles for their state.
Also a user may notice that just after switching a power state, the switch goes back to its previous position, only until a second later it goes back to its new position. This is caused by the old power state that was just polled by a Quartz job. This may also result in a Circle not being switched at all.
In this PR a `prioritySendQueue` is introduced for switching power states. Also when there is a pending power state change, a just received (and soon obsolete) power state is ignored. Switching should now be fast and reliable, regardless of the workload resulting from the Quartz jobs. 
Also fixed …
=> [Plugwise] Improve power state switching, fix ObjectAlreadyExistsException when (re)starting binding

bundles/binding/org.openhab.binding.mios/examples/scripts/miosTransform.xslt, bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceDefaults.properties, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/transform/miosTStatSetpointCommand.map, features/openhab-addons/src/main/feature/feature.xml
UI7 of MiOS changes the way Thermostats are implemented. This change
added minimalist support for UI7 Thermostats, based upon feedback
received from the community:
* https://community.openhab.org/t/mios-binding-thermostat/14967
=> [mios] Add support for UI7 style thermostats.

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/AbstractDevice.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Structure.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Thermostat.java
Updates to the Nest binding to match [the October 2016 API Update](https://developers.nest.com/documentation/cloud/release-notes).
Please test [this JAR](https://dl.dropboxusercontent.com/u/4286376/nest-oct-2016-api-update/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar) to verify that the new features work.  You will have to update your Product at developer.nest.com to use the v6 permissions, and set up a new PIN for your account and update your nest.cfg or openhab.cfg file.  Also, the thermostat against which you are testing must be at the 5.6 or later firmware version.
Please report back here or [on the forum](https://community.openhab.org/) with your results, and thanks!
=> [nest] October 2016 API Update

bundles/binding/org.openhab.binding.dsmr/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.dsmr/build.properties, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/dsmr.cfg, features/openhab-addons/src/main/feature/feature.xml
The DSMR Binding works just fine with OH2 so here is the OH2 feature addon. This should make using OH2 a bit more easy for the more than 1 million households in The Netherlands that already have a smart meter installed.
=> [DSMR] Add openHAB 2 feature addon

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/nma.cfg, features/openhab-addons/src/main/feature/feature.xml
Actions known to work via manual install [here](https://community.openhab.org/t/notify-my-droid-in-oh-2/15012).
=> [nma] Add NotifyMyAndroid actions to OH2

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/TCPBinding.java, bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/UDPBinding.java
The TCP binding currently does not allow straight string literals to be passed as message, it can only done through MAP files or other non direct means. The MQTT binding gives more options: "default", transformation or straight strings.  This PR takes from the MQTT Binding and applies the same rules while maintaining as much as possible the current code. The private method splitTransformationConfig is removed and its functionality incorporated directly into the transformResponse method.
=> TCP/UDP Binding enhancement 'MQTT style'

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/jointspace.cfg, features/openhab-addons/src/main/feature/feature.xml
Hi 
After confirming that the current jointSPACE binding with the current snapshot of OH2 is still compatible (see #1005), I created the necessary entries and file to make it usefull as a Karaf feature for OH2
[information from here](http://docs.openhab.org/developers/development/compatibilitylayer.html)
As I do not have experience with Karaf, I hope I did not forget something.
=> [jointSPACE] Add the 1.9 binding to the OH2 distro

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/HttpBindingProvider.java, bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java, bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpGenericBindingProvider.java
Prior to this PR, the HTTP binding would only update items of the following types:
* Number
* Contact
* Switch
* Rollershutter
* DateTime
* String
With this PR, the HTTP binding will update items of any type (Dimmer, Location, etc.), providing the incoming or optionally transformed string can be converted into one of the item's accepted data types.
A test JAR is [here](https://dl.dropboxusercontent.com/u/4286376/http-states/org.openhab.binding.http-1.9.0-SNAPSHOT.jar).
Fixes #4759
=> [http] Allow all item types to receive updates

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
Improves the binding reliability by:
* making sure CR is followed by LF when reading incoming packets, which
should result in less protocol message errors
* polling max 1 second for `AcknowledgeMessage`s so the `SendThread` does
not wait indefinitely when ACKs get lost
The most common scenario for the binding to stop working should now be solved. I.e. a received `AcknowledgeMessage` results in a protocol message error (e.g. because it is preceded by the LF of a previous message). Especially on Windows this seems to be an issue due to non-blocking reads.
=> [Plugwise] Reliability improvements

bundles/binding/org.openhab.binding.dsmr/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.ecobee/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.garadget/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.gpio/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.gpio/OSGI-INF/gpiobinding.xml, bundles/binding/org.openhab.binding.onewire/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.plugwise/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.powermax/ESH-INF/binding/binding.xml
Following the example in #4804, add `<service-id>org.openhab.ID</service-id>` to all 1.x bindings that already provide an `ESH-INF/binding/binding.xml` file for configuration through the Paper UI.  This should result in the binding services finding the configuration at the service PIDs where they are expected to be.  
The GPIO binding was a special case because it did not explicitly set its `service.pid`, which I understand means that the component's name is used instead.  So I explicitly set the `service.pid` for the service component to match how other bindings name their service PIDs.
=> Add service ids to ESH-INF/binding/binding.xml files

bundles/binding/org.openhab.binding.ecotouch/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.ecotouch/build.properties, bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/EcoTouchTags.java, bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchBinding.java, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/ecotouch.cfg, features/openhab-addons/src/main/feature/feature.xml
This pull request adds some more recognized tags to the binding and provides the metadata for OH2.
I can squash the commits into one, if requested.
Open problems:
OH2 shows the binding under PaperUI/Configuration/Bindings, but changes to the configuration are ignored (AbstractActiveBinding<>.updated(Dictionary<String, ?> config) is called with config == null, if no ecotouch.cfg file is in place).
Only configuration via the provided ecotouch.cfg file works.
=> Waterkotte Ecotouch heatpump binding for OH2

bundles/binding/org.openhab.binding.upb/ESH-INF/binding/binding.xml, distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/upb.cfg, features/openhab-addons/src/main/feature/feature.xml
@cvanorman This look OK to you?
=> Add UPB binding to OH2, Fixes #4811

bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBPersistenceService.java
Because `ColorItem` extends `DimmerItem` the current `MapDBPersistenceService` implementation tries to store the item state as a percentage.
`item.getStateAs(PercentType.class)` then causes the following exception:
```
java.lang.IllegalArgumentException: Value must be between 0 and 100
```
Changing the if-then-else order results in the correct behavior.
=> Fix IllegalArgumentException with ColorItem MapDB persistence

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java, bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBulb.java
I accidently used 3:brightness and this does not lead to the logging of any error, even while running in debug mode, after I traced down the problem I now changed the behavior the message "Not a valid id on the bridge: {bridge}" is logged and no further attempts to execute commands or update the status from the bridge are made.
The reason the old code did not work was that a null object was always wrapped in some internal object (see the code in HueSetting), further in the execution a null pointer was triggered, because the internal state of bulb was inconsistent because nothing could be retrieved from the bridge. That NPE was (unfortunately) swallowed by openHAB's core classes.
The reason an exception is now thrown from the HueBuld is that otherwise a HueBulb object will be constructed …
=> Improved the handling of incorrect device id's

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
fixes #4229: DecimalType and DPT 5.001 are incompatible, expected is PercentType. Misuse was not logged but failed silently.
=> [KNX] Add log entry if DPT incompatible

bundles/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickBinding.java, bundles/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickController.java, bundles/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickSendEvent.java
This will improve send performance for sliding dimmer devices with over 50% in certain cases.
If issue #1683 still exist I guess its fixed by this patch.
An internal send que between tellstick binding and controller have been implemented.
The que removes outdated send events which not have been broadcasted by the tellstick device yet.
Signed-off-by: Elias Gabrielsson elias@rehash.se (github: EliasGabrielsson)
=> Updated Tellstick performance Closes #4089

bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBPersistenceService.java
initialization.
The main change is modifying mkdir() to mkdirs() to cover the case where
more than one directory in the path does not exist. Also added some
additional debugging/log messages.
Fixes #4662.
Fixes #4844.
=> Fix problems with creating the MapDB database directories during

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/CirclePlus.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseDeviceCache.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
This PR fixes some exceptions that are occasionally thrown when the binding is started. Some examples of these stacktraces are:
```
17:25:58.113 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=294, bundle=200/mvn:org.openhab.binding/org.openhab.binding.plugwise/1.9.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.plugwise
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)[:1.8.0_65]
at java.util.ArrayList$Itr.next(ArrayList.java:851)[:1.8.0_65]
at org.openhab.binding.plugwise.internal.Stick.getDeviceByMAC(Stick.java:148)[200:org.openhab.binding.plugwise:1.9.0.201611250210]
at …
```
=> [Plugwise] Fix exceptions at binding startup, improve device cache

bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java, bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBindingProviderImpl.java, bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavConfig.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavQuery.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
rebased on 2016/12/03 and squashed my commits into 1.
added a "filter-category-any" configuration that will allow a item
configuration to have filters that match any of an event filter. Allows
an event to command a GROUP, and have an "awareness" on all individual
items of the group that an event concerning them will happen
example : 
String cuisine_NextEventName1 "cuisine proch. evt. 1 [%s]" <calendar> {
caldavPersonal="calendar:chauffagecmd type:UPCOMING eventNr:1 value:NAME
filter-category-any:'cuisine,salon,rezdechaussee'"}
String cuisine_NextEventName2 "cuisine proch. evt. 2 [%s]" <calendar> {
caldavPersonal="calendar:chauffagecmd type:UPCOMING eventNr:2 value:NAME
filter-category-any:'cuisine,salon,rezdechaussee'"}
String cuisine_NextEventName3 "cuisine proch. evt. 3 [%s]" <calendar> …
=> [caldav] add filter-category-any

features/openhab-addons/src/main/feature/feature.xml
as per our discussion, the suffix makes sense on bindings, but not necessarily on persistence add-ons, so I am reverting this.
=> reverted suffix on persistence add-ons

bundles/action/org.openhab.action.satel/src/main/java/org/openhab/action/satel/internal/SatelActionService.java
This PR fixes "[setSatelCommModule] not found; Component will fail" error when using Satel Action bundle in openHAB 2.
=> [satel] OH2 compatibility fixes

bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavEvent.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java
Fix #4820, tested live on my home heaters
rebased on upstream/master on 2016/12/03
The issue was that some known recuring events, under specific confitions would not have their schedule updated ; the reload code is calling the function "addEventToMap" for every new or modified event, but the event was already in the map, thus the call was ignored. Fixed that. At least this case does not occur at my home, all my heaters (zwave controlled) have worked perfectly this week (never before).
Added a lot of trace and debug lines to be able to understand what was
going on
revert .classpath modifications
cosmetics + small perf improvement
remove lambda expression
(jenkins alergic)
=> [caldav] fix #4820 recurring events not scheduled

bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRBinding.java, bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java, bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchBinding.java, bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/internal/FritzboxBinding.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064Binding.java, bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBinding.java, bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java, bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBinding.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/connection/OneWireConnection.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowerMaxBinding.java
For every current binding that has an `ESH-INF/binding/binding.xml` file with configuration parameters, replace all constructs like
```java
String configValue = (String) config.get(“configKey”);
```
with
```java
String configValue = Objects.toString(config.get(“configKey"), null);
```
Because OH2 runtime, unlike OH1 runtime, the ConfigAdmin dictionary can have non-String config values.
=> Replace string casting of config values

bundles/persistence/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java
Quotes are added around the retention policy and measurement
identifiers. The lexer of influxdb treats 'default' (which
is also the default retention policy) as a reserved word.
This will also allow querying items which have reserved
characters in their names.
Tested on openhab2. Fixes at least:
https://github.com/openhab/openhab/issues/4840
=> [influxdb] Quote retention policy and measurement

bundles/persistence/org.openhab.persistence.gcal/META-INF/MANIFEST.MF
Bundle was importing ch.qos.logback packages which were never referenced, but also not present in OH2.  See https://github.com/openhab/openhab/pull/4891#issuecomment-267331202
=> [gcal-persistence] Remove unneeded ch.qos.logback imports

features/openhab-addons/src/main/feature/feature.xml
- Changed gcal and gcal-persistence feature names to "Google Calendar Scheduler" and Google Calendar Presence Simulator, respectively
- Moved gcal to misc category
=> [gcal] Rename features and add gcal to misc category

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java
I have many lines in my log like
```
2016-12-17 14:20:52.586 [INFO ] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 2: does not support SECURITY_REPORT, proceeding to next stage.
```
It seems like this could be at DEBUG log level.
=> [zwave] Decrease logging for "does not support SECURITY_REPORT"

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
Sometimes the following warnings/errors show up when the binding is started:
```
2016-12-12 09:01:11.124 [WARN ] [ng.plugwise.internal.PlugwiseBinding] - Plugwise can not add device with name: light and MAC address: 000D6F0000414243, the same MAC address is already used by device with name: 000D6F0000414243
2016-12-12 09:01:11.201 [WARN ] [ng.plugwise.internal.PlugwiseBinding] - Plugwise can not add a valid device without a proper MAC address. light can not be used
2016-12-12 09:01:11.244 [ERROR] [ng.plugwise.internal.PlugwiseBinding] - Error scheduling a Quartz Job for a non-defined Plugwise device (light)
```
As a result the respective named device can not be used until the binding is restarted.
This PR resolves the issue by only starting the Stick messaging threads when …
=> [Plugwise] Fix device names can sometimes not be resolved

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/GetStationsDataResponse.java
Changed <= to < for rf level and >= to > for battery level since levels were off by one.
=> netatmo: fix logic for rf and battery level to match the levels that are displayed with the apps.

bundles/binding/org.openhab.binding.plex/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexApiLevel.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexBinding.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnectionProperties.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/Device.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/SessionUpdate.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/websocket/Child.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/websocket/NotificationContainer.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/websocket/PlaySessionStateNotification.java, bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/websocket/Update.java
This fixes two issues in the current Plex binding:
- Latest Plex Media Server (>= 1.3.2.3112) sends a different message format over the websocket connection. The binding now supports both this and the earlier format.
- No websocket connections were possible when authentication was enabled in PMS. The token used for other http calls is now also sent as a query parameter when connecting to the websocket.
=> Update for Plex binding

bundles/binding/org.openhab.binding.iec6205621meter/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.nikobus.test/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.nikobus/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.stiebelheatpump/META-INF/MANIFEST.MF, pom.xml
brings back gnu.io to fix the build
=> updated dependency reference

bundles/binding/org.openhab.binding.zwave/database/enerwave/zwnrsm2.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Related to https://github.com/openhab/org.openhab.binding.zwave/issues/229, but for OH1. I exported the device from the database at www.cd-jackson.com. I added zwmrsm2.xml because the existing zwn-rsm2.xml in the same folder doesn't seem to match what was exported from the device database.
=> Add new device ID for ZWN-RSM2 (0101:5606)

bundles/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/core/DmxController.java, bundles/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/core/DmxTransmitter.java, distribution/openhabhome/configurations/openhab_default.cfg
Adds configurable DMX transmit refresh. The "refresh" configuration option defaults to -1 (never refresh), which is compatible with the current implementation. A value of 0 would refresh every 35ms, another value would transmit data if it has been changed or the last transmission is more than (value) ms in the past.
=> [dmx] fixes #4774

bundles/action/org.openhab.action.satel/src/main/java/org/openhab/action/satel/internal/Satel.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelCommModule.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBinding.java
This PR adds new action method `satelResetUserCode()` which reverts user code set by `satelSetUserCode(String)` to the value configured in *openhab.cfg*.
=> [satel] Added ability to revert user code

bundles/binding/org.openhab.binding.netatmo/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.netatmo/build.properties, bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
netatmo: fixed a error when using the optional granularity parameter, added the ability to configure netatmo with the the OH2 Paper UI. The binding shows up as "Netatmo Binding (1.x)".
=> netatmo: add ability to configure via OH2 Paper UI

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
Ignoring local events is the correct behaviour of the binding. This message only blows up my and probably logfiles of other users.
Signed-off-by: Sebastian Kutschbach <sebastian.kutschbach@freenet.de>
=> KNX-Binding: Changed warn to debug in log message 'Ignoring local events...'

bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBindingConfigFactory.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyBindingConfig.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyWritableBindingConfig.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/OneWireDevicePropertyExecutableBindingConfig.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/OneWireDevicePropertyPushButtonBindingConfig.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/OneWireDevicePropertySwitchBindingConfig.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/modifier/AbstractOneWireDecimalTypeModifier.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/modifier/AbstractOneWireOnOffTypeModifier.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/modifier/AbstractOneWireOpenClosedTypeModifier.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/modifier/OneWireTypeModifier.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/listener/OneWireDevicePropertyWantsUpdateListener.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/scheduler/OneWireUpdateScheduler.java, bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/scheduler/OneWireUpdateTask.java
The new option makes it possible to use a relay like a pushbutton. It
is possible to do that with a rule and timer, but then you have no
control of the real time a button is pushed on slow systems.
Example:
onewire="deviceId=29.66C30E000000;propertyName=sensed.0;refreshinterval=10";pushbutton=500;invert",autoupdate="false"
New PullRequest for closed: #4063
=> OneWireBinding: New feature pushbutton

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Circle.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Energy.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/CalibrationResponseMessage.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/InformationResponseMessage.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/PowerBufferRequestMessage.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/PowerBufferResponseMessage.java, bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/PowerInformationResponseMessage.java
This PR improves the Plugwise Circle/Stealth power measurements as follows:
* Increase precision by using `PULSES_PER_KW_SECOND = 468.9385193` which is also used by all other Plugwise implementations on the internet, instead of `PULSE_FACTOR = 2.1324759f` which is: `1/(468.9385193/1000)` but with loss of precision
* Increase precision by using doubles instead of floats in calculations
* Use seconds correction that is part of the `PowerInformationResponseMessage`
* Fix wrong `Energy` date/time values being used in `PowerBufferResponseMessage`
* Corrected log address calculations in `InformationResponseMessage`, `PowerBufferRequestMessage`, `PowerBufferResponseMessage` because the original address calculation would cause the same logs returned multiple times (inspired by …
=> [Plugwise] Power measurement improvements

bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/ADMsgType.java, bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBinding.java, bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderGenericBindingProvider.java, bundles/binding/org.openhab.binding.diyonxbee/src/main/java/org/openhab/binding/diyonxbee/internal/DiyOnXBeeBinding.java
Overview of LRR Support : http://www.alarmdecoder.com/wiki/index.php/LRR_Support
Alarm Decoder LRR Protocol : http://www.alarmdecoder.com/wiki/index.php/Protocol#LRR
Sample usage:
Item MUST be in this format:
**String sAlarmLRR "LLR Msg: [%s]" (gAlarmPanel) {alarmdecoder="LRR:00#text"}**
ITEMS:
```
String sAlarmLRR "LLR Msg: [%s]" (gAlarmPanel) {alarmdecoder="LRR:00#text"}
String sAlarmLRR_lastUser "Last User: [%s]" (gAlarmPanel)
String sAlarmLRR_lastEvent "Last Event: [%s]" (gAlarmPanel)
DateTime sAlarmLRR_lastEventDateTime ""  (gAlarmPanel)
String sAlarmLRR_lastPartition "Last Partition: [%s]" (gAlarmPanel)
```
RULES:
```
import java.util.Map;
import java.util.HashMap;
import com.google.common.collect.ImmutableMap
val Map<String, String> UserList = ImmutableMap.<String, String>builder() …
```
=> [AlarmDecoder] Added support for AlarmDecoder LRR Protocol

bundles/persistence/pom.xml
See https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1404/console
=> temporarily removed dynamodb persistence as it breaks the build

bundles/binding/org.openhab.binding.fht/src/main/java/org/openhab/binding/fht/internal/FHTBinding.java
The FHT binding would not send correct control commands for low temperature values.
(
Presumably, this bug was hidden for quite a long time, since virtually nobody sets low temperatures to heat their homes :-)
)
Detailed bug description
Temperature control command are hex strings following the "FHT80b syntax: THHHHCCAA" given in http://culfw.de/commandref.html#cmd_T. (Note: Temp commands can only be sent to FHT80b devices, i.e. the buggy method setDesiredTemperature(...) will not be called for commands requiring other syntax.)
Low temp values were converted to one-digit hex strings, whereas two-digit hex-strings are required, cf. the trailing AA part of the command string.
=> bugfix: padding of FHT temperature control hex string

bundles/binding/org.openhab.binding.zwave/database/products.xml
Hi,
Following this thread https://community.openhab.org/t/vision-zipato-zd2102-not-recognized/20083.
Windows sensor Vision Security ZD2102 is also available from Zipato manufacturer. It is exactly the same product, but the manufacturer ID is not the same.
=> [ZWave] Support ZD2102 from Zipato

bundles/binding/org.openhab.binding.zwave/database/mcohome/mh9co2wd.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Please add this device to the zwave database. Here is the link to the
online database: [Link](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/455?layout=openhab1)
Signed-off-by: David Masshardt <david@masshardt.ch> (github:
TheNetStriker)
=> Zwave database update: McoHome CO2 monitor

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/LocationConfig.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/ForecastIoProvider.java, distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/src/main/resources/conf/weather.cfg
Fulfills feature request in #3062.
=> [Weather] Allow Forecastio to request units other than SI

bundles/io/org.openhab.io.gcal/src/main/java/org/openhab/io/gcal/internal/util/ExecuteCommandJob.java
The Google Calendar Scheduler is instructed to send a whole number for a PercentType like 50, but was sending 50.0 because the StreamTokenizer was identifying a number (TT_NUMBER) which means it gives a `double`, whose string representation of whole numbers ends in ".0".  This change causes TT_NUMBER tokens to never happen, so numbers are always their string representation, which can be dealt with
[Forum discussion](https://community.openhab.org/t/presence-simulation-with-google-calendar-scheduler/19281/19?u=watou)
=> [gcal] Ensure number updates and commands survive round trip

bundles/binding/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/handling/ComfoAirConnector.java, bundles/binding/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirBinding.java
- Add RXTX CPU workaround
- Change Thread to SchedulerExecutorService
- Remove flush() on send, can cause blocking forever
=> [ComfoAir] Optimize serial connection

bundles/io/org.openhab.io.gcal.test/src/test/java/org/openhab/io/gcal/internal/util/ExecuteCommandJobTest.java
Test was expecting the incorrect ".0" in the parse result.  See #5039
=> Fixed incorrect gcal test

bundles/binding/org.openhab.binding.tinkerforge/README.md
@theoweiss:
I changed the markdown to work at docs.openhab.org  (every heading and code block needs a blank line above and below).  Also regenerated the TOC.  If you have edits in progress, please recreate these changes in your copy.  Otherwise, please OK this PR.  Thanks!
=> Fix markdown; change back to LF

bundles/binding/org.openhab.binding.tinkerforge/README.md
Some extra blank lines for Markdown formatting.  Changed `/services/` to `services/` to avoid possible confusion.  @theoweiss OK with you?
=> [tinkerforge] Final Markdown adjustments

bundles/binding/org.openhab.binding.dmx/README.md
Now in the right repo.
Replaces https://github.com/openhab/openhab-docs/pull/327
=> Update OLA links

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/CULLifecycleManager.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/network/CULNetworkHandlerImpl.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/serial/CULSerialHandlerImpl.java
This Pull Request addresses the issues described in #4035. I replaced the current implementation of CULNetworkHandlerImpl with a nio based one to simplify handling of connection errors. 
To enable this change slight changes in other components of the CUL transport were necessary. Mainly the responsibility of low level communication is now in the respective handler implementations and not in the AbstractCULHandler any more.
=> Improved the reconnect behaviour of CULNetworkHandlerImpl

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/CULLifecycleManager.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/network/CULNetworkHandlerImpl.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/serial/CULSerialHandlerImpl.java
As discusssed/requested in #4359.
- Fix synchronization issues
- Eclipse formatting
- Logging cleanup
=> [Cul] Fix formatting and synchronization issues

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java
The DSC Alarm command was not working correctly.  The binding was
erroneously checking for a partition number which is not required by
this command.  This has been tested as seen [here](https://community.openhab.org/t/dsc-alarm-binding-sending-code-for-the-panic-button/23314/2), and found to be working correctly.
Signed-off by: Russell Stephens rsstephens@gmail.com (github:@RSStephens)
=> [DSCAlarm] Bug Fix: DSC Alarm Command 060 Not Working

bundles/persistence/org.openhab.persistence.jdbc/README.md, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, pom.xml
fixes crash on startup in raspberry pi, 3.8.11.2 does not work with armhf proc.
[Forum discussion](https://community.openhab.org/t/openhab2-jdbc-persistence-sqlite/16088/9)
```
#
#
#
#
#
#
Stack: [0xab224000,0xab274000],  sp=0xab26f900,  free space=302k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [sqlite-3.8.11.2-5a76de3a-1d60-4101-b599-a9158d4ca28f-libsqlitejdbc.so+0x5cb0]
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;Z)V+0
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+328
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+48
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57
j …
```
=> [jdbc] Update sqlite to latest version

bundles/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeboxBinding.java
Fix the playing time to use a number and not a percent.
Rename the numberChangeEvent() method to percentChangeEvent().
Add a new numberChangeEvent() method that uses DecimalType instead of PercentType.
Fixes #3542.
=> [Squeeze] Fix playing time error

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java, bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/UDPBinding.java
This is to prevent the null pointer exception reported in #5110 .
Also updated configuration updates to use Objects.toString() and fixed Eclipse formatting.
Fixes #5110.
=> [TCPBinding] Prevent null pointer exception in UDPBinding

bundles/binding/org.openhab.binding.iec6205621meter/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openmuc/j62056/Connection.java
Trap ArrayIndexOutOfBoundsException in the bytesToHexString() method.
When encountered, fall back to a simpler method of conversion.
Fixes #4651.
=> [iec6205621meter Binding] Fix ArrayIndexOutOfBoundsException

bundles/binding/org.openhab.binding.zwave/database/products.xml
Z-Wave: Added id:type (2002:0501) to Fibaro Universal Binary Sensor (FGBS-001)
=> [Z-Wave] Database update: Fibaro Universal Binary Sensor (FGBS-001)

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBinding.java
Introduced projector state cache, which will minimize projector state
queries.
=> Epson projector binding Improvements

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/protocol/API.java, bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java, bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/UDPBinding.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavQuery.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
If config is null, log a warning and return.
Switch to using Objects.toString() for reading config values.
Drop the thrown exceptions for missing username/password, since those values are not required.
Add a warning to the log output if the url is not specified in the configuration.
Use the default TimeZone if the one specified in configuration is invalid.
Misc. fixes in openhab_default.cfg and caldavio.cfg.
Fixes #5116
=> [CalDAV] Various configuration fixes

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgs213.xml, bundles/binding/org.openhab.binding.zwave/database/products.xml
Added FGS-213 from OpenHAB 2 repo, as per @cdjackson suggestion, see https://community.openhab.org/t/database-missing-z-wave-fibaro-fgs-213-switch/25298 and https://github.com/openhab/org.openhab.binding.zwave/issues/418. I have added this product next to the similar FGS-223, which was already in products.xml.
=> Z-Wave Binding: Added Fibaro FGS-213

bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java
This fixes a problem described in https://community.openhab.org/t/caldav-binding-setup-issue/21651 caused by a race-condition of the binding not having been initialized at the right time.
Should find some time to do a new openhab 2 port, but for now we're fine.
=> [caldav] Fix race condition causing NPE

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/command/IntegraStateCommand.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/SatelBindingConfigFactory.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/IntegraStateEvent.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/DoorsState.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/ObjectType.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/OutputState.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/PartitionState.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/StateType.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/TroubleMemoryState.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/TroubleState.java, bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/ZoneState.java
This PR introduces support for detailed Integra troubles. It allows defining items that reflect various troubles in Integra alarm system.
=> [satel] Support for troubles added

bundles/binding/org.openhab.binding.ecotouch/README.md, bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/EcoTouchTags.java, bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchBinding.java
Also documented new values and some state mappings.
Closes #5165
Signed-off-by: Christian Stübner <c.stuebner@digitalvitamin.de> (github: Digitalvitamin)
=> [ecotouch] Add divider for analog values and additional temperature values (#5165)

bundles/binding/org.openhab.binding.asterisk/.classpath
Fixed a bad entry in the .classpath file that was causing errors in Eclipse.
=> [Asterisk] Fix bad classpath entry

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
This should fix bug #4548 where after a timed-out connection all further connections fail with a 401 unauthorized error.
=> [fritzboxtr064] Reset HTTP auth cache in case of connection errors

bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java
=> [pushover] Changed root-tag to 'response' and added warning if the Pushover response contains an info-tag

bundles/persistence/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java
...as it did not look at the base item before, so it was falling back to
StringType for all group items.
fixes #5238
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
=> [influxdb] fix state type calculation of group items

bundles/binding/org.openhab.binding.lightwaverf/src/main/java/org/openhab/binding/lightwaverf/internal/command/LightwaveRfEnergyMonitorMessage.java
Work around the total lack of data validation to prevent the binding from crashing OH.
Fixes #5226.
=> [LightwaveRF] Don't let the energy monitor crash OH

bundles/binding/org.openhab.binding.plugwise/.project, features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
This PR will will move the Plugwise binding to the legacy bindings and can be merged after https://github.com/openhab/openhab2-addons/pull/1907 is merged.
=> Move Plugwise1 Binding to legacy bindings

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR fixes a deadlock when stopping the binding.
=> [Satel] Binding deactivation fix

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Related to #5254 from @MrMontesa.
This improves the error handling in the Telegram action by distinguishing between the case where the URL fetch returned "200 OK", but no content, and the case where the URL fetch returned content that could not be recognized as a supported image type.  This provides a better warning message to the user in the logs.
Also cleaned up the log messages to conform better to the logging guidelines.
=> [Telegram] Distinguish between "no image retrieved" and "unrecognized image" errors

bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/utils/EBusUtils.java
This PR fixes a CRC calculation issue if the CRC byte 0xAA is expanded to 0xA9 0x01
Started from community thread, already got feedback from user.
https://community.openhab.org/t/ebus-binding/3399/163
=> [eBUS] Fix escaping issue if slave CRC is 0xAA

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
Http Binding logs the following error if the config key "format" is included in http.cfg
> [ERROR] [ab.binding.http.internal.HttpBinding] - given config key 'format' does not follow the expected pattern '<id>.<url|updateInterval>'
This PR adds the format config key to the list of excluded keys from additional processing
=> [HTTP Binding] Don't log an error when the "format" configuration setting is found

bundles/binding/org.openhab.binding.fritzboxtr064/README.md, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
Reading the WAN IP via the FritzBox SOAP service API WANPPPConnection1 only works if the FritzBox establishes the PPP connection itself. If it uses an external router for internet connectivity, WANIPConnection1has to be used instead. The patch adds the option to configure an item for this.
Fixes #5283
=> [fritzboxtr064] get wan ip from external router (#5283)

pom.xml
_This is a cross-repo change which is part of the implementation of a release automation process for openHAB_
This adjusts scm connection info within the pom.xml which is used by release automation processes to push changes, create tags etc. The property `scm.gitBaseUrl` is taken from the parent pom within the openhab-core component https://github.com/openhab/openhab-core/blob/a1e10ccea71189991fb542e4251ac8bee04c4c91/poms/pom.xml#L51 and makes it possible to easily make "sandbox releases" on separate repositories. Within the `url` tag, the `scm.gitBaseUrl` is intentionally not used because in discussions with @kaikreuzer I agreed that we aim to keep the pom.xml human-readable without always having to lookup properties from the parent pom(s). As the `url` tag is just a meta information and …
=> Make git scm easier configurable (e.g. for forks / sandbox usage)

bundles/binding/org.openhab.binding.fritzboxtr064/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.fritzboxtr064/OSGI-INF/binding.xml, bundles/binding/org.openhab.binding.fritzboxtr064/OSGI-INF/genericbindingprovider.xml, bundles/binding/org.openhab.binding.fritzboxtr064/README.md, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/FritzboxTr064BindingProvider.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/AbstractItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallEvent.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallMonitor.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064Binding.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064GenericBindingProvider.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Helper.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ItemConfiguration.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/MultiItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ParametrizedItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhoneBookEntry.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/SingleItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/SoapValueParser.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Service.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/WritableItemMap.java
This change adds items for DSL and WAN statistics to the fritzboxtr064 binding.
Supporting the new items required a somewhat large change to the ItemMap-related code because previously the code did not support reading the values of multiple items in a single SOAP service request. I basically splitted the existing ItemMap in a MultiItemMap which can extract multiple item values from a single SOAP response but does not (currently) support input parameters and writing values, and a SingleItemMap, which has all existing functionality but supports only a single item value per SOAP response. I also introduced the ItemConfiguration abstraction for the openhab item config to make the handling of item commands and parameters explicit
I asked gitbock if he agrees with me making changes to the …
=> [fritzboxtr064] add items for dsl/wan statistics (#5221)

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
Reimplemented additional colormode and aspectratio values as originally proposed by @jaydonoghue in his PR, but with fixed values.
Fixes #4935.
=> [epsonprojector] Add additional ColorMode and AspectRatio values (from 5030UB projector)

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
Changed logging level from warn to debug for UnDefType items as they
pollute logs.
=> [JDBC persistence] Decreased logging level

bundles/binding/org.openhab.binding.knx/README.md
There was a new line in the markdown link syntax that broke the GIRA link.
minor fix.
=> [KNX] Fixed README markdown syntax for docs.openhab.org

pom.xml
I believe currently the static-code-analysis tool can be executed but doesn't log the errors in this repo.
With this change it doesn't execute at all.
Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>
=> Deactivated the static-code-analysis tool.

bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBitemSerializer.java
I tried to implement a NPE safe-guard as suggested in https://github.com/eclipse/smarthome/issues/4104#issuecomment-323926875 for storing values in mapdb persistence.
Closes #5285 
=> [mapdb] Avoid NPE if null is passed to writeUTF() method

bundles/binding/org.openhab.binding.tacmi/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBinding.java, bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiMeasureType.java, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/tacmi.cfg
As I now have the TA CMI binding running with openhab 2 for several months, I think it is safe to add it to the distribution.
Included is a small change of one scale factor which turned out to be necessary after a firmware change of the C.M.I, and a slightly better error handling when the listening socket can't be created.
=> [tacmi] Add binding to openhab2 distribution

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Fixes #5336
The API should be backwards compatible, but I urge maintainers to review this very carefully.
Signed-off-by: Sami Salonen <ssalonen@gmail.com>
=> [telegram] sendTelegramPhoto has now configurable timeout and retry

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Precipitation.java
- The modifier `DOUBLE_3H` is not needed to parse the forecast data.
- Added mapping for parsing snow from forecast data
=> [weather] Fixed parsing of rain value in forecast data

bundles/binding/org.openhab.binding.iec6205621meter/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.powermax/ESH-INF/binding/binding.xml
=> added serial-port context to config parameters in order to support automatic selection lists

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/AbstractDatagramChannelBinding.java, bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/AbstractSocketChannelBinding.java
Prevent the null pointer exceptions found during shutdown by @tbnobody in #2706.
However this does not fix #2706.
Also clean up logging and switch to using Objects.toString() for retrieving configuration settings.
=> [TCPBinding] Prevent null pointer exceptions during shutdown

pom.xml
This should solve the current build problems.
As openHAB 1 add-ons do not depend on any changes in ESH/openHAB2 target platform, it should be safe to always compile against the older 2.1.0 version of it.
=> compile against 2.1.0 target platform

bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/SoulissBinding.java
The NPE happens for all items that are not of souliss type. The fix is rather ugly, but it works.
There are at least three articles in the community site referencing this problem:
* https://community.openhab.org/t/yamahareceiver-binding-has-issue-with-zone-2/19731/7
* https://community.openhab.org/t/issue-with-souliss-binding-after-update/20246/3
* https://community.openhab.org/t/oh2-crash-after-3-4-days-running/34962
Fixes #5369.
=> Fixes NPE in souliss binding

pom.xml
Workaround for build issues raised by #5372 (unleash plugin was not present in openHAB 2.1 parent pom).
=> Add maven unleash plugin for automated releases

bundles/binding/org.openhab.binding.dsmr/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.plugwise/ESH-INF/binding/binding.xml, bundles/binding/org.openhab.binding.upb/ESH-INF/binding/binding.xml
Adds the serial-port context to the other bindings that have a serial port configuration parameter but were not part of #5360.
=> Add serial-port context to config parameters of bindings

bundles/binding/org.openhab.binding.tinkerforge/README.md
Added explanation for using symbolic names if more than one device of the same type is used.
Related coumminty forum thread:
https://community.openhab.org/t/how-to-use-multiple-tinkerforge-io-16-bricklet/36749
Signed-off-by: Siegfried Huismann <sihui@gmx.de>
=> Update TinkerForge README.md

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULManager.java, bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/serial/CULSerialHandlerImpl.java
I've build a throttle, which waits with sending a new command for the response of the former command to prevent race conditions.
See issue #5328
I've tested this with the Intertechno binding, but no other, which use the CUL transport
=> [CUL transport] Throttle commands, which are sent to the CUL

features/openhab-addons/src/main/feature/feature.xml
Some recently merged bindings don't have a "1" suffix in their feature name. 
This will also resolve the "404 Not Found" errors when you click on the respective bindings in Paper UI to show their documentation.
=> Correct feature names

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Update to send the username and password received, not nulls.
Fixes #5398
=> [Telegram Action] Fix sending of photos with authentication

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java, bundles/binding/org.openhab.binding.knx/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBindingDatapointReaderTask.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java, bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Added an assertion that the type not be null in the test for 19.001 DPT_DATE_TIME. This is for #5422.
(However, not that this is not a fix for #5422, just an enhancement)
Also cleaned up some compiler warnings.
=> [KNX.Test][KNX] Add a NotNull assertion to the 19.001 DPT_DATE_TIME test.

bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBinding.java
Prevent the null pointer exceptions described in #4236 and #5459.
5459 also spawned [this community thread](https://community.openhab.org/t/pilight-binding-how-to-get-it-to-work-with-latest-openhab/39322/2).
=> [Pilight] Fix NullPointerExceptions in the checkItemState() method

bundles/action/org.openhab.action.xmpp/README.md
- Note that linter errors still present around URL literals in table.
Did not know how to correct this.
=> [XMPP Action] Fix some linter errors

bundles/binding/org.openhab.binding.fs20/README.md
User `openhab` needs to be in the `dialout` group so it can access a CUL device unter `/dev/ttyACM0`. Otherwise an exception occurs.
Signed-off-by: David Waldhans <public@waldhans.at> (github: dwaldhans)
=> [FS20] Add remark about adding openhab user to dialout group

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBinding.java
Close connection to projector if command fails. Connection is reopened
when next command is send to projector. Also decreased some logs to
debug level (binding doesn't spam log anymore if projector is completely
powered off. 
=> [EpsonProjector] Improved connection stability

bundles/binding/org.openhab.binding.exec/.project, bundles/binding/org.openhab.binding.freebox/.project, bundles/binding/org.openhab.binding.hdanywhere/.project, bundles/binding/org.openhab.binding.mcp23017/.project, bundles/binding/org.openhab.binding.milight/.project, bundles/binding/org.openhab.binding.netatmo.test/.project, bundles/binding/org.openhab.binding.oceanic/.project, bundles/binding/org.openhab.binding.opensprinkler/.project, bundles/binding/org.openhab.binding.pioneeravr/.project, bundles/binding/org.openhab.binding.pulseaudio/.project, bundles/binding/org.openhab.binding.rfxcom.test/.project, bundles/binding/org.openhab.binding.rfxcom/.project, bundles/binding/org.openhab.binding.rme/.project, bundles/binding/org.openhab.binding.samsungtv/.project, bundles/binding/org.openhab.binding.squeezebox/.project, bundles/binding/org.openhab.binding.systeminfo.test/.project, bundles/binding/org.openhab.binding.systeminfo/.project, bundles/binding/org.openhab.binding.tellstick/.project, bundles/binding/org.openhab.binding.yamahareceiver/.project
This should fix the issue that only the OH1 or the OH2 version of these projects can be automatically imported in Eclipse.
Maybe we should add the 1 suffix to all binding projects to prevent future issues? The same has been done with the feature names.
=> Rename Eclipse projects for bindings that also exist in OH2

bundles/io/org.openhab.io.transport.mqtt/src/main/java/org/openhab/io/transport/mqtt/internal/MqttBrokerConnection.java
Allow the broker's URL and clientID to be modified without restarting the whole binding.
Fixes #5500.
Fixes #3394.
=> [MQTT] Allow broker URL and clientID to be modified while running

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
=> moved RWE SmartHome to legacy add-ons

bundles/action/org.openhab.action.pushover/META-INF/MANIFEST.MF, bundles/action/org.openhab.action.pushover/README.md, bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java
- Added new actions `sendPushoverEmergency` for sending emergency-priority notifications
- Added new actions `cancelPushoverEmergency` to cancel emergency-priority notifications
- Switched API partially to JSON
- Code cleanup
Closes #5458 
=> [Pushover] Added Receipts and Callback API for handling of emergency-priority notifications

bundles/binding/org.openhab.binding.fritzboxtr064/README.md
Fixes #5538. 
A)
Replaced all hash characters (#) with double slash (//) in the item configuration section.
This enables users of OH2 to just copy/paste the item list.
B)
In the Rules section I have replaced some lines, mainly because CallType has to be replaced with StringListType
Again, this enables easy copy/paste for OH2 users.
Stefan
=> [FritzboxTr064] Update README.md

bundles/binding/org.openhab.binding.serial/META-INF/MANIFEST.MF, bundles/binding/org.openhab.binding.serial/README.md, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java
Fix the configuration parsing error.
Clean up compiler warnings.
Make minor fixes in README.md.
Fixes #5542
=> [Serial] Fix configuration parsing error in the serial binding

bundles/binding/org.openhab.binding.tinkerforge/README.md
I changed the subid's for 
* Industrial Digital Out 4 Bricklet:
* Industrial Digital IN 4 Bricklet:
to match the examples.
Fixes #5545
=> proposed solution for "[Tinkerforge] Readme is wrong #5545"

bundles/action/org.openhab.action.pushbullet/META-INF/MANIFEST.MF, bundles/action/org.openhab.action.pushbullet/README.md, bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletAPIConnector.java, bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/model/Push.java
Added the ability to push notes to all subscribers of a channel based on the recipient format. Also, added the ability to push notes without specifying a recipient as the Pushbullet API will default to broadcast them to all the user account's devices.
=> [Pushbullet] Added ability to push notes to a channel

features/openhab-addons-legacy/src/main/feature/feature.xml
Because the old binding uses a different protocol the TV's supported by both bindings might vary
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl> (github: martinvw)
=> Add the Samsung TV Binding to the legacy bindings

features/openhab-addons-legacy/src/main/feature/feature.xml
Reverts openhab/openhab1-addons#5564
Sorry. A short test suggests that its not working so I rather not spent time on this but on making the OH2 binding behave properly :-) 
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Revert "Add the Samsung TV Binding to the legacy bindings"

bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java
Fix a binding configuration parsing error, as reported in [this community thread](https://community.openhab.org/t/serial-binding-regexps/44466).
This regression is one I inadvertently introduced while fixing #5542.
=> [Serial] Fix a binding configuration parsing error

bundles/binding/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOGenericBindingProvider.java
more than 3 arguments did throw an error. I just changed the value to 4 to allow all of the possible ones.
=> [GPIO] Fixed Arguments Error

bundles/binding/org.openhab.binding.fritzboxtr064/README.md, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/InputArgument.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ItemConfiguration.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/MultiItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/ParametrizedItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/SingleItemMap.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/SoapValueParser.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java, bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/WritableItemMap.java
Add a new command item type `callDeflectionSwitch` which reads and sets the current state of a call deflection entry in the FritzBox.
The first two commits are refactorings which unify the handling of input arguments for reading and writing calls to the FritzBox TR064 API and to simplify configuration of FritzBox items.
=> [FritzboxTr064] Add switch to change call deflection on/off (#5290)

bundles/binding/org.openhab.binding.systeminfo/README.md, bundles/persistence/org.openhab.persistence.rrd4j/README.md
- Added `everyMinute` strategy to examples in documentation
- Fixed spelling
wrt: https://github.com/openhab/openhab-docs/pull/723#issuecomment-397869854
=> [rrd4j] Added 'everyMinute' strategy to examples in documentation

bundles/binding/org.openhab.binding.comfoair/README.md
I added the device commands from the [issue](https://github.com/openhab/openhab-docs/issues/521) opened by binderth. 
Also rearranged the sequence to make it more logical.
Closes openhab docs issue #521.
Signed-off-by: Maurits Jaspers <mauritsjas@gmail.com> (github: Maurits28)
=> [ComfoAir][Documentation] - Add undocumented features

bundles/binding/org.openhab.binding.vdr/src/main/java/org/openhab/binding/vdr/internal/VDRConnection.java
VDR is not a typical always on service, so it's very common that vdr is not available.
Signed-off-by: Udo Hartmann udo1toni@gmail.com
=> [vdr1] change logLevel for could not connect to DEBUG

bundles/binding/org.openhab.binding.ekey/README.md, bundles/binding/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/EKeyGenericBindingProvider.java
Fix the string values in two thrown exceptions to use the correct term `RELAYID`.
Also clean up the README.
Fixes #5609
=> [ekey] Fix values in thrown exceptions

bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseListener.java
This is a fix of issue #5623: garbled zibase messages
The buffer was indeed not cleared, causing the previous messages to remain visible if longer.
=> [Zibase] Cleaning the zibase message buffer: fix of #5623

bundles/persistence/org.openhab.persistence.dynamodb/ESH-INF/config/config.xml, bundles/persistence/org.openhab.persistence.dynamodb/OSGI-INF/dynamodb.xml, bundles/persistence/org.openhab.persistence.dynamodb/build.properties, bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java, features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/conf/dynamodb.cfg, features/openhab-addons/src/main/feature/feature.xml
This PR introduces the changes discussed in #5334. I highly recommend reading that thread for background.
Currently DynamoDB is not part of the official addon bundle since it not supporting up-to-par with new openHAB2 packaging requirements. It is working though without any issues using textual configuration.
To meet openHAB2 requirements, this PR introduces:
- Karaf feature `openhab-persistence-dynamodb`
- PaperUI configuration support (actually I think this might the first persistence to have this)
Furthermore, `service.pid` is now declared, which seems to help with the textual configuration (in case someone prefers it over UI). I also had to adjust some OSGI parameters to make configuration reloading work as it should with the UI (once again, details in #5334).
I hope that with these …
=> [dynamodb] Introduce Karaf support

bundles/binding/org.openhab.binding.serial/README.md, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java, bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java
- Adds a new setting to select charset for string encoding.
- Problem parsing more than one setting is solved.
- The BASE64 setting can now also be written as BASE64() and then it
will be parsed correctly at any position inside the string.
- Readme updated regarding the new charset setting and the new BASE64
settings format.
Forum link: https://community.openhab.org/t/strange-problem-with-serial-binding/43230
Signed-off-by: David Masshardt <david@masshardt.ch> (github:
TheNetStriker)
=> [Serial] Added setting to select charset for string encoding

bundles/binding/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NetworkUpsToolsBinding.java
Perform proper bounds checking when reading configuration settings.
Fixes #5619.
=> [NetworkUPSTools] Prevent ArrayIndexOutOfBoundsExceptions during configuration update

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
This binding has been replaced by a openHAB version 2: https://github.com/openhab/openhab2-addons/pull/3720
=> [dsmr] Moved dsmr binding to legacy, replaced by openHAB 2 version.

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
=> moved OneWire binding to legacy add-ons

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
The KNX 1.x binding tests have been failing since half a year now.
This PR fixes a few tests so that they pass and sets the remaining ones to "ignore".
=> Address failing KNX unit tests

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java
fixed name resolution of address book entries.
the name resolution did not work 100% correct, if there are some white spaces in between the number, i.e. like this '+49 40 123 456 789'
=> [fritzboxtr064] replaced the trim method, to get rid of white spaces in between the tel numbers

bundles/persistence/org.openhab.persistence.caldav/OSGI-INF/caldav.xml, bundles/persistence/org.openhab.persistence.dynamodb/OSGI-INF/dynamodb.xml, bundles/persistence/org.openhab.persistence.influxdb08/OSGI-INF/influxdb.xml, bundles/persistence/org.openhab.persistence.jdbc/OSGI-INF/jdbc.xml, bundles/persistence/org.openhab.persistence.jpa/OSGI-INF/jpa.xml, bundles/persistence/org.openhab.persistence.mongodb/OSGI-INF/mongodb.xml, bundles/persistence/org.openhab.persistence.mysql/OSGI-INF/mysql.xml, bundles/persistence/org.openhab.persistence.rrd4j/OSGI-INF/rrd4j.xml
Same as https://github.com/openhab/openhab1-addons/pull/5659 for the other persistence services
=> made item registry mandatory in persistence services

bundles/action/org.openhab.action.pushover/README.md
- use ApiKey instead of ApiToken to match the Pushover API
- Reordering of the action section - show current actions first, move depreciated actions later
- Fixing the deprecated syntax highlighting
- Added default device to the table
- Removed the note about Builder pattern, not sure that it's really needed
=> [Pushover] Updates to reflect language used in the API

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
=> move owntracks to legacy add-ons as it has been replaced by the new gpstracker binding

bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/Mail.java, bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConnectorThread.java, bundles/binding/org.openhab.binding.bticino/src/main/java/com/myhome/fcrisciani/connector/MyHomeJavaConnector.java, bundles/binding/org.openhab.binding.ddwrt/src/main/java/org/openhab/binding/ddwrt/internal/DDWRTBinding.java, bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm1/internal/protocol/API.java, bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBinding.java, bundles/binding/org.openhab.binding.isy/src/main/java/org/openhab/binding/isy/ISYActiveBindingConfig.java, bundles/binding/org.openhab.binding.powerdoglocalapi/src/main/java/org/openhab/binding/powerdoglocalapi/internal/PowerDogLocalApiBinding.java, bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/RWESmarthomeConfig.java, bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetWLANConfig.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java, bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java, bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java
Fixes: https://github.com/openhab/openhab-distro/issues/762
Signed-off-by: Martin van Wingerden <martin@martinvw.nl>
=> [mysql-persistence] Do not log plain passwords

bundles/persistence/org.openhab.persistence.rrd4j/README.md
I have hignlighted the fact that the `everyMinute` strategy must be used,
There have been a number of recent queries regarding non persisted data with the rrd4j database where the user had not set the everyMinute strategy.
=> [Persistence][Documentation] Small change to highlight the mandatory use of the everyMinute strategy

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java
Eliminates a potential Null Pointer Exception in the getHost method, as described in #5668.
This showed up due to a user configuration pointing to an unresolvable hostname.
=> [Plex] Eliminate a potential Null Pointer Exception in the getHost method

features/openhab-addons/src/main/feature/feature.xml
Related to https://github.com/openhab/openhab-distro/pull/781
Not yet moving it to legacy addons - will do this once we can confirm that the new binding is fully integrated and working.
=> added "1.x" to mqtt binding label

bundles/binding/org.openhab.binding.plcbus/src/main/java/org/openhab/binding/plcbus/internal/protocol/AbstractReceiveFrameContainer.java, bundles/binding/org.openhab.binding.plcbus/src/main/java/org/openhab/binding/plcbus/internal/protocol/SerialPortGateway.java
This caused two different openhab threads to concurrently receive
bytes from the serial port. In turn, each thread received every other byte,
and so both threads saw corrupted frames. Even worse - threads would get
stuck waiting for response, and entire openhab was unresponsive until
restarted.
Adding synchronized helped. I've also improved logging of error (which is
now not being thrown in this scenario).
=> [PLCBus] Fix addon crash when two commands are sent in quick succession

features/openhab-addons-external/src/main/resources/conf/pushbullet.cfg
[+] Add the ConfigAdmin Persistent IDentity (PID) exclusive Marker on the first line to override existing/stored configurations
[-] Commented out the `accesstoken=1234abc` line to serve as an example (not to be activated when the Addon is installed)
[+] Added the default devicename in the config file
Refs:
1) https://github.com/openhab/openhab-distro/issues/396#issuecomment-332236729
2) https://github.com/eric-erki/smarthome/blob/e51fb052dc05a74358d948e904efe61b04c146fc/bundles/config/org.eclipse.smarthome.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java#L292
Signed-off-by: Angelos Fountoulakis agf@wired-net.gr (github: AngelosF)
=> [Pushbullet] Update pushbullet.cfg

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
Related to https://github.com/openhab/openhab2-addons/pull/3826
=> move EnOcean 1.x binding to legacy addons

bundles/action/org.openhab.action.telegram/README.md, bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
See https://github.com/openhab/openhab2-addons/issues/4286
Adds support for sending images contained on the local openHAB host's file system. Image files are specified using the file protocol (e.g. `file:///path/to/local/image.jpg`)
IDK why the README shows that the entire doc changed, as I only made several small additions.
Also the IDE forced several formatting changes in addition to the addition to the code for supporting the file protocol.
Signed-off-by: Mark Hilbush <mark@hilbush.com>
=> [Telegram] Add support for file protocol

bundles/binding/org.openhab.binding.tcp/README.md
Signed-off-by: Alex R. Berg, developlantern@gmail.com, github: arberg
Better example, info that its broken with links, added unclear stuff - strange to have in wiki, but better than leaving user in wilderness I believe. Lets just be honest, if somebody knows what it means and feels like specified that would be great.
=> [TCP Binding] Enhancements for README.md

bundles/binding/org.openhab.binding.ekey/README.md
I was browsing through the addons and noticed that the links are broken.
=> [ekey] Correct README links to ekey.net

bundles/binding/org.openhab.binding.tcp/README.md
Two problems found while reviewing #5594:
Fixed typographical error and removed outdated query.
=> [TCP] Minor fixes for README

features/openhab-addons/src/main/feature/feature.xml
Adds the "1" suffix to the ucprelayboard binding feature name which solves issues like "404 Not Found" when clicking on the binding name in Paper UI to show the documentation.
=> [ucprelayboard] Correct feature name

bundles/binding/org.openhab.binding.weather/README.md, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/property/UnixDateConverter.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Clouds.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Condition.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Precipitation.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/ProviderName.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Station.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Weather.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/ApiXuProvider.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherProviderFactory.java, bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherbitProvider.java, bundles/binding/org.openhab.binding.weather/src/main/resources/weather/common-id-mappings.xml
I 've added two new free provider for weather forecast.
-  APIXU [ApiXU](https://www.apixu.com/)
- Weatherbit [Weatherbit](https://www.weatherbit.io/)
Both provides a free forecast. Only ApiKey must be created like all other provider.
I will try to create openhab2-addons for these both in the next day's.
=>  [Weather] Add two new Provider APIXU and Weatherbit. 

bundles/action/org.openhab.action.telegram/README.md, bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java, bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramActionService.java, bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramBot.java, distribution/openhabhome/configurations/openhab_default.cfg, features/openhab-addons-external/src/main/resources/conf/telegram.cfg
This pull requests adds the ability to write messages that contain markdown or html tags, see https://core.telegram.org/bots/api#markdown-style.
It is configurable if a bot should use formatted messages in the `telegram.cfg`. This pull request is inspired by #5490 but since the other pull request is stale I started a complete rewrite.
=> [Telegram] Support for formatted messages

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml, bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
This will add the ability to add on level items into OpenHAB for the Insteon PLM binding. Items should be number type with a range from 0 to 255. The feature works the same as other features in the binding (LEDBrightness and RampRate). 
RampRate is Insteon message 0x05. LEDBrightness is Insteon message 0x07. OnLevel (new) is Insteon message 0x06.
=> [InsteonPLM] Add OnLevel feature to Insteon PLM 2477D dimmer

bundles/binding/org.openhab.binding.anel/README.md, bundles/binding/org.openhab.binding.fritzaha/README.md, bundles/binding/org.openhab.binding.gc100ir/README.md, bundles/binding/org.openhab.binding.lcn/README.md, bundles/binding/org.openhab.binding.nikobus/README.md
Hi,
I have clicked through the addons section and identified some images which are not loaded over `https` which causes the browser to throw a mixed content warning.
I have changed the urls where possible, to get rid of those warnings.
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>
=> [Documentation] Fixed mixed-content and added https urls and resources where possible

bundles/action/org.openhab.action.mail/README.md
Explain how to use names with the email address in the from and to parameters, as it wasn't obvious.
Move the explanation for the `to` parameter down, so it's more in context to its usage.
=> [Mail Action] Explain email address format

bundles/binding/org.openhab.binding.horizon/README.md
Furthermore, it should be considered whether the sendCommand method should be used.
=> [Horizon] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.denon/README.md
Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
=> [Denon] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.primare/README.md
=> [Primare] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.rwesmarthome/README.md
=> [Rwesmarthome] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.velux/README.md
=> [Velux] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.vdr/README.md
=> [VDR] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.zibase/README.md
=> [Zibase] Update README with better sendCommand alternative

bundles/action/org.openhab.action.twitter/README.md
Since there is no official binding for "Dropbox", as far as I know, this information is not helpful because you can not make any reference.
=> [Twitter] Remove reference to Dropbox from README

bundles/persistence/org.openhab.persistence.jdbc/README.md, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
Options `sqltype.tablePrimaryKey` and `sqltype.tablePrimaryValue` were not read
correctly. They were treated as yet another item type which didn't match their use
in the code.
Also added debug log of sql query similar to other functions.
Second commit is just a "copy/paste" bug fix.
=> [jdbc] Fix sqltype.table* options

bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java
Change the logic in the eventBegins() method so that the update goes out even if the event is "before now".
It's not clear why this check ever existed, anyway.
Looks like this fixes #5744.
=> [CalDAV-Personal] Make the calendar update even if the event is 'before now'

bundles/binding/org.openhab.binding.velux/README.md
for clarification of different password (frontend versus API).
=> [velux] Add note to clarify bridge password setting in README

bundles/persistence/org.openhab.persistence.dynamodb.test/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java, bundles/persistence/org.openhab.persistence.dynamodb.test/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java, bundles/persistence/org.openhab.persistence.dynamodb.test/src/test/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfigTest.java, bundles/persistence/org.openhab.persistence.dynamodb/ESH-INF/config/config.xml, bundles/persistence/org.openhab.persistence.dynamodb/META-INF/MANIFEST.MF, bundles/persistence/org.openhab.persistence.dynamodb/README.md, bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/AbstractBufferedPersistenceService.java, bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java, bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java, bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java
This PR introduces several performance optimizations to DynamoDB Persistence Service:
- buffering data in the PersistenceService, and writing it in batches on background.
We get performance gains by writing data in batches but also reduce
`items` `QueueingThreadPoolExecutor.taskQueue` pressure in `GenericItem.notifyListeners`.
- previously several checks were done on each store, causing
significant overhead on `store` and `query` operations: 1) connection check
(listing tables), 2) checking table existence. These are now removed,
table is created on error (`ResourceNotFoundException`).
In addition, I have implemented exponential back-off retry for writes.
I've been verified the changes in my local setup. Before I could see that `QueueingThreadPoolExecutor.taskQueue` size growed …
=> [dynamodb] Performance optimizations

bundles/persistence/org.openhab.persistence.dynamodb.test/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java
Attempt to fix https://ci.openhab.org/job/openHAB1-Addons/lastCompletedBuild/org.openhab.persistence$org.openhab.persistence.dynamodb.test/testReport/org.openhab.persistence.dynamodb.internal/AbstractDynamoDBItemSerializationTest/testDecimalTypeWithNumberItem/
cc @kaikreuzer 
Did not fail with all platforms (for example could reproduce locally).
```
org.openhab.persistence.dynamodb.internal.AbstractDynamoDBItemSerializationTest.testDecimalTypeWithNumberItem
Failing for the past 3 builds (Since Unstable#1698 )
Took 3 ms.
Error Message
Expected state 3.2 (3.2 but with some digits lost) did not match actual state 3.2000000000000001776356839400250464678
Stacktrace
java.lang.AssertionError: Expected state 3.2 (3.2 but with some digits lost) did not match actual state …
```
=> [dynamodb] Fix test failure

pom.xml
Needed to fix error with current Git version:
```
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.7.3:perform-tycho (default-cli) on project pom-addons1: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.7.3:perform-tycho failed: Unable to add local changes to the index. At least one pattern is required.
```
=> Update unleash plugin version

bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/AbstractCULHandler.java
Currently the CUL sending thread will produce a timeout of 2s if a command is sent that will not provide a response. This is the case when sending a FS20 message ("F" prefix). The major purpose of this PR is to provide a generic solution for such commands and only fix the problem for the FS20 protocol as there is no other equipment for testing available.
Additional Minor changes and refactorings:
- Use a queue that is blocking instead of polling in a busy loop
- Use monitors / synchronized methods to wait for a response instead of using a boolean local member
=> Fix CUL 2s blocking problem after sending FS20 message

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/UDPBinding.java
Transfer the functionality of [TCPBinding.java](https://github.com/lewie/openhab/blob/master/bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/TCPBinding.java#L210) also to UDPBinding.java 
Using UDP, postamble=\r was sent as UTF-8 instead as ASCII:
> Receved: str\\u000d	-> HEX:  73 74 72 5C 75 30 30 30 64
Now, it will be sent as ASCII:
> Receved: str\r	 	 	 -> HEX:  73 74 72 0D
Signed-off-by: lewie <helmut.lehmeyer@gmail.com>
=> [TCP1] Unescape UDP preAmble and postAmple like for TCP

bundles/binding/org.openhab.binding.serial/README.md
Added info for Linux permissions on systemd based system, where /etc/default/openhab2 should be modified.
=> added systemd permission info

bundles/binding/org.openhab.binding.davis/README.md, bundles/binding/org.openhab.binding.davis/src/main/java/org/openhab/binding/davis/datatypes/DavisCommandType.java, bundles/binding/org.openhab.binding.davis/src/main/java/org/openhab/binding/davis/datatypes/DavisValueType.java, bundles/binding/org.openhab.binding.davis/src/main/java/org/openhab/binding/davis/internal/DavisBinding.java
Hi,
I just made a push of my work. This bundle is working fine for about 2 weeks in my openhab2 installation.
Goal of this enhancement is to communicate by IP (new) or SERIAL (existing) with Davis weather station. The protocol remains the same.
Best regards
=> [Davis] Enable IP communication with davis weather station

features/openhab-addons-legacy/src/main/feature/feature.xml, features/openhab-addons/src/main/feature/feature.xml
openhab2 has a pushbullet binding.
~~Depends on https://github.com/openhab/openhab2-addons/pull/5668 .~~ 
PR has been merged into OH2 HEAD
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
=> [pushbullet] move action to legacy

bundles/binding/org.openhab.binding.mcp23017/README.md
The address in the first example is 0x21, but the explenation under it statet the address as 0x20. The second example shows the right way
=> Typo lead to confusing instructions

bundles/binding/org.openhab.binding.networkupstools/README.md
- Fixing a minor TYPO
- Adding that no `things` file configuration required
Signed-off-by: Soren Thorsen <st@debian-linux.dk>
=> Fixing a minor TYPO and thing info

.travis.yml
On newer Maven versions the reactor summary also contains the project name and version so the regexp needs to be adjusted for this.
Also make sure grep treats binary data as text (-aE switch) so the pipe doesn't choke on this.
=> Fix empty reactor summary on newer Maven versions

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
This is workaround for failed test in timezone different then utc.
=> [KNX.Test] workaround for timezone in KNXCoreTypeMapperTest

bundles/binding/org.openhab.binding.caldav-personal/README.md
Escaping special characters in URLs allows usage of calendar-ids with special characters, e.g. private-home --> private%2Dhome
=> Fixed restriction on special characters in URLs

bundles/binding/org.openhab.binding.novelanheatpump/README.md, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/HeatpumpCommandType.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/Messages.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/messages.properties, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/i18n/messages_de.properties, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java, bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpGenericBindingProvider.java
All currently known output signals were added as Switch items (prefix `output_`), together with `simple_state_num`, `switchoff_reason_0` and `switchoff_code_0` to allow better rule-based error management.
Both extended and regular state strings now can translate more heatpump states.
I also added a workaround for the calculation of the thermal energies because (probably due to a sign bug in the firmware) the energies might be unreasonably large.
=> Novelan heatpump: Add output signals and additional state variables as items, add missing heatpump states

bundles/binding/org.openhab.binding.swegonventilation/README.md, bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/SwegonVentilationBinding.java, bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/protocol/SwegonVentilationDataParser.java
Swegon device can send messages at a high speed (e.g. every second) which can cause lot of item updates. Added throttle feature which can be used to skip some incoming messages. 
=> [swegon] Added throttle support

bundles/binding/org.openhab.binding.openenergymonitor/README.md, bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/internal/OpenEnergyMonitorBinding.java, bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/protocol/OpenEnergyMonitorDataParser.java
Open energy monitor devices can send messages at a high speed (e.g. every second) which can cause lot of item updates. Added throttle feature which can be used to skip some incoming messages. 
=> [oem] throttle support

bundles/io/org.openhab.io.gpio/src/main/java/org/openhab/io/gpio/linux/GPIOPinLinux.java
* Fixes GPIO Binding Item state out of sync even with debounce set.
Fixes #5729
Signed-off-by: Ingo Schuck <ingo.schuck@oktett-8.de> (github: oktett-8)
=> [GPIO] Fixes debounce Item state out of sync (#5729)

bundles/binding/org.openhab.binding.diyonxbee/README.md
=> [Diyonxbee] Formatting changes for README

bundles/binding/org.openhab.binding.caldav-command/README.md
changed pre to ``` for better readability on openhab.org
=> [CalDAV-Command] Readability enhancements for README

bundles/binding/org.openhab.binding.cups/README.md
Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
Additionally changed pre to ``` for better readability on openhab.org
=> [Cups] Update README with better sendCommand alternative

bundles/binding/org.openhab.binding.snmp/README.md
according to https://github.com/openhab/openhab1-addons/issues/2426, the binding supports at least also version v2c. I tested it to make a COUNTER64 OID work (https://community.openhab.org/t/synology-disk-usage-and-snmp-binding/65869)
I wasn't able to test SET
=> [SNMP] Update README.md for the version property

bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/Connection.java, bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBinding.java
Don't start the polling loop if login fails.
Add a message for login failure.
Also prevent obvious opportunities for null pointer exceptions.
Fixes #5924
=> [Garadget] Fix NullPointerException.

bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
Updated the logic in the getCacheData() method so that the cached URL is handled properly as a dynamic URL (i.e. the date parameters are honored).
Fixes #5929 and replaces/obsoletes #5928.
Also added a little additional debug output (TRACE calls).
Signed-off-by: 9037568 <namraccr@gmail.com>
=> [HTTP binding] Fix URL translation for #5929

bundles/persistence/org.openhab.persistence.rrd4j/README.md, features/openhab-addons-external/src/main/resources/conf/rrd4j.cfg
When I tried to set up rrd4j persistence on my own system, I found the `rrd4j` `ReadMe.md` documentation in general very hard to understand, and in particular missing some specific information.
Very kindly @JueBag helped me to solve it -- thank you!
So, based on our common learning, this PR contains improvements and extensions to the `ReadMe.md` file (it also contains a small change in the `.cfg` sample file in which the parameter names have been changed to match the documentation).
=> [rrd4j] improvements and extensions to documentation

bundles/binding/org.openhab.binding.diyonxbee/NOTICE
See https://github.com/andrewrapp/xbee-api/blob/master/COPYING
=> The xbee license is actual a GPL not LGPL

README.md
Maybe it would be good idea to have badges showing the maintainance status of our repositories at a glance. https://www.repostatus.org/ offers such badges. If you think this is a good idea, I'd create PRs for all repos.
=> Add inactive badge
