openhab/openhab1-addons

bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunCalc.java
bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunZodiacCalc.java
bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java

see https://github.com/openhab/openhab/issues/1908 and https://github.com/openhab/openhab/issues/1800

Astro: Optimized capricorn zodiac and fixed isSunUpAllDay calculation

---

bundles/core/org.openhab.core.transform/src/main/java/org/openhab/core/transform/internal/service/JSonPathTransformationService.java

This fix allows to transform other than string values using JSONPath.

transform: JSONPath support for non-string values.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_wallcs.xml

https://github.com/openhab/openhab/issues/1925

Add zwave.me secure wall controller

---

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoGenericBindingProvider.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoMeasureType.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/DeviceListResponse.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/MeasurementRequest.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/MeasurementResponse.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/RefreshTokenRequest.java

Update of the netatmo binding to handle timestamp of values for every Netatmo Module (feature request #1892)

---

bundles/action/org.openhab.action.weather/src/main/resources/readme.txt
bundles/binding/org.openhab.binding.lgtv/.project
bundles/binding/org.openhab.binding.pilight/.project
bundles/binding/org.openhab.binding.s300th.test/.project
bundles/binding/org.openhab.binding.samsungac.test/.project
bundles/binding/org.openhab.binding.samsungac/.project

This should fix all errors described in #1801 as well as in https://groups.google.com/d/topic/openhab/2q7bwocAubE/discussion
Fixes #1801

Fix various errors in eclipse IDE

---

bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/bus/BindingConfigParser.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/Event.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicCommunicator.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicPublisher.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/config/binding/DatapointConfig.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/config/binding/ValueBindingConfig.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/config/binding/VariableConfig.java

Docs: https://github.com/openhab/openhab/wiki/Homematic-Binding#delay

Homematic: Added delayed sending of commands

---

bundles/core/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java

what a time lost to identify those two small forgotten serviceName :)

Correction of bug identified on deltaSince and evolutionRate

---

bundles/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickBinding.java

Fix issue with events with same value was ignored and a fixed max_idle issue

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhba.xml

parameter 30 was not saved when setting to 1

Zwave: update zmnhba.xml

---

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

Bugfix PR for issue https://github.com/openhab/openhab/issues/1879
Regards,
Theo

Influxdb persistence Bugfix for #1879

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/rtc/ct100.xml
bundles/binding/org.openhab.binding.zwave/database/rtc/ct30.xml

https://github.com/openhab/openhab/issues/1883

Update CT30/CT100 association groups

---

bundles/action/org.openhab.action.astro/.classpath
bundles/action/org.openhab.action.astro/.project
bundles/action/org.openhab.action.astro/META-INF/MANIFEST.MF
bundles/action/org.openhab.action.astro/OSGI-INF/action.xml
bundles/action/org.openhab.action.astro/build.properties
bundles/action/org.openhab.action.astro/pom.xml
bundles/action/org.openhab.action.astro/src/main/java/org/openhab/action/astro/internal/Astro.java
bundles/action/org.openhab.action.astro/src/main/java/org/openhab/action/astro/internal/AstroActionService.java
bundles/action/org.openhab.action.astro/src/main/java/org/openhab/action/astro/internal/AstroActivator.java
bundles/action/org.openhab.action.astro/src/main/java/org/openhab/action/astro/internal/AstroConfig.java
bundles/action/org.openhab.action.astro/src/main/resources/readme.txt
bundles/action/pom.xml
bundles/binding/org.openhab.binding.astro/META-INF/MANIFEST.MF
distribution/pom.xml
features/org.openhab.designer.feature/feature.xml

Requested: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/openhab/ewdZbOr7dSQ
Currently only sunrise and sunset implemented, more on demand.
Usage:
```
var Date current = now.toDate
var double lat = xx.xxxxxx
var double lon = xx.xxxxxx
var DateTimeType sunriseStart = new DateTimeType(getAstroSunriseStart(current, lat, lon))
var DateTimeType sunriseEnd = new DateTimeType(getAstroSunriseEnd(current, lat, lon))
var DateTimeType sunsetStart = new DateTimeType(getAstroSunsetStart(current, lat, lon))
var DateTimeType sunsetEnd = new DateTimeType(getAstroSunsetEnd(current, lat, lon))
```

Initial contribution of Astro-Action.

---

bundles/binding/org.openhab.binding.zwave/database/everspring/hsp02.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/198

Add everspring HSP02

---

bundles/action/org.openhab.action.xmpp/src/main/java/org/openhab/action/xmpp/internal/XMPPConsole.java
bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/FritzboxBindingProvider.java
bundles/binding/org.openhab.binding.fritzbox/src/main/java/org/openhab/binding/fritzbox/internal/FritzboxBinding.java

This should fix https://github.com/openhab/openhab/issues/1923 
I have tested it with my Fritz!Box 7270 and it works as expected.
There is no feedback on the linked issue https://github.com/openhab/openhab/pull/1971 and my Fritz!Box does not have a second AP, so unfortunately I cannot test this issue.

Adding guest wlan to fritzbox binding

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/SerialMessage.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCRC16EncapsulationCommandClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java

added crc 16 encapsulation 0x56 command class

crc 16 encapsulation

---

bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/MaxCubeBinding.java

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>
Addressing issue  #1983

Improve handling of network and timing disruptions in maxcube binding

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Sorry for this, files got mixed up during staging

Updated the products.xml with new filename SW-ZCS-1.xml

---

bundles/binding/org.openhab.binding.zwave/database/everspring/se812.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

just to update the database with the SE812 classes and association group

Add Everspring SE812 config file 

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBusReaderScheduler.java

Bug fix for #2097. Changes: modified iteration over list when removing items.

Bug fix for #2097

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBusReaderScheduler.java

Bug fix for #2097. Changes: modified iteration over list when removing items.

Bug fix for #2097 (master)

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgfs101.xml

Fibaro Flood Sensor:
- add parameters
- little rewording

fgfs101 Add Parameters

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgss101.xml

Change Maximum from 1000 to 100
Change Default from 50 to 20
Change Size from 2 to 1

Change Parameter Settings of Parameter 12

---

bundles/binding/org.openhab.binding.zwave/database/evolve/ltm-5.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added manufacturer Evolve and LTM-5 Accessory switch to z-wave product database.

Add Evolve LTM-5 accessory switch to products database.

---

bundles/binding/org.openhab.binding.zwave/database/intermatic/ha20.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add intermatic HA20 Dimmer

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBusReaderScheduler.java

Eliminated false error message. Improved log output.

Bug fix for #2064: eliminated false error message

---

bundles/binding/org.openhab.binding.zwave/database/aeon/keyfobg1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/221

Add Aeon keyfob

---

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelBinding.java
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConfigReader.java
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConnectorThread.java
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java

The binding did not properly handle communication with multiple devices (messages from one device could have been handled by a listener for another device).

Communication fixed for multiple devices.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2230

Add RTC CT80

---

bundles/binding/org.openhab.binding.zwave/database/vision/zp3102.xml

I just saw that the parameter is in minutes, not in seconds...

Change Indication from sec to minutes.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2241

Update reference for Aeon G5 key fob

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2225

Update database codes for Everspring SM103 / HSM02

---

bundles/binding/org.openhab.binding.zwave/database/aeon/4in1ms_g5.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2220

Add Aeon 4in1 G5

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2230

Add RTC 3M-30 and confirmation parameters for CT80

---

bundles/binding/org.openhab.binding.zwave/database/aeon/smart_strip.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/225

Aeon SmartStrip product addition

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2225

Update code for Everspring SM103

---

bundles/binding/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/handling/ComfoAirCommandType.java

- Fix EWT low/high temperature values
- Add EWT active state
- Minor typos fixed

Comfoair: EWT bugfixes / enhancements

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java

Protect against a null dereference when looking up associations for devices that don't support it.

Null dereference checks. Indentation fixes.

---

bundles/binding/org.openhab.binding.zwave/database/linear/lb60z-1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

I couldn't find this devices in the database in the binding, nor in the http://www.pepper1.net/zwavedb/ database.
Information about the device is gathered from http://www.linearcorp.com/product_detail.php?productId=1756

Added Linear LB60Z-1 to the database

---

bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/EcoTouchBindingProvider.java
bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/EcoTouchTags.java
bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchBinding.java
bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchConnector.java
bundles/binding/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchGenericBindingProvider.java
bundles/model/org.openhab.model.sitemap/src/org/openhab/model/Sitemap.xtext

This PR adds write support and new tags.
To let the user specify a negative adaption value for heating (-2.0K .. +2.0K) the grammar sitemap.xtext is extended.

Write-Support for EcoTouch binding

---

bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/MonitorSessionThread.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoDevice.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoGenericBindingProvider.java

Add termuregulation temperature reading from bus

Add termuregulation temperature reading from bus

---

bundles/persistence/org.openhab.persistence.db4o/src/main/java/org/openhab/persistence/db4o/internal/Db4oPersistenceService.java
distribution/src/deb/Readme.txt
distribution/src/deb/bin/openhab.sh
distribution/src/deb/etc/init.d/openhab

rename openhab.userdata to smarthome.userdata. more: #2300

rename openhab.userdata to smarthome.userdata

---

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelGenericBindingProvider.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/command/SatelCommand.java

This PR contains minor fixes in error messages (wrong placeholder used in *String.format*).

[satel] Fixes in error messages

---

bundles/binding/org.openhab.binding.mios/README.md
bundles/binding/org.openhab.binding.mios/examples/transform/miosShutterCommand.map
bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceBindingConfig.java
bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/DeviceDefaults.properties
bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/config/MiosBindingConfig.java

Added Roller shutter functionality to the MIOS binding

Added Roller shutter functionality

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgsd002.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zp3102.xml

the new version of the FGSS-001, available in france from now.

Add new fibaro smoke detector FGSD-002

---

bundles/binding/org.openhab.binding.alarmdecoder/.classpath
bundles/binding/org.openhab.binding.comfoair/.classpath
bundles/binding/org.openhab.binding.davis/.classpath
bundles/binding/org.openhab.binding.ehealth/.classpath
bundles/binding/org.openhab.binding.enocean/.classpath
bundles/binding/org.openhab.binding.epsonprojector/.classpath
bundles/binding/org.openhab.binding.iec6205621meter/.classpath
bundles/binding/org.openhab.binding.insteonplm/.classpath
bundles/binding/org.openhab.binding.knx/.classpath
bundles/binding/org.openhab.binding.modbus/.classpath
bundles/binding/org.openhab.binding.nikobus/.classpath
bundles/binding/org.openhab.binding.oceanic/.classpath
bundles/binding/org.openhab.binding.openenergymonitor/.classpath
bundles/binding/org.openhab.binding.plcbus/.classpath
bundles/binding/org.openhab.binding.plugwise/.classpath
bundles/binding/org.openhab.binding.rfxcom/.classpath
bundles/binding/org.openhab.binding.rme/.classpath
bundles/binding/org.openhab.binding.serial/.classpath
bundles/binding/org.openhab.binding.swegonventilation/.classpath
bundles/binding/org.openhab.binding.urtsi/.classpath
bundles/binding/org.openhab.binding.wago/.classpath
bundles/binding/org.openhab.binding.zwave/.classpath
bundles/io/org.openhab.io.transport.cul/.classpath
bundles/io/org.openhab.io.transport.serial/.classpath

fix eclipse project classpaths due to nrjavaserial update

---

bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ASCIIInputStream.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusASCIITransport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusBINTransport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusSerialTransaction.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusSerialTransport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/ModbusSerialListener.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/ModbusTCPListener.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/ModbusUDPListener.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/SerialConnection.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPConnectionHandler.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPSlaveConnection.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/UDPMasterTerminal.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/UDPSlaveTerminal.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/util/BitVector.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/util/SerialParameterValidator.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/util/SerialParameters.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/util/ThreadPool.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusGenericBindingProvider.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSerialSlave.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTcpSlave.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusUdpSlave.java

replaced System.out debug printouts through appropriate slf4j logging (as mentioned in https://github.com/openhab/openhab/pull/2056#discussion_r24003386).
Added data validation for future improvements of faulty openhab.config parameter feedback.

Cleaning up the modbus binding

---

bundles/binding/org.openhab.binding.mochadx10/.classpath
bundles/binding/org.openhab.binding.mochadx10/.project
bundles/binding/org.openhab.binding.mochadx10/.settings/org.eclipse.jdt.core.prefs
bundles/binding/org.openhab.binding.mochadx10/.settings/org.maven.ide.eclipse.prefs
bundles/binding/org.openhab.binding.mochadx10/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.mochadx10/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.mochadx10/OSGI-INF/mochadx10binding.xml
bundles/binding/org.openhab.binding.mochadx10/build.properties
bundles/binding/org.openhab.binding.mochadx10/pom.xml
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/MochadX10BindingProvider.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10Activator.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10Binding.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10BindingConfig.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10GenericBindingProvider.java
bundles/binding/org.openhab.binding.mochadx10/src/main/resources/readme.txt
distribution/openhabhome/configurations/openhab_default.cfg

First version of a binding to control X10 devices with a CM15Pro controller using a Mochad X10 server (http://sourceforge.net/projects/mochad/).

Create Mochad X10 Binding

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgsd002.xml

Hello, There were some syntax errors in the file fgsd002.xml

Fix syntax issues in fgsd002.xml

---

bundles/binding/org.openhab.binding.mios/src/main/java/org/openhab/binding/mios/internal/MiosUnitConnector.java

When a MiOS Unit is called, as a result of a Command, these calls can fail.  When they do, we need better diagnostics as to when/if it's failing, so we can work out why.
Sometimes, this is just because the configurable Transformations have been incorrectly setup, but we'd fail silently which made it hard to debug in the field.

MiOS - Improve diagnostics for failed HTTP requests to MiOS Unit.

---

bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/Mail.java

https://github.com/openhab/openhab/issues/771#issuecomment-34875578

multiple recipients to sendMail is added

---

bundles/binding/org.openhab.binding.zwave/database/brk/zsmoke.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

No information can be found on this device so the assumption is it is the same as the ZCOMBO from the same manufacturer

Add BRK ZSMOKE

---

bundles/model/org.openhab.model.sitemap/src/org/openhab/model/Sitemap.xtext

Signed-off-by: Kai Kreuzer <kai@openhab.org> (github: @kaikreuzer)

allow negative values for setpoint widget ranges

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

updated zwave binding products.xml

Add new reference for Vision ZD2101

---

bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/Mail.java
bundles/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoGenericBindingProvider.java

Changes to fix issue #2392, resolving contradictory if statement, and fixing a minor typographical error.

Fix for issue #2392 (catch 22 if statement)

---

bundles/binding/org.openhab.binding.mochadx10/pom.xml
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10Address.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10BrightCommand.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10Command.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10DimCommand.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10OffCommand.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/commands/MochadX10OnCommand.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10Binding.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10BindingConfig.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10CommandParser.java
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10GenericBindingProvider.java
bundles/binding/org.openhab.binding.mochadx10/src/simulator/java/org/openhab/binding/mochadx10/simulator/MochadX10Simulator.java
bundles/binding/org.openhab.binding.mochadx10/src/simulator/java/org/openhab/binding/mochadx10/simulator/MochadX10SimulatorMain.java

Added receive thread to also respond to messages received by the Mochad X10 host.
Added a simulator for the Mochad X10 host. With the simulator, a.o. connection issues can be debugged more easily.
This pull request replaces pull request #2377.

Added receive thread and mochad X10 simulator

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/CommandHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/PollHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

Adding support for Insteon Thermostat 2441TH to insteonplm binding

Insteonplm Thermostat 2441TH

---

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java

This PR adds support for rollershutter items and introduces some other minor changes in the code.

[satel] Basic support for rollershutter items added

---

bundles/core/org.openhab.core.library.test/src/test/java/org/openhab/core/library/types/LocationItemTest.java
bundles/core/org.openhab.core.library/META-INF/MANIFEST.MF
bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/CoreItemFactory.java
bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/LocationItem.java
bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/PointType.java
bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/resources/SitemapResource.java
bundles/model/org.openhab.model.item.ui/src/org/openhab/model/ui/contentassist/ItemsProposalProvider.java
bundles/model/org.openhab.model.item/src/org/openhab/model/Items.xtext
bundles/model/org.openhab.model.sitemap/src/org/openhab/model/Sitemap.xtext
bundles/ui/org.openhab.ui.webapp/META-INF/MANIFEST.MF
bundles/ui/org.openhab.ui.webapp/OSGI-INF/mapviewrenderer.xml
bundles/ui/org.openhab.ui.webapp/snippets/mapview.html
bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/MapviewRenderer.java
bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/items/ItemUIRegistryImpl.java
bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/proxy/ProxyServlet.java
features/org.openhab.designer.feature/feature.xml

Converted PointType logic to BigDecimal as in smarthome instead of double.
Added a GUI introducing Mapview widget in sitemaps.
The mapview is currently based on OpenStreetMaps, could be changed by any javascript guru (that I'm not) to have something nicer

Introducing PointType and LocationItem - Round 2

---

bundles/binding/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/SnmpBindingProvider.java
bundles/binding/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpBinding.java
bundles/binding/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpGenericBindingProvider.java

This PR enhances the SNMP binding as requested in issue #2426.

Enhance SNMP binding (Issue #2426)

---

bundles/binding/org.openhab.binding.zwave/database/aeon/dsd31.xml

https://github.com/openhab/openhab/issues/2082

Fix database error in Aeon DSD31

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Add reference for Philio PST-02 e
Door-Temperature-Luminance version

Update zwave database

---

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/connector/EpsonProjectorSerialConnector.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java

Added workaround for both rfxcom and epson projector bindings, which decrease CPU consumption.
Related to issue: https://github.com/NeuronRobotics/nrjavaserial/issues/22

Decrease CPU consumption caused by nrjavaserial library

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConfigurationConverter.java

Fixes https://github.com/openhab/openhab/issues/2082

Fix configuration converter bug getting parameter from database

---

bundles/binding/org.openhab.binding.zwave/database/aeon/dsb54.xml
bundles/binding/org.openhab.binding.zwave/database/philio/pan04_1b.xml
bundles/binding/org.openhab.binding.zwave/database/philio/pst02a.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/231

ZWave: Add New RPi entry

---

bundles/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBinding.java
bundles/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoCommandType.java

New commands introduced:
FileSystemUsed
FileSystemFree
FileSystemTotal
FileSystemUsagePercent
FileSystemFiles
FileSystemFreeFiles
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: )

System binding: added support to query file system statistics

---

bundles/binding/org.openhab.binding.zwave/database/linear/ws15z-1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/27

Add linear WS15-1

---

bundles/binding/org.openhab.binding.maxcube/src/main/java/org/openhab/binding/maxcube/internal/message/M_Message.java

I found the reason for the wron encoding as descriped here: https://github.com/openhab/openhab2/issues/191

Fixed encoding problem of room and device names.

---

bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java

Milight bugfix

---

bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/GenerateRules.mwe2
bundles/model/org.openhab.model.script/src/org/openhab/model/script/GenerateScript.mwe2

I messed up my fork's repo so I made clean new branch; this supüersedes  #2465; sorry for the inconvenience
regards
Gernot

fix for Issue #2460: removed references to non-existent tests from generators

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java

removed errorneous return in message processing method

Fix issue #2467

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WorldWeatherOnlineProvider.java

... for provider WorldWeatherOnline

WeatherBinding: Use of API v2 and support of uvIndex and dewpoint

---

bundles/io/org.openhab.io.transport.cul.test/.classpath
bundles/io/org.openhab.io.transport.cul.test/.project
bundles/io/org.openhab.io.transport.cul.test/.settings/org.eclipse.jdt.core.prefs
bundles/io/org.openhab.io.transport.cul.test/.settings/org.maven.ide.eclipse.prefs
bundles/io/org.openhab.io.transport.cul.test/CULConstructorsTest.launch
bundles/io/org.openhab.io.transport.cul.test/META-INF/MANIFEST.MF
bundles/io/org.openhab.io.transport.cul.test/build.properties
bundles/io/org.openhab.io.transport.cul.test/pom.xml
bundles/io/org.openhab.io.transport.cul.test/src/test/java/org/openhab/io/transport/cul/CulConstructorsTest.java
bundles/io/org.openhab.io.transport.cul.test/src/test/resources/Readme.md
bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULSerialHandlerImpl.java

added unittests
fixed bug (unreported, found by said unittests): parity is not correctly handled in arePropertiesEqual()

fixed bug #2428 for serial w/o new baudrate/parity settings

---

bundles/binding/org.openhab.binding.zwave/database/philio/pan04_1b.xml

https://github.com/cdjackson/HABmin/issues/232

Update philio pan04 1b

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgs222.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/234

Add Fibaro FGS222

---

bundles/binding/org.openhab.binding.zwave/database/fortrezz/wwa02.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2488

Add Fortress WWA02

---

bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java

Helps finding out what the problem is reported here: https://groups.google.com/forum/#!topic/openhab/8IoRQezSIEQ

fix-logging-for-failed-to-create-db-table

---

bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBinding.java
bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightGenericBindingProvider.java
bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/communication/DeviceType.java
bundles/binding/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/types/PilightContactType.java

This pull request adds support for Contact items to the pilight v6 binding. Please merge #2446 first.
[Updated wiki](https://github.com/idserda/openhab/wiki/pilight-Binding)
@SJoWie80 Could you also test this new functionality? Thanks!

Support for Contact items in pilight binding

---

bundles/action/org.openhab.action.squeezebox/src/main/java/org/openhab/action/squeezebox/internal/Squeezebox.java
bundles/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeboxBinding.java
bundles/io/org.openhab.io.squeezeserver/src/main/java/org/openhab/io/squeezeserver/SqueezeServer.java

i.e. if connection to server is lost

Fix so Squeezebox actions automatically reconnects

---

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBinding.java
bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConfig.java
bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/data/HueSettings.java
bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBulb.java

This makes the device ids of type String as in the Hue SDK and the ESH.

Refactor HUE int deviceNumber to String deviceId

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMeterConverter.java

fixed log statement which crashed the build

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConfigurationConverter.java

Fixes https://github.com/openhab/openhab/issues/2082

Change converter so parameter references can start at 0 (to 255)

---

distribution/openhabhome/configurations/rules/demo.rules

fixes #2556 - Syntax error in demo.rules

---

bundles/ui/org.openhab.ui.webapp/snippets/main.html

Update Classic UI footer

---

distribution/openhabhome/configurations/logback.xml

Fixes logging issue from #2555

Adjust log level for DefaultAnnotationProcessor

---

bundles/binding/org.openhab.binding.zwave/database/aeon/hem.xml

index for group 3 is 103, not 101 (which is group 1)

Small error in the Aeon HEM Z-Wave database

---

distribution/pom.xml

Fix for duplicate dependency #2593.

Fix duplicate dependency (#2593)

---

distribution/src/assemble/addons.xml

Signed-off-by: Dan Cunningham dan@digitaldan.com

Adds the harmonyhub io package to the addons dist. Closes #2558

---

bundles/binding/org.openhab.binding.zwave/database/aeon/dsb54-gen5.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/38

Add Aeon recessed door sensor (Gen5)

---

bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/PointType.java

CherryPicked from https://github.com/eclipse/smarthome/pull/301

Fixed toString in PointType

---

bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBinding.java

Sonos: reduced log level for discovered non Sonos devices.

---

bundles/binding/org.openhab.binding.systeminfo.test/.project

fixed .project name of systeminfo.test bundle

---

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

Reported as working by Jim Howard on 3/12/2015.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab/FIg-KEqaPDQ/qktZLJOjc0wJ

InsteonPLM: added 2475 SDB In-LineLinc Relay

---

bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/items/ItemUIRegistryImpl.java

and fixed warning in getState error logging.

ItemUIRegistry: Improved getLabel error logging

---

bundles/binding/org.openhab.binding.enocean/.classpath

Missing update in classpath for opencean

---

bundles/binding/org.openhab.binding.zwave/database/devolo/mt02646.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add devolo Home Control Metering Plug

Add devolo Home Control Metering Plug

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBindingDatapointReaderTask.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/connection/KNXConnection.java
distribution/openhabhome/configurations/openhab_default.cfg

https://github.com/openhab/openhab/issues/2508

 One KNX command causes two busevents

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/42

Add new code for Aeon Gen5 ZStick

---

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

Continued from https://github.com/openhab/openhab/pull/2519
Hopefully this time I've done it right.

2502 - fix for NumberFormatException

---

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

Influxdb: fix regression for DateTimeTyp conversion; fix type handling for HistoricState

Influxdb: fix regression for DateTimeTyp conversion; fix type handling HistoricState

---

bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcAuthenticationService.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcControllerService.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcHttpsClient.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcResourceInteractionService.java

IHC binding: improved timeout handling

---

bundles/binding/org.openhab.binding.hms/.classpath
bundles/binding/org.openhab.binding.hms/.project
bundles/binding/org.openhab.binding.hms/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.hms/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.hms/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.hms/build.properties
bundles/binding/org.openhab.binding.hms/pom.xml
bundles/binding/org.openhab.binding.hms/src/main/java/org/openhab/binding/hms/HMSBindingProvider.java
bundles/binding/org.openhab.binding.hms/src/main/java/org/openhab/binding/hms/internal/HMSActivator.java
bundles/binding/org.openhab.binding.hms/src/main/java/org/openhab/binding/hms/internal/HMSBinding.java
bundles/binding/org.openhab.binding.hms/src/main/java/org/openhab/binding/hms/internal/HMSGenericBindingProvider.java
bundles/binding/org.openhab.binding.hms/src/main/resources/readme.txt
bundles/binding/pom.xml
distribution/pom.xml

Hi openhab team,
this is my first own binding and I'd like to share it with the community. I'm totally new to git, so I hope my pull request is OK? What else do I have to do? What about a WIKI page and an config guide?
Thanks so far,
Tom

new HMS binding

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConfigurationConverter.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ConfigurationParameter.java

Update debug logging for configuration converter

---

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBinding.java

Rfxcom: received command logging changed from info to debug level

---

bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_05461.xml

ZWave.me ZME_05461 double switch device file

zme_05461.xml

---

bundles/binding/org.openhab.binding.zwave/database/leviton/vri10-1lz.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Also reformed the products file
https://github.com/openhab/openhab/issues/2694

Add Leviton VRI10-1LZ zwave device

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2536

Add product reference for zwave.me switch

---

bundles/binding/org.openhab.binding.maxcul/src/main/java/org/openhab/binding/maxcul/internal/message/sequencers/PairingInitialisationSequence.java

Just a quick tidy up I had hanging round in my local workspace.

[MAX!Cul] Ensure that associations isn't null before checking if it is empty.

---

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
distribution/openhabhome/configurations/openhab_default.cfg

Lengthened default polling to three minutes to conform to API documentation.

[Ecobee] Changed default polling to 3 minutes; added binding example.

---

bundles/binding/org.openhab.binding.zwave/database/aeon/smart_strip.xml
bundles/binding/org.openhab.binding.zwave/database/leviton/vri10-1lz.xml
bundles/binding/org.openhab.binding.zwave/database/leviton/vrs15-1lz.xml
bundles/binding/org.openhab.binding.zwave/database/northq/nq9121.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/238

Update Aeon Smart Strip to add endpoints 5 and 6

---

bundles/binding/org.openhab.binding.zwave/database/philio/pan06_1a.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/52

Add Philio PAN06-1A

---

bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/CcuClient.java
distribution/openhabhome/configurations/openhab_default.cfg

This is the same as https://github.com/openhab/openhab/pull/2703
I did a complete new checkout and now everything works. Please delete the previous PR.

Homematic: Configurable connection timeout for CcuClient #2

---

bundles/binding/org.openhab.binding.zwave/database/act/zrm230.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/56
https://github.com/openhab/openhab/issues/2727

Add ZRM230

---

bundles/binding/org.openhab.binding.zwave/database/aeon/siren.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

cdjackson/HABmin#241
cdjackson/HABmin#239

Zwave database updates

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Signed-off-by: Dan Cunningham dan@digitaldan.com

adds an additional entry for the GE/Jasco outdoor module

---

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java

Log to debug on connection errors in Plex binding	

---

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

Fix NPE when only using default config in RRD persistence service

---

bundles/binding/org.openhab.binding.zwave/database/northq/nq9021.xml

- Added missing parameters
- Updated misleading descriptions
- corrected defaults and range.

Fixed NorthQ NQ-9021 database.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zs6301.xml

https://github.com/cdjackson/HABmin/issues/242

Add Vision ZS6301 CO Detector

---

bundles/binding/org.openhab.binding.zwave/database/leviton/vrpd3-1lw.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

There doesn't seem to be any information about the command classes this module supports anywhere, so I just copied it from one of the existing leviton dimmers.

Added Leviton VRPD3-1LW plug-in dimmer

---

bundles/model/org.openhab.model.item/pom.xml
bundles/model/org.openhab.model.persistence/pom.xml
bundles/model/org.openhab.model.rule/pom.xml
bundles/model/org.openhab.model.script/pom.xml
bundles/model/org.openhab.model.sitemap/pom.xml
pom.xml

updated fornax mwe plugin to 3.5.1 and removed deprecated itemis repo

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMActiveBinding.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/ModemDBBuilder.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Driver.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/driver/Port.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/message/MsgFactory.java

- retry modem database download if it fails
- much improved handling of corrupt data packets as received from the
InsteonHub raw port
- discard spurious messages for the insteon thermostat to avoid
outlier temperature and humidity values

bug fixes to make insteonplm binding more robust

---

bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/SonosCommandType.java
bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBinding.java
bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosEntry.java
bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosResourceMetaData.java
bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
bundles/binding/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosZonePlayer.java

Signed-off-by: Dan Cunningham dan@digitaldan.com

SONOS Favorite support.

---

bundles/core/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java

adds solution for second part of #2599 (deltaSince with rrd4j counter db)

add new feature sumSince to persistence extensions

---

bundles/binding/org.openhab.binding.zwave/database/ge/ZW4005.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added  GE ZW4005 to database and updated products.xml

Add GE Device ZW4005

---

bundles/binding/org.openhab.binding.zwave/database/linear/wadwaz-1.xml

Removed non applicable configuration parameters and association groups.

Linear  WADWAZ-1 Fix

---

bundles/binding/org.openhab.binding.heatmiser/src/main/java/org/openhab/binding/heatmiser/internal/thermostat/HeatmiserPRT.java

Added suggested code referenced in Issue #2177  to handle remote sensor air temp.

Heatmiser update per Issue #2177

---

bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java

some Git Lessons Learned? :-)
Fix for this Issue: https://github.com/openhab/openhab/issues/2705

Mysql fix prepared statement for issue #2705

---

bundles/binding/org.openhab.binding.zwave/database/aeon/dsb06.xml

Added changes suggested by Hugo Donis to database file to correct errors
in group labels and  help text for Aeotec dbs06

Update Aeotec dbs06

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/tkb/tz78.xml

Added per request reference Issue #2745 
There is little to no information available on this device. This is a
best guess configuration based on what is available. Please test and
report back!

Added Zwave Device TKB T78

---

bundles/binding/org.openhab.binding.zwave/database/aeon/smart_strip.xml

Implemented Hugo Donis' suggested changes to add report items, correct
index errors and defaults.

Update Aeotec Smart Strip

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/remotec/zts110.xml

Added Remotec ZTS-110 Thermostat

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Fix error in WS15Z

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgs212.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2851

Add Fibaro FGS212

---

bundles/binding/org.openhab.binding.zwave/database/popp/zweather.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added support for POPP Z Weather Device in response to Issue #2855

POPP Z Weather Added

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhla.xml

Chris, I am committing my work so far for your perusal. Its about 1/3rd
the way done but I thought I would commit in case you want to review the
progress thus far. This is in reference to Issue #2553

Qubino zmnhla binding in process.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zl7431.xml

Added Vision zl7431 per Issue #2817

Added Vision zl7431

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw096.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

First attempt at adding z-wave xml.  This one for the smart switch 6.  All feedback welcome.

Added Aeon Labs Smart Switch 6 (zw096)

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhcd.xml

New Pull with completed Qubino ZMNHCD files hopefully conflict free this time, per Issue #2817

Added Qubino ZMNHCD

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ConfigurationParameter.java

https://github.com/cdjackson/HABmin2/issues/51

Fix bug in config parameter to allow size=3

---

bundles/binding/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOBinding.java

New PR to remove the problem with #2735
Sorry for these trials and errors, i'm starting with github...

Add Log Info for GPIO binding

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zm1601v5.xml

Updated Database to include ZM1601 version 5 per Issue #2892

Added ZM1601 version 5

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Update codes for Aeon zstick gen5

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/widom/wps104.xml

Added Energy Driven Switch WPS104 per Issue #2881

Added WiDOM Energy Driven Switch

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgd211-21.xml

https://github.com/openhab/openhab/issues/2902

Add param 40 into FGD211 version 2.1-2.3

---

bundles/binding/org.openhab.binding.zwave/database/vision/zm1601v5.xml

Changed Parameters from 0 and 1 to 1 and 2 as suggested in Product Manual, per PR #2892

Edit Vision zm1601v5

---

bundles/binding/org.openhab.binding.zwave/database/widom/wps104.xml

Removed Help text from within Items and moved it into Parameter Help
Section. Per requested change from PR #2890

Edit  Widom WPS104

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveConfigurationCommandClass.java

https://github.com/openhab/openhab/issues/2905
https://github.com/openhab/openhab/issues/2892

Updated handling of configuration class with 0 size

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw100-a.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

added support for Aeon MultiSensor 6

---

bundles/binding/org.openhab.binding.zwave/database/popp/zweather.xml

Added missing configuration parameters not mentioned in Pepper Database. Ref PR #2855

Edit Popp Z - Weather

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Edited device type and id. Per Issue #2553

Edit  Qubino Flush PWM

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw098.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/248

Add Aeon LED bulb

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added POPP_NEW to products database with new Manufacturer ID 0169 per PR
#2915

Edit Popp Z Weather

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_05457.xml

Added device to database per Issue #2941

Added Zwaveme ZME_05457

---

bundles/binding/org.openhab.binding.zwave/database/aeon/Copy of 4in1ms_g6.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/249

Add Aeon 4 in 1 Gen 6

---

bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/cosem/CosemDate.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/messages/OBISMsgFactory.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/messages/OBISMsgType.java

- Parsing CosemDate can now handle multiple formats
- Fixed spelling error
- Fixed DSMR v2 compensated gas, cold, heating and water meter value
This pull request is proposed instead of pull request #2795

Fixed issues voor DSMR v2 and ACE4000 meters

---

bundles/binding/org.openhab.binding.zwave/database/aeon/4in1ms_g6.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/249

Update Aeon 4in1 parameters and product code

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Update MS codes

---

bundles/binding/org.openhab.binding.zwave/database/act/zir010.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added support for ACT ZIR010 motion sensor

Add ACT ZIR010 support

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/2958

Add Leviton  DZPD3

---

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

Added on/off module 2635-222

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
bundles/core/org.openhab.core.library.test/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/DateTimeType.java

Fixes #2945 and my solve some issues of #2508

removed usage of static SimpleDateFormatter

---

bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java

Fix for https://github.com/openhab/openhab/issues/2732
and Types extended

Fix for #2732 - Saving group as string? But datatype is double!?

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgd211-21.xml

#2978: ZWave: Fibaro Dimmer Missing Option for Parameter 14

Add Roller Blind switch option to Fibaro Dimmer parameter 14

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgd211-21.xml

#2986: Miscellaneous configuration parameter fixes for Fibaro dimmer

Miscellaneous configuration parameter fixes for Fibaro dimmer

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java

https://github.com/cdjackson/HABmin/issues/252

Change initialisation check to PC_CONTROLLER specific class

---

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

fix issue #2979 (wrong state logged if incompatible type stored in rrd)

---

bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/connection/EBusTCPConnector.java
bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/utils/EBusUtils.java

-Fix wrong interpreted broadcasts as "no answer" telegrams
-optimized tcp network settings

eBUS Bugfix Update for 1.7.1

---

distribution/src/deb/bintray-upload-debs.sh

@teichsta auto publishing should work but I could not test it.

bintray-upload-debs: add automatic publishing

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Changed spaces to the commonly used tabs ins this file.

Z-Wave product database formatting cleanup

---

bundles/binding/org.openhab.binding.zwave/database/aeon/dsb45-zwus.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added product to database per Issue #3001

Aeon DSB45-ZWUS

---

bundles/binding/org.openhab.binding.zwave/database/aeon/ses3.xml

Edited SES3 adding missing configuration parameters, correcting values,
editing help and formatting for portability into OH2

Zwave Database Cleanup Aeon SES3

---

bundles/binding/org.openhab.binding.zwave/database/aeon/ses3.xml

Re-Added CommandClasses per request.

Aeon Cleanup SES3

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw100-a.xml

Added parameter 7 but am awaiting feedback on other issues. I am
hesitant to remove what may appear to be superfluous parameters as
documentation does refer to some of those values. As for adding a
parameter to set 101 - 103 to default there are no values given in the
documentation for doing that. I will await feedback on affecting those
changes as well. ref Issue #3005

Edit Aeon Multi-Sensor 6

---

bundles/binding/org.openhab.binding.zwave/database/aeon/minimote.xml

Edited for readability and portability into OH2

Zwave Database Cleanup Aeon Minimote

---

bundles/binding/org.openhab.binding.zwave/database/aeon/doorsensor.xml

Edited for accuracy and portability into openhab2

Z-Wave Database Cleanup Aeon Door/Window Sensor

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added product reference for Vision ZD2102-5 per Issue #3018

Update Zwave Product Database

---

bundles/binding/org.openhab.binding.zwave/database/ge/dimmer.xml

Added CDATA tags to Help and formatted code.

Zwave Ge Database Edit: Dimmer

---

bundles/binding/org.openhab.binding.zwave/database/ge/receptacle.xml

Added CDATA and formatted code.

Zwave GE Database Edit : Receptacle

---

bundles/binding/org.openhab.binding.zwave/database/ge/relay.xml

Added CDATA and formatted code.

Zwave GE Database Edit : Relay

---

bundles/binding/org.openhab.binding.zwave/database/ge/ZW4005.xml

Added CDATA tags and formatted code

Zwave GE Database Edit : ZW4005

---

bundles/binding/org.openhab.binding.zwave/database/ge/zw3003.xml

Added CDATA to help and formatted code.

Zwave GE Database Edit : zw30003

---

bundles/binding/org.openhab.binding.zwave/database/ge/ZW3101.xml

Added CDATA tags and formatted code

Zwave GE Database Edit zw3101

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Find out what's right when or if someone complains!!!

Removing keyfob G1 since the type/id conflicts with the G5

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added new Device ID to product file per Issue #3038

Zwave.Me WALLC-S ID ADD

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

added fgd212.xml to products.xml

zwave: add Fibaro Dimmer 2 (FGD-212) to DB

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhod.xml

Added Qubino  ZMNHOD

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhod.xml

https://github.com/openhab/openhab/issues/3039

Update Qubino ZMNHOD

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhod.xml

https://github.com/openhab/openhab/issues/3039

Update Qubino ZMNHOD parameter 10

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Add HEATIT thermostat to database

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/thermofloor/multireg_thermostat.xml

http://www.pepper1.net/zwavedb/device/624
https://github.com/openhab/openhab/issues/2180

Add heatit (Thermo-Floor) thermostat

---

bundles/binding/org.openhab.binding.samsungac/src/main/java/org/binding/openhab/samsungac/communicator/AirConditioner.java
bundles/binding/org.openhab.binding.samsungac/src/main/java/org/binding/openhab/samsungac/communicator/SsdpDiscovery.java
bundles/binding/org.openhab.binding.samsungac/src/main/java/org/openhab/binding/samsungac/internal/SamsungAcBinding.java

During my latest testing and discussions in the forums, there has been some issues with SsdpDiscovery.
I've handled the discovery better, and it has been tested by some other users as well.
Also the air conditioners sometimes disconnect from the WIFI, this caused the binding to drop the connection and not properly reconnect, this should, if not fix it entirely, better the problem...

Better SsdpDiscovery and improved stability

---

bundles/binding/org.openhab.binding.zwave/database/cooper/rfwc5.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

database files for the RFWC5 5-button scene controller device from Cooper

add RFCW5 to the database

---

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/SatelBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/ConfigIterator.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/ConnectionStatusBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStatusBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/SatelBindingConfigFactory.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/ConfigurationDictionary.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBinding.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelGenericBindingProvider.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/IntRSModule.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java

This PR allows to connect to Satel INT-RS via RS-232 interface. Besides that it introduces some other communication improvements and code refactoring around binding configuration.

[satel] INT-RS support added.

---

bundles/binding/org.openhab.binding.fs20/src/main/java/org/openhab/binding/fs20/internal/FS20Binding.java
bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULSerialHandlerImpl.java

Patch as described in #3087.  Not tested; only verified that `mvn clean install` succeeds.  @wojtus, please verify this fix is what you intended and that it works (i.e., test the bundle that contains this patch).  Thank you!

[Cul] patch as described in #3087

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherPublisher.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/scheduler/WeatherJobScheduler.java

In reference to  #3092 this pull request removes the internal caching in the weather binding to avoid holding state in the binding.

[Weather] remove caching

---

bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/listeners/ItemStateChangeListener.java
bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/listeners/ResourceStateChangeListener.java
bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/resources/ItemResource.java
bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/internal/resources/ResponseTypeHelper.java

added functionality to register to /rest/items for xml/json/jsonp for atmosphere (websocket) requests

added websocket functionality to /rest/items

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveDeviceClass.java

https://github.com/openhab/openhab/issues/3128

Add Secure Barrier Add-on device class

---

bundles/binding/org.openhab.binding.zwave/database/fakro/arz.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

New product added to z-wave database - Fakro ARZ Z-Wave (roller shutter module).

[zwave] Fakro ARZ Z-Wave added to the database.

---

bundles/archetype/org.openhab.archetype.action/src/main/resources/archetype-resources/OSGI-INF/action.xml
bundles/archetype/org.openhab.archetype.action/src/main/resources/archetype-resources/src/main/java/internal/__action-name__ActionService.java

fix Action archetype in order to remove the usage of ManagedServices

---

bundles/binding/org.openhab.binding.ecobee/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.nest/META-INF/MANIFEST.MF

Clean up bundle dependencies to make it compatible with openHAB 2.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/tkb/tz88.xml

Add the ID for the UK version of the Greenwave 5 Port PowerNode to the database.

[zwave] Add the UK version of the Greenwave np210

---

bundles/binding/org.openhab.binding.zwave/database/philio/pan08.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add the Philio 'Relay Insert for Blind Control' PAN08 to the database.

[z-wave] Add Philio PAN08

---

bundles/binding/org.openhab.binding.zwave/database/popp/009303.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add database entry for Popp 009303 Battery Wall Controller

Add Popp 009303 Wall Controller

---

bundles/binding/org.openhab.binding.zwave/database/leviton/dzr15-1lz.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added database support for receptacle per Issue #3094

Added Leviton DZR15-1LZ

---

bundles/persistence/org.openhab.persistence.rrd4j/OSGI-INF/rrd4j.xml
bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

fixes #3168

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/pull/3191

Fix whitespace error

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3214

Add new reference for Aeon Gen5 key fob

---

bundles/action/org.openhab.action.openwebif/META-INF/MANIFEST.MF
bundles/action/org.openhab.action.xpl/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.lgtv/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.mochadx10/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.sagercaster/META-INF/MANIFEST.MF

fixes dependency infos in manifests in order to make bundles compile on

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3226

Add EcoNet EV100 vent

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zm1602v4

The Vision Security Siren 1602 with version application 15.3 and Version 4 has 2 parameters like the previous version but the index start to 1 instead of 0.

New Vision Security 1602

---

bundles/binding/org.openhab.binding.zwave/database/nodon/crc3100.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3240

Add Nodon CRC3100

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhda.xml

Added missing label for parameter with index 1.

[zwave] Qubino ZMNHDA database fix.

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/CommandHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/PollHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

@teichsta Replacement PR for #3139

Added support for Insteon FanLinc module, model 2475F.

---

bundles/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBinding.java

Signed-off-by: hmerk <hans-joerg.merk@t-online.de>
As per discussion https://community.openhab.org/t/milight-brightness/2672

Fix Milight brigthness bug

---

bundles/archetype/org.openhab.archetype.action/src/main/resources/archetype-resources/OSGI-INF/action.xml
bundles/archetype/org.openhab.archetype.binding/src/main/resources/archetype-resources/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.autelis/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.harmonyhub/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.lightwaverf/OSGI-INF/binding.xml
bundles/persistence/org.openhab.persistence.cosm/OSGI-INF/cosm.xml
bundles/persistence/org.openhab.persistence.db4o/OSGI-INF/configuration.xml
bundles/persistence/org.openhab.persistence.gcal/OSGI-INF/gcalpersistence.xml
bundles/persistence/org.openhab.persistence.influxdb/OSGI-INF/influxdb.xml
bundles/persistence/org.openhab.persistence.jpa/OSGI-INF/configuration.xml
bundles/persistence/org.openhab.persistence.logging/OSGI-INF/loggingpersistence.xml
bundles/persistence/org.openhab.persistence.mapdb/OSGI-INF/mapdb.xml
bundles/persistence/org.openhab.persistence.mongodb/OSGI-INF/mongodb.xml
bundles/persistence/org.openhab.persistence.mqtt/OSGI-INF/mqtt-persistence.xml
bundles/persistence/org.openhab.persistence.mysql/OSGI-INF/mysql.xml
bundles/persistence/org.openhab.persistence.sense/OSGI-INF/sense.xml

thanks @kaikreuzer for providing the according fix for rrd4j already

Another try to fix #2661

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhcd.xml

Added new ID to ZMNHCD product and fixed labels in the product xml file.

[Z-Wave] Database update for Qubino flush shutter

---

bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/engine/RuleTriggerManager.java
bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/engine/scriptmanager/Script.java
bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/shared/UpdatedEventTrigger.java

Second attempt. Commits are squashed. See discussion at #3249.

JSR223: Support for UpdatedEventTrigger

---

bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/Mail.java
bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/MailActionService.java
distribution/openhabhome/configurations/openhab_default.cfg

Sends message as UTF-8 which allows non-ascii characters in message body.

Mail action: send message as UTF-8

---

bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransaction.java

substitues pull request #3211 / fix for #658

modbus binding bug fix - connections were left open on command execution

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3240

Fix Nodon manufacturer ID

---

bundles/persistence/org.openhab.persistence.rrd4j/META-INF/MANIFEST.MF

removed version constraints

---

bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/engine/scriptmanager/Script.java

[jsr223] Added missing UnDefType

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhbd.xml

Z-Wave plus version of Qubino Flash 2 relays added to the database.

[ZWave] Database updated (Qubino Flash 2 relays)

---

bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

reverted all changes to InfluxDBPersistenceService that accidentally found their way into the service through #3125 and reapplied removal of PersistenceRestorer - sorry for any inconvenience! 

reapplied removal of PersistenceRestorer to latest InfluxDbService

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhbd.xml

Minor DB fix for Flash 2 relays.

[z-wave] Database update (Qubino Flash 2 relays)

---

bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/WithingsGenericBindingProvider.java

Fixed bad array index as report in #3336.

Fixed bad array index in withings binding config.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhdd.xml

Just a Z-wave database update.

Z-wave Qubino Flush Dimmer Plus ZMNHDD

---

bundles/action/org.openhab.action.mail/src/main/java/org/openhab/action/mail/internal/Mail.java

Also see #3348 as an alternative pull request (didn't realize this existed; please consider the more appropriate one).  This pull request tries to use the file name or falls back to "Attachment", and also has a new action method signature that takes a list of strings with are URLs to attachments.

[mail action] Supply attachment name; allow multiple attachments.

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhdd.xml

Fixes to Z-Wave Plus Qubino dimmer.

[z-wave] Database updates for Qubino Flush Dimmer (Z-Wave Plus)

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhbd.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhdd.xml

Yet another Qubino db update, this time associations have been fixed basing on the newest docs.

[z-wave] Database updates for new Qubino devices.

---

bundles/binding/org.openhab.binding.tacmi/.classpath
bundles/binding/org.openhab.binding.tacmi/.project
bundles/binding/org.openhab.binding.tacmi/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.tacmi/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.tacmi/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.tacmi/README.md
bundles/binding/org.openhab.binding.tacmi/build.properties
bundles/binding/org.openhab.binding.tacmi/pom.xml
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/TACmiBindingProvider.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBinding.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiGenericBindingProvider.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiMeasureType.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogMessage.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogValue.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/DigitalMessage.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/Message.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/MessageType.java
bundles/binding/org.openhab.binding.tacmi/src/main/resources/readme.txt
bundles/binding/pom.xml
distribution/openhabhome/configurations/openhab_default.cfg
distribution/pom.xml

This is an initial release of a binding for the CMI from Technische Alternative.

Initial implementation of TACmi binding.

---

bundles/core/org.openhab.core.library.test/src/test/java/org/openhab/core/library/items/DimmerItemTest.java
bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/DimmerItem.java

… which reverts commit 6f7c38469681080932977f839261b37ff5529d73 from PR #3362 but should contain the desired fix as well.

Back ported ESH DimmerItem to openHAB (also DimmerItemTest)

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherPublisher.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/gfx/WeatherTokenResolver.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/utils/UnitUtils.java

Example: 
```
${weather:temperature.current(%.1f)[fahrenheit]}
```

Weather: Added unit conversion in html tokens

---

distribution/openhabhome/configurations/openhab_default.cfg

Fixed networkupstools binding example; added DSMR binding example

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherBinding.java

See discussion [here](https://community.openhab.org/t/sending-wunderground-temperature-to-knx-bus/3976).

[weather] ignore received commands and updates

---

bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/internal/XbmcActiveBinding.java
bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/XbmcConnector.java
bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/calls/InputExecuteAction.java

Trivial addition that opens many new possibilities (http://kodi.wiki/view/JSON-RPC_API/v6#Input.Action).

[XMBC] Added Input.ExecuteAction to XBMC binding.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/sensative/strips11-01-011.xml

Updated zwave database for #3384.

Add sensative strips to zwave database.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3226

Update EV100 codes

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhad.xml

https://github.com/openhab/openhab/issues/3416

Add ZMNHAD

---

bundles/binding/org.openhab.binding.lcn/META-INF/MANIFEST.MF

fixed version of LCN bundle

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveAlarmCommandClass.java

Unknown name at this stage. Used by ZCOMBO.

Add alarm type 12

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Add additional device id for Trane thermostat XL624

Add additional device id for Trane thermostat XL624

---

bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhad.xml

Updated with new parameters and adjusted associations (didn't know how to add specific association groups per end point, so just the association groups for the root device i currently present).

Update zmnhad.xml for issue #3416

---

bundles/binding/org.openhab.binding.zwave/database/aeon/4in1ms_g5.xml

https://github.com/openhab/openhab/issues/3409

Add extra 4in1 Gen5 parameters.

---

bundles/action/org.openhab.action.telegram/.classpath
bundles/action/org.openhab.action.telegram/.project
bundles/action/org.openhab.action.telegram/META-INF/MANIFEST.MF
bundles/action/org.openhab.action.telegram/OSGI-INF/action.xml
bundles/action/org.openhab.action.telegram/build.properties
bundles/action/org.openhab.action.telegram/pom.xml
bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramActionService.java
bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramActivator.java
bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramBot.java
bundles/action/org.openhab.action.telegram/src/main/resources/readme.txt
bundles/action/pom.xml
distribution/openhabhome/configurations/openhab_default.cfg
distribution/pom.xml
features/org.openhab.designer.feature/feature.xml

```
telegram:bots=bot1,bot2
telegram:bot1.chatId=22334455
telegram:bot1.token=xxxxxx
telegram:bot2.chatId=654321
telegram:bot2.token=yyyyyyyyyyy
```
```
rule "Send telegram with Fixed Message"
when
Item Foo changed
then
sendTelegram("bot1", "item Foo changed")
end
```
```
rule "Send telegram with Formatted Message"
when
Item Foo changed
then
sendTelegram("bot1", "item Foo changed to %s and number is %.1f", Foo.state.toString, 23.56)
end
```

Telegram action

---

bundles/binding/org.openhab.binding.zwave/database/aeon/4in1ms_g5.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Have added configuration for a new type of Reitz Group Plug Switch and fixed documentation for #3409

ZWave DB: Added type mapping and fixed documentation

---

bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpCommand.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpCommandRef.java

Added Game2 channel for newer Onkyo devices.

Onkyo game2 channel

---

bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/messages/GetStationsDataRequestStub.java
bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/messages/GetStationsDataTest.java
bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/messages/MeasurementRequestStub.java
bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/messages/MeasurementTest.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoMeasureType.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoUnitSystem.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/AbstractRequest.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/GetStationsDataRequest.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/MeasurementRequest.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/messages/RefreshTokenRequest.java

This pull request includes a fix for https://github.com/openhab/openhab/issues/3429

Netatmo: add support for wind module, fix for issue 3429: use HTTP POST instead of HTTP GET

---

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java

Fix Anel-binding for new Firmware 6 beta (28 fields in UDP protocol).

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMultiLevelSwitchConverter.java

https://github.com/openhab/openhab/issues/3134

Make 99% read 100% for multilevel switch

---

distribution/pom.xml

Included CalDAV binding into the distribution

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMultiLevelSwitchConverter.java

https://github.com/openhab/openhab/issues/3481

Add type check to multi level command converter

---

bundles/binding/org.openhab.binding.zwave/database/domitech/domezbulb.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Tested locally https://community.openhab.org/t/domitech-z-wave-zbulb/4553 @cdjackson

Add domitech zbulb led bulb to z-wave product database

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMultiLevelSensorConverter.java

https://github.com/openhab/openhab/issues/3395

Use BigDecimal for temperature conversion

---

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java
bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/AuthorizeResponse.java
bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/Thermostat.java

Updated Ecobee binding (and wiki) to align with the minor updates present in the [December 2015 ecobee API update](https://www.ecobee.com/home/developer/api/documentation/v1/change-log.shtml)

[Ecobee] Updated to align with December 2015 ecobee API update.

---

bundles/io/org.openhab.io.cv/src/main/java/org/openhab/io/cv/CVApplication.java
bundles/io/org.openhab.io.rest/src/main/java/org/openhab/io/rest/RESTApplication.java

There is a situation that we want to have only one connector http or https.
When we use only one kind of connector only proper connector should be registered in discovery service.

Open http or https port for jetty only when configured

---

bundles/persistence/org.openhab.persistence.jdbc/.classpath
bundles/persistence/org.openhab.persistence.jdbc/build.properties

As requested by @lewie on https://github.com/openhab/openhab/pull/3493#issuecomment-160870679

JDBC Binding: remove resources from build upon author request

---

distribution/pom.xml

distribution/pom.xml is missing sapp binding - binding is not included in build

[sapp binding] - binding not included in addons build

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java

Code added on behalf of @lewie
Fixes #3516

jdbc persistence: fix postgresql table creation

---

bundles/binding/org.openhab.binding.mqtt.test/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.mqtt.test/src/test/java/org/openhab/binding/mqtt/internal/MqttItemConfigTest.java
bundles/binding/org.openhab.binding.mqtt.test/src/test/java/org/openhab/binding/mqtt/internal/MqttMessageSubscriberTest.java
bundles/binding/org.openhab.binding.mqtt/OSGI-INF/mqtt-eventbus-binding.xml
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttEventBusBinding.java
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttGenericBindingProvider.java
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttItemConfig.java
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttMessageSubscriber.java

This PR is for discussion and review only at this point.  It relates to [this discussion](https://community.openhab.org/t/strange-string-behaviour-on-on-off/4735/1).

[mqtt] Make inbound messages sensitive to item's accepted types and commands

---

bundles/binding/org.openhab.binding.sapp/src/main/java/org/openhab/binding/sapp/internal/SappBinding.java

Some events do not trigger eventPublisher update

[SAPP binding] bug: some events from device are not managed

---

bundles/action/org.openhab.action.xmpp/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.fs20/src/main/java/org/openhab/binding/fs20/internal/FS20Binding.java
bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/internal/OpenEnergyMonitorBinding.java
bundles/binding/org.openhab.binding.samsungac/src/main/java/org/openhab/binding/samsungac/internal/SamsungAcBinding.java
bundles/binding/org.openhab.binding.weather/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/internal/XbmcActiveBinding.java
bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java

a few bug fixes to make the addons work on openHAB 2 (Karaf)

---

bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdBinding.java

It may happen that a song changes, but the id stays the same (e.g. for streams).
Therefore, test whether the title or the artist has changed instead of
the id (which is of no interest anyway).

mpd: fix artist and track not updated

---

distribution/pom.xml

MQTT action JAR was missing from addons.zip.

Added MQTT action JAR to addons.zip

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/rtc/ct32.xml

add ct-32 to zwave database

---

bundles/binding/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/connection/ConnectionSettings.java
bundles/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.systeminfo/OSGI-INF/binding.xml
bundles/io/org.openhab.io.multimedia.tts.marytts/META-INF/MANIFEST.MF

a few fixes to run smoothly on Karaf

---

bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonConnector.java

Denon NPE fix

---

bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/RWESmarthomeCommunicator.java

This commit fixes a sometimes happening timeout problem and is very important for a stable binding in OH 1.8.0. So please include it in the release.

Fixed session timeout problem (important for 1.8.0 release)

---

bundles/binding/org.openhab.binding.zwave/database/linear/wo15z-1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

As per information from http://www.pepper1.net/zwavedb/device/484

zwave config for Linear WO15Z-1 outlet

---

bundles/binding/org.openhab.binding.zwave/database/nodon/crc3605.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3586

Add Nodon SoftRemote (CRC3605)

---

bundles/io/org.openhab.io.multimedia.tts.marytts/META-INF/MANIFEST.MF

added missing package import

---

bundles/action/org.openhab.action.squeezebox/src/main/java/org/openhab/action/squeezebox/internal/Squeezebox.java
bundles/io/org.openhab.io.squeezeserver/src/main/java/org/openhab/io/squeezeserver/SqueezeServer.java
distribution/openhabhome/configurations/openhab_default.cfg

Refer https://community.openhab.org/t/googletts-responding-with-503-error-even-after-the-url-fix/3385/2
Allows any TTS service to be used with the Squeezebox speak action.

Updated Squeezebox speak action to allow configurable TTS URL

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/utils/UnitUtils.java

should fix https://community.openhab.org/t/error-from-weather-binding/5305/2

Weather: Fixed exception if degree is not in a valid range

---

bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxSynchronizer.java

This PR is related to https://github.com/openhab/openhab/issues/3451
Changes:
1/ use smarthome.userdata directory for storing dbx files
2/ smarthome/openhab.configdir as default contentdir

fix permission and content directory issues when used within apt installation

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/CommandHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

Added the features necessary for the insteon on/off outlet. Tested, verified working.

insteonplm: Added On/Off Outlet and related CommandHandler changes

---

bundles/binding/org.openhab.binding.myq/.classpath
bundles/binding/org.openhab.binding.myq/.project
bundles/binding/org.openhab.binding.myq/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.myq/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.myq/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.myq/build.properties
bundles/binding/org.openhab.binding.myq/pom.xml
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/MyqBindingProvider.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/GarageDoorData.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/GarageDoorDevice.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/InvalidDataException.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/InvalidLoginException.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/LoginData.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQResponseCode.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBindingConfig.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqData.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqGenericBindingProvider.java
bundles/binding/org.openhab.binding.myq/src/main/resources/readme.txt
bundles/binding/pom.xml
distribution/openhabhome/configurations/openhab_default.cfg
distribution/pom.xml

@teichsta Chamberlain MyQ Binding is ready for review

Added Chamberlain MyQ Binding

---

bundles/binding/org.openhab.binding.wemo/README.md
bundles/binding/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBinding.java
bundles/binding/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoGenericBindingProvider.java

Fix for #3538 -- added additional parameters for wemo insight plug
More info in the [forum thread] (https://community.openhab.org/t/wemo-insight-plug-adding-new-params-to-binding/4969) with @hmerk

Wemo insight: additional parameters added #3538

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Precipitation.java

see [discussion](https://community.openhab.org/t/wunderground-forecast-rain-total/5343/11) and https://github.com/openhab/openhab/issues/3596

Weather: Added Wunderground total precipitation

---

features/openhab-addons-external/pom.xml
features/openhab-addons-verify/pom.xml

fixes #3626

---

features/pom.xml

disable feature verification

---

bundles/binding/org.openhab.binding.mystromecopower/src/main/java/org/openhab/binding/mystromecopower/internal/MyStromEcoPowerBinding.java

Fix if the master device is not configured into the openhab config file.

Mystrom Binding fix

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added ZW089B and FGSS001 to Products File

---

bundles/binding/org.openhab.binding.zwave/database/vision/zd2102.xml

Added user requested Parameter 1: Per Issue #3064

Updated Vision zd2102

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added Remotec ZXT-120AU

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Fibaro RGBW

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/CommandHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

See #3579. I've tested this manually with my Insteon PLM and 2672-222 bulb.

Insteon: Added Ramp Dimmer Support

---

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java

Modbus binding: Items bound to discrete / coil issue fixed

---

bundles/binding/org.openhab.binding.lightwaverf.test/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.octoller/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.samsungac.test/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.yamahareceiver/META-INF/MANIFEST.MF
bundles/io/org.openhab.io.rest.test/META-INF/MANIFEST.MF
bundles/io/org.openhab.io.transport.cul.test/META-INF/MANIFEST.MF

Update stale Bundle-Versions (for #3638)

---

bundles/binding/org.openhab.binding.energenie/src/main/java/org/openhab/binding/energenie/internal/EnergenieBinding.java
bundles/binding/org.openhab.binding.energenie/src/main/java/org/openhab/binding/energenie/internal/EnergenieBindingConfig.java
bundles/binding/org.openhab.binding.energenie/src/main/java/org/openhab/binding/energenie/internal/EnergenieGenericBindingProvider.java

Signed-off-by: hmerk <hans-joerg.merk@t-online.de>

Add support for energie measuerement on PWM-LAN devices. Replaces #2908

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavEvent.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventJob.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java
distribution/openhabhome/configurations/openhab_default.cfg

update logging, 
add new parameter for caldav loading with invalid timestamps, 
fix rescheduling events

fix logging and rescheduling

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavEvent.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventJob.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java
distribution/openhabhome/configurations/openhab_default.cfg

Revert "fix logging and rescheduling"

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavEvent.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventJob.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java
distribution/openhabhome/configurations/openhab_default.cfg

update logging,
add new parameter for caldav loading with invalid timestamps,
fix rescheduling events

[caldav] fix logging and rescheduling

---

bundles/binding/org.openhab.binding.zwave/database/vision/zl7431.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zl7432.xml

Updated Vision ZL7431 and 32 for Multi-Instance

---

bundles/binding/org.openhab.binding.zwave/database/everspring/sm103.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Fixing zwave binding database for issue #3595

Fix issue #3595 - Everspring sm103 recognized as hsm02

---

bundles/binding/pom.xml
distribution/pom.xml

Reverts openhab/openhab#3675 due to build problems (see discussion in #3675)

Revert "Include binding fritzboxtr064 into build process"

---

bundles/core/org.openhab.core/src/main/java/org/openhab/core/types/UnDefType.java

Revert "remove the special toString() in order to sync with ESH"

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Added AU version of Fibaro Dimmer 2. Corrected ID for FGRGBW

Added AU version of FGD212 / Correction to FGRGBW

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveNode.java

Remove applicationUpdateReceived from XML

---

features/openhab-addons-verify/pom.xml
features/pom.xml

In preparation of https://github.com/openhab/openhab-distro/issues/11
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

Update to new ESH feature

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveNode.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/serialmessage/IdentifyNodeMessageClass.java

@teichsta this is for 1.8 once merged (I need to test some more in OH2 first).

Add additional device information flags

---

bundles/binding/org.openhab.binding.lightwaverf.test/src/test/java/org/openhab/binding/lightwaverf/internal/LightwaveRfGenericBindingProviderTest.java

See https://github.com/openhab/openhab/pull/3670#commitcomment-15257429
Consider cherry-picking onto 1.8 branch.

Fix list compare change in #3670 (@gameldar comment)

---

features/openhab-addons-verify/pom.xml
features/pom.xml

added jfrog snapshot repo

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft11.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft13.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_ft14.xml

Added support for all 4 versions per Issue #3597

Added Zwaveme Floor Thermostats

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/ecobee.cfg
features/openhab-addons-external/src/main/resources/conf/nest.cfg
features/openhab-addons/src/main/feature/feature.xml

Adding to 2.0 compatible action and bindings as in #3614.

Added Ecobee and Nest to features.

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveDeviceClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java

@teichsta I'd like to get this into 1.8 if still possible...

Updates to fix XML serialisation issues

---

bundles/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/NibeHeatPumpBinding.java

Reported working https://github.com/openhab/openhab/issues/3714#issuecomment-169451019

[nibeheatpump] Fix for #3714

---

bundles/binding/org.openhab.binding.zwave/database/popp/004001.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added POPP 004001 Smoke detector with internal Siren to zwave database.
Alll data was pulled from Pepper1.

Added POPP 004001 to resolve issue #3700

---

bundles/persistence/org.openhab.persistence.db4o/OSGI-INF/configuration.xml
bundles/persistence/org.openhab.persistence.db4o/OSGI-INF/database-db4o.xml
bundles/persistence/org.openhab.persistence.db4o/src/main/java/org/openhab/persistence/db4o/internal/Db4oPersistenceService.java

See #3728 and [forum discussion](https://community.openhab.org/t/db4o-persistence-broken-in-1-8/5889/5).  Thanks @lewie!  @teichsta, could you review/merge/cherry-pick?

[db4o-persistence] fix for #3728

---

bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/GarageDoorData.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/LoginData.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqData.java

Changed trace to debug level for device data. Added new device name to regex. Fixed door state logging.

MyQ Device fixes

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/281

Update Merten wall controller ID

---

bundles/persistence/org.openhab.persistence.sitewhere/META-INF/MANIFEST.MF

removed unnecessary import

---

bundles/persistence/org.openhab.persistence.caldav/META-INF/MANIFEST.MF

removed require-bundle directive

---

bundles/binding/org.openhab.binding.sonance/.classpath

removed non-existing source folder

---

bundles/binding/org.openhab.binding.mystromecopower/META-INF/MANIFEST.MF

Replaced require-bundle directive

---

bundles/binding/org.openhab.binding.zwave/database/linear/wt00z-1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

As per specification at http://www.pepper1.net/zwavedb/device/485.

adding zwave database entry for Linear WT00Z-1

---

bundles/persistence/org.openhab.persistence.caldav/META-INF/MANIFEST.MF

added missing import

---

bundles/binding/org.openhab.binding.yamahareceiver/.classpath
bundles/binding/org.openhab.binding.yamahareceiver/build.properties

some cleanup on yamahareceiver project

---

bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/messages/GetStationsDataTest.java
bundles/binding/org.openhab.binding.netatmo.test/src/test/resources/getstationsdata.json
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java

This PR replaces #3735 and contains only one commit with all changes.

[netatmo] add the possibility to have several station positions

---

bundles/binding/org.openhab.binding.zwave/database/philio/PAT02

Took the information from the datasheet of the PAT02 of Philio

Flood Multisenson PAT02-A/B/C

---

features/openhab-addons-external/src/main/resources/conf/weather.cfg

Same as #3813, but for master branch (OH2).

[weather] Added name examples to default weather.cfg (like #3813)

---

bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java

This fixes https://github.com/openhab/openhab/issues/3808

Fix for defect 3808, remove extra Unicode character 0x0xfeff.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_054336.xml
bundles/binding/org.openhab.binding.zwave/database/zwaveme/zme_10024.xml

https://github.com/cdjackson/HABmin/issues/285
https://github.com/cdjackson/HABmin/issues/286
@yased - please advise if this is ok and close the two requests if it is.

Added ZWave.me devices to database

---

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java

method sendTelegramPhoto accepts two additional optional parameters (username and password) used to get image on locked servers

Telegram action: added username/password authorization on image http get

---

bundles/binding/org.openhab.binding.netatmo/OSGI-INF/binding.xml
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/netatmo.cfg
features/openhab-addons/src/main/feature/feature.xml

Tested with both 1.8 and latest build of 2.0.

OH2 changes for Netatmo

---

bundles/binding/org.openhab.binding.sonance/src/main/java/org/openhab/binding/sonance/internal/SonanceBinding.java

Fixed a bug with the volume command and enabled power query again as described under "known issues" in the Wiki: https://github.com/openhab/openhab/wiki/Sonance-binding
Signed-off-by: Laurens Van Acker laurens-at-van-dot-acker-dot-be

Sonance binding power query and volume command fix

---

pom.xml

Update target platform to new p2 repository
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

Replace target platform with openhab deps repo

---

pom.xml

Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>

Update openhab-deps-repo url to new location

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmdhsd.xml

https://github.com/cdjackson/HABmin2/issues/110

Add Qubino ZMDHSD

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java

https://github.com/openhab/openhab/pull/3880

Remove dependancy on database to determine if device supports class during config

---

bundles/binding/org.openhab.binding.networkhealth/src/main/java/org/openhab/binding/networkhealth/internal/NetworkHealthBinding.java

Added addBindingProvider and removeBindingProvider to NetworkHealth Binding for OpenHAB2 compatibility.

Added add and remove binding methods for OH2 compatibility.

---

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java

[tcp] Same change as #3792 on master

---

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java

[tcp] Same change as #3792 on 1.8

---

bundles/persistence/org.openhab.persistence.rrd4j/OSGI-INF/rrd4j.xml
bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

ignoring component.name service property

---

bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnectionProperties.java
bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexConnector.java
bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/Connection.java
bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/Device.java
bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/communication/MediaContainer.java

Support for Plex Media Servers with required secure connections

---

bundles/binding/org.openhab.binding.koubachi/src/main/java/org/openhab/binding/koubachi/internal/KoubachiBinding.java
bundles/binding/org.openhab.binding.koubachi/src/main/java/org/openhab/binding/koubachi/internal/api/Device.java

Thanks to input [here](https://community.openhab.org/t/koubachi-not-supporting-new-values/4833/13?u=watou), it now makes sense to update this binding to v3 API.  I will update wiki after merge.

[koubachi] Added v3 API Device members; changed default URLs to v3.

---

bundles/binding/org.openhab.binding.zwave/database/ge/12718.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Appeared as a generic device originally. It's basically a GE 45602.

Add Z-Wave config for GE 12718

---

bundles/binding/org.openhab.binding.zwave/database/homeseer/ezmultipli.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Based on user manual at http://www.expresscontrols.com/pdf/EZMultiPliOwnerManual.pdf and the Z-Wave db entry at www.pepper1.net/zwavedb/device/592.

Add EZMultiPli to product database. 

---

bundles/binding/org.openhab.binding.weather/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherBinding.java

Fixes #3829
Test JAR [here](https://dl.dropboxusercontent.com/u/4286376/weather-addBindingProvider/org.openhab.binding.weather-1.9.0-SNAPSHOT.jar)

[weather] add/removeBindingProvider; immediate="true"

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin/issues/293

Update FGK101 codes

---

bundles/action/org.openhab.action.twitter/src/main/java/org/openhab/action/twitter/internal/TwitterActionService.java

slightly enhanced log statement as suggested in #openhab/openhab/3782

---

bundles/binding/org.openhab.binding.souliss/resources/properties/commands_to_states.properties
bundles/binding/org.openhab.binding.souliss/resources/properties/states_SOULISStoOH.properties
bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/RefreshHEALTY.java
bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/typicals/RefreshSUBSCRIPTION.java
bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/udp/SendDispatcher.java
bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/udp/UDPSoulissDecoder.java

Some bugfix to definition of "Typical 18 : Pulse Digital Output - Use for bistable Relay" and other minor bugfix.

Some bugfix

---

bundles/binding/org.openhab.binding.enphaseenergy/src/main/java/org/openhab/binding/enphaseenergy/internal/EnphaseenergyBinding.java

Forum discussion [here](https://community.openhab.org/t/planning-1-8-1-and-2-0-beta2-releases/6812/18?u=watou).
Test JAR [here](https://dl.dropboxusercontent.com/u/4286376/enphaseenergy-addBindingProvider/org.openhab.binding.enphaseenergy-1.9.0-SNAPSHOT.jar).

[enphaseenergy] add/removeBindingProvider

---

features/openhab-addons-external/pom.xml

In PR #3946, I went ahead without validation.  Kai later provided the necessary steps to validate the config, so I fixed the errors that resulted from the additional manual build steps identified.
For reference, when making this type of change in `openhab` repo, you need to also do a `mvn clean install` from the `openhab-distro` repo.

MiOS Binding - Correct build errors from PR #3946

---

bundles/binding/org.openhab.binding.netatmo.test/src/test/java/org/openhab/binding/netatmo/internal/authentication/RefreshTokenRequestStub.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/authentication/OAuthCredentials.java
bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/authentication/RefreshTokenRequest.java

This fixes https://github.com/openhab/openhab/issues/3937

netatmo: fix for issue #3937

---

bundles/persistence/pom.xml

added rrd4j to the build again

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw100-a.xml
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveConfigurationCommandClass.java

Update parameter 42 of Aeon ZW100

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveDeviceClass.java

Add Binary Valve device class

---

bundles/binding/org.openhab.binding.zwave/database/econet/ebv105.xml
bundles/binding/org.openhab.binding.zwave/database/mcohome/mhs412.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/124

Add MHS412 and EBV105

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/culintertechno.cfg
features/openhab-addons/src/main/feature/feature.xml

Signed-off-by: Patrick Ruckstuhl patrick@ch.tario.org (github: tarioch)

Adding feature for intertechno

---

bundles/binding/org.openhab.binding.zwave/database/everspring/hac01.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/3591

Add Everspring HAC01

---

bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/RWESmarthomeBinding.java
bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/RWESmarthomeGenericBindingProvider.java
bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/RWESmarthomeCommunicator.java
bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/xmlresponse/GetAllLogicalDeviceStatesXMLResponse.java
bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/xmlresponse/GetEntitiesXMLResponse.java
bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/model/LogicalDevice.java

- added support for Power Control / Power Control Solar / Energy Control, fixes #3764
- fixes #3967, a session timeout problem while executing commands 
- fixed smoke detector example config
- fixed smoke detector return values to ON / OFF
- fixed isRunning()
- improved logging

RWE Smarthome: Fix session timeout / add support for power control & energy control

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java

ZWave: Fix casting error in config

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java

Matches @lewie's diff in #3992.

[jdbc persistence] fix for parsing given URL Strings with space char

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java

Fix error casting wakeup class

---

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java

Add lighting5 commands : OPEN_RELAY, CLOSE_RELAY and STOP_RELAY
Linked to  #3289 but no feedback has been received after this modification.

RFXCOM Add lighting5 commands OPEN|CLOSE|STOP_RELAY

---

bundles/binding/org.openhab.binding.tcp/src/main/java/org/openhab/binding/tcp/protocol/internal/ProtocolGenericBindingProvider.java

Added wildcards for TCP/UDP Binding, code duplicated from Exec Binding.

Added wildcard command for TCP/UDP Binding

---

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/weather/NetatmoWeatherBinding.java

The results from the method contains dynamic info such as battery level, wifi strenght, rf strenght, etc.

Netatmo: Poll The method getstationsdata instead of only calling it at startup.

---

bundles/binding/org.openhab.binding.zwave/database/mcohome/mhs411.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/cdjackson/HABmin2/issues/125

Add MCO Home MH-S411

---

bundles/binding/org.openhab.binding.astro/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/bus/AstroBinding.java

Reported and this change reported working: https://github.com/openhab/openhab-distro/issues/129
Cc: @Marty56

Changes to have 1.x astro binding work in OH2

---

bundles/binding/org.openhab.binding.smarthomatic/.classpath
bundles/binding/org.openhab.binding.smarthomatic/.project
bundles/binding/org.openhab.binding.smarthomatic/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.smarthomatic/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.smarthomatic/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.smarthomatic/build.properties
bundles/binding/org.openhab.binding.smarthomatic/pom.xml
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/SmarthomaticBindingProvider.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/BaseStation.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/InitializationException.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SHCMessage.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SerialDevice.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SerialEventWorker.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SmarthomaticActivator.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SmarthomaticBinding.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/java/org/openhab/binding/smarthomatic/internal/SmarthomaticGenericBindingProvider.java
bundles/binding/org.openhab.binding.smarthomatic/src/main/resources/data_types.xsd
bundles/binding/org.openhab.binding.smarthomatic/src/main/resources/packet_layout.xml
bundles/binding/org.openhab.binding.smarthomatic/src/main/resources/packet_metamodel.xsd
bundles/binding/org.openhab.binding.smarthomatic/src/main/resources/readme.txt
bundles/binding/org.openhab.binding.smarthomatic/src/test/java/org/openhab/binding/smarthomatic/TestSHCMessage.java
bundles/binding/org.openhab.binding.smarthomatic/src/test/java/org/openhab/binding/smarthomatic/TestSHCMessageGeneration.java

we've created a openhab binding for smarthomatic (see https://www.smarthomatic.org/basics/communication_protocol.html). I've also tested the binding with openhab2. Do I have to do anything else?

Smarthomatic binding for openhab

---

bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java

See [this report](http://developer.ecobee.com/api/topics/need-to-mass-clear-alerts-on-a-thermostat#reply_16614731).
This PR is for the 1.8 branch.  I will make a separate PR for master.

[ecobee] Include alerts in the payload when any item is bound to an alerts property

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveConfiguration.java

Update handling of configuration class detection

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveNodeNamingCommandClass.java

Minor improvements to a few log messages in the ZWaveNodeNamingCommandClass.

Minor improvements to ZWave log messages.

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveNodeNamingCommandClass.java

https://github.com/openhab/openhab/issues/4058
https://github.com/openhab/openhab/issues/4046

Handle null terminations in node naming class

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveNodeNamingCommandClass.java

Fix bug in node name class where location was set as the name

---

bundles/binding/org.openhab.binding.garadget/.classpath
bundles/binding/org.openhab.binding.garadget/.project
bundles/binding/org.openhab.binding.garadget/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.garadget/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.garadget/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.garadget/build.properties
bundles/binding/org.openhab.binding.garadget/pom.xml
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/GaradgetBindingProvider.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/AbstractDevice.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/Connection.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBinding.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBindingConfig.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetDevice.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetGenericBindingProvider.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetPublisher.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetSubscriber.java
bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/HttpResponseHandler.java
bundles/binding/org.openhab.binding.garadget/src/main/resources/garadget.items
bundles/binding/org.openhab.binding.garadget/src/main/resources/readme.txt
bundles/binding/pom.xml
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/garadget.cfg
features/openhab-addons/src/main/feature/feature.xml

See wiki [here](https://github.com/openhab/openhab/wiki/Garadget-Binding).

[garadget] initial commit of the Garadget binding

---

bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonConnector.java

The Denon binding was spamming the log with error level messages when the receiver was not reachable over http (when it was turned off for example). This issue is discussed here: https://community.openhab.org/t/denon-binding-spams-noroutetohostexception/7292
Since HttpUtil catches this error and logs it to level 'error' the binding now uses its own implementation for doing a http request.

Denon binding: use different http request method

---

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java

RFXCOM add support for undecoded RF Message

---

bundles/binding/org.openhab.binding.rfxcom.test/.classpath
bundles/binding/org.openhab.binding.rfxcom.test/.project
bundles/binding/org.openhab.binding.rfxcom.test/.settings/org.eclipse.core.resources.prefs
bundles/binding/org.openhab.binding.rfxcom.test/.settings/org.eclipse.jdt.core.prefs
bundles/binding/org.openhab.binding.rfxcom.test/.settings/org.eclipse.m2e.core.prefs
bundles/binding/org.openhab.binding.rfxcom.test/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.rfxcom.test/build.properties
bundles/binding/org.openhab.binding.rfxcom.test/pom.xml
bundles/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessagesTest.java
bundles/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureHumidityMessageTest.java

support for testing the RFXCOM messages.
Many of the problems that are reported running this tests in current master can be solved by @Speederc  PRs

RFXCOM test binding

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java

fixes #4055

---

bundles/binding/org.openhab.binding.zwave/database/danfoss/mt02650.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add Danfoss MT02650

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/neohub.cfg
features/openhab-addons/src/main/feature/feature.xml

Neohub Binding OH2

---

bundles/binding/org.openhab.binding.ebus/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.ebus/OSGI-INF/ebusbinding.xml
bundles/binding/org.openhab.binding.ebus/src/main/java/org/openhab/binding/ebus/internal/EBusBinding.java

- Remove dependency to logback
- Fix optional dependency on serial
- Remove unnecessary Activator class
- Remove bindingChanged helper thread, also removed configurationAdminService

Fix eBus binding issues for OH2

---

bundles/binding/org.openhab.binding.gc100ir/.classpath
bundles/binding/org.openhab.binding.gc100ir/.project
bundles/binding/org.openhab.binding.gc100ir/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.gc100ir/OSGI-INF/activebinding.xml
bundles/binding/org.openhab.binding.gc100ir/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.gc100ir/build.properties
bundles/binding/org.openhab.binding.gc100ir/pom.xml
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/GC100IRBindingProvider.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/GC100IRActivator.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/GC100IRBinding.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/GC100IRConnector.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/GC100IRGenericBindingProvider.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/GC100IRHost.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/response/GC100IRCommand.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/response/GC100IRCommandCode.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/response/GC100IRCompleteResponseCommandCode.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/response/GC100IRResponseCommandCodeFactory.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/internal/response/GC100IRUnknownResponseCommandCode.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/lib/GC100IRConnection.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/lib/GC100IRControlPoint.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/lib/GC100IRDevice.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/lib/IGC100IRControlPoint.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/util/GC100ItemBean.java
bundles/binding/org.openhab.binding.gc100ir/src/main/java/org/openhab/binding/gc100ir/util/GC100ItemUtility.java
bundles/binding/pom.xml
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/gc100ir.cfg
features/openhab-addons/src/main/feature/feature.xml

This is a fork of the https://github.com/openhab/openhab/pull/1586 PR which had gone stale. I've updated the code by resolving the code review comments and tidied up parts where I saw fit. Tested this binding and it works!

Global Cache IR binding

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConverterHandler.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveWakeUpConverter.java

@cdjackson , as discussed by email, I have added the option to set the wakeup interval of a device using an item. Few changes have been made:
- New ZWaveWakeUpConverter class has been added.
- ZWaveConverterHandler has been updated to support the new converter.
I am very new to the git and github stuff, I hope I did not make any mistake.
Aitor

Added the option to change the wakeup interval of a device from an item

---

bundles/binding/org.openhab.binding.zwave/database/dlink/dch-z120.xml
bundles/binding/org.openhab.binding.zwave/database/popp/004001.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add Z120 and update POPP 004001

---

bundles/binding/org.openhab.binding.zwave/database/aeon/minimote.xml
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveMultiLevelSensorCommandClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveWakeUpCommandClass.java

https://github.com/openhab/openhab/issues/4124

Update minimote to not request WAKEUP information

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Fix database entry for DLink Z120

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

closes https://github.com/openhab/openhab/issues/3400

Update codes for FGS211
