bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBaseMessage.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessageFactory.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComSecurity2Message.java

This PR is a single commit to replace #4012 .
It solves the merge conflict appeared after @Speederc  PRs merged.
@Speederc  please check my current solution for the protocol change. Currently only if firmware is >= 251 the new format will be used.

Add suppport for Security2/Keeloq protocol on rfxcom binding - updated

---

bundles/binding/org.openhab.binding.lgtv/META-INF/MANIFEST.MF

to make plugin compatible with openHAB 2.

[lgtv] Removed required bundle javax from MANIFEST file

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java
bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBindingProviderImpl.java
bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavConfig.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavEvent.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/CalDavQuery.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavConfig.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java
bundles/persistence/org.openhab.persistence.caldav/src/main/java/org/openhab/persistence/caldav/internal/CaldavConfiguration.java
bundles/persistence/org.openhab.persistence.caldav/src/main/java/org/openhab/persistence/caldav/internal/CaldavPersistenceService.java
distribution/openhabhome/configurations/openhab_default.cfg

- add charset option
- presence-simulation posibility
- filter for categories and event name
- small fixes

[caldav] - add charset option, presence-simulation, filter option

---

features/openhab-addons/src/main/feature/feature.xml

added serial binding to features

---

bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java

[novelan] Fix for issue #4119

---

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java

Remove redundant log messages that only cluttered the log and hid useful messages.
Make remaining log messages more consistent and readable.
Removed redundant toString() calls
(Replaces earlier pull request that had too many conflicts after the mass code formatting update in the master).

[plugwise] Clean up logging.

---

bundles/binding/org.openhab.binding.mochadx10/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.mochadx10/OSGI-INF/mochadx10binding.xml
bundles/binding/org.openhab.binding.mochadx10/src/main/java/org/openhab/binding/mochadx10/internal/MochadX10Binding.java

https://github.com/openhab/openhab/issues/4136

MochadX10 fix hanging on OH2 shutdown - Issue #4136

---

features/openhab-addons/src/main/feature/feature.xml

updated compatible persistence services

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/influxdb.cfg
features/openhab-addons-external/src/main/resources/conf/mapdb.cfg

added config files required by #4144

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java

Creating main Items-table, generate SQL in histItemFilterQueryProvider and a upper- lowercase problem: https://github.com/openhab/openhab/issues/4111

4 Bugs in Derby DAO and some typo

---

bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBinding.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogValue.java
bundles/binding/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/Message.java

Fixed handling of negative temperature values
Improved BigDecimal Math
Improved error handling, logging and socket timeout in exec loop

Small fixes to TACmi binding

---

bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxSynchronizer.java

issues #956 
Signed-off-by: Scott (github: computergeek1507)
Tested on my 1.8.1 install.

Fix dropbox for windows machines

---

bundles/binding/org.openhab.binding.stiebelheatpump/src/main/java/org/openhab/binding/stiebelheatpump/internal/ConfigParser.java

Occurred on widnows build by maven.

MalformedByteSequenceException in stiebelheatpump ConfigParserTest

---

pom.xml

switched to snapshot version of core bundles

---

pom.xml

corrected repo location

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveSceneConverter.java

Catch number format exception in scene converter

---

distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/koubachi.cfg
features/openhab-addons/src/main/feature/feature.xml

[koubachi] make installable from Paper UI

---

bundles/binding/org.openhab.binding.zwave/database/aeon/minimote.xml
bundles/binding/org.openhab.binding.zwave/database/econet/ebv105.xml
bundles/binding/org.openhab.binding.zwave/database/greenwave/np310.xml
bundles/binding/org.openhab.binding.zwave/database/greenwave/ns210.xml
bundles/binding/org.openhab.binding.zwave/database/greenwave/ns310.xml
bundles/binding/org.openhab.binding.zwave/database/philio/psr04.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/stelpro/stzw402.xml
bundles/binding/org.openhab.binding.zwave/database/telldus/tzdw-100.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zp3103.xml

ZWave Update database

---

distribution/openhabhome/configurations/openhab_default.cfg

… in `openhab_default.cfg`.  I will update [the wiki](https://github.com/openhab/openhab/wiki/Squeezebox-Binding#incorrect-info-in-config-comments) after this is merged.

Correct squeezebox action and binding example config

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

closes https://github.com/openhab/openhab/issues/4164

ZWave: Update FGMS001 codes

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveDeviceClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveNodeNamingCommandClass.java

Update device classes and add santiy checks in node naming class

---

bundles/binding/org.openhab.binding.zwave/database/vision/zl7431.xml
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/ZWaveNode.java

Request update following node naming

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java

stabilized jdbc service startup on incomplete configuration

---

ISSUE_TEMPLATE.md

Proposed initial version of issue template for openhab. We can tweak it over time but I'd like to get an initial version into the repository.

initial commit of issue template

---

bundles/binding/org.openhab.binding.nest/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.nest/build.properties

Like @kaikreuzer added for One-Wire binding in #4268

[nest] added configuration meta-data

---

ISSUE_TEMPLATE.md

These are updates to the issue template based on feedback from reviewers.

Updates to issue template

---

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueGenericBindingProvider.java

Also reduced the nesting depth.

Log a warning if the Hue binding for an item is empty.

---

features/openhab-addons-verify/pom.xml
features/openhab-addons/src/main/feature/feature.xml
features/pom.xml

Related to: https://github.com/openhab/openhab-distro/pull/172

[WIP] changes for Xtext 2.9.2 usage (ESH / OH)

---

features/openhab-addons/src/main/feature/feature.xml

renamed netatmo binding v1

---

features/openhab-addons-verify/pom.xml
features/openhab-addons/src/main/feature/feature.xml

Related to eclipse/smarthome#1396

use ESH Karaf target platform

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

Add support for KNX DPT 14.058 (DPT_PRESSURE).

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/proprietary/FibaroFGRM222CommandClass.java

Add extra FGRM manufacturer_specific codes

---

features/openhab-addons-verify/pom.xml

fixes https://github.com/openhab/openhab-distro/issues/163

adds esh addons to the verification

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/alarmdecoder.cfg
features/openhab-addons/src/main/feature/feature.xml

Signed-off-by: digitaldan <dan@digitaldan.com>

Addes the Alarm Decoder binding to OH2 compatable bindings

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveProductDatabase.java

ZWave: Add extra checks in database code

---

bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBinding.java
bundles/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/hardware/HueBridge.java
distribution/openhabhome/configurations/openhab_default.cfg

Update pairing mechanism of hue binding to be compatible with new firmware

---

features/openhab-addons/src/main/feature/feature.xml

related to https://github.com/openhab/openhab/pull/4324

added dependency to serial transport

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java

Optional option added for command calendar: `caldavCommand:defaultItemOnBegin=<item>`
If the command-calendar contains items whose contents does not follow the `BEGIN/END:<item>:<value>` pattern AND a default item is specified, then the respective lines are interpreted as `BEGIN:<defaultItemOnBegin>:<line>`
This is really nice to use in combination with a rule such as described here: https://github.com/openhab/openhab/wiki/Controlling-openHAB-with-your-voice
Set the default item to: `caldavCommand:defaultItemOnBegin=VoiceCommand`
Then you can use the very same logic of your voice commands also in your calendar events (which should also improve the [WAF factor](https://en.wikipedia.org/wiki/Wife_acceptance_factor) ;-)).
Depending on your rule implementation, it is possible to use event …

Default item added to caldav command calendar.

---

bundles/binding/org.openhab.binding.intertechno/src/main/java/org/openhab/binding/intertechno/internal/CULIntertechnoBinding.java

Fixes #3987
Signed-off-by: Patrick Ruckstuhl patrick@ch.tario.org (github: tarioch)

Only send Intertechno settings if specified

---

bundles/binding/org.openhab.binding.zwave/database/nexia/db100z.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

https://github.com/openhab/openhab/issues/4280

ZWave Add next db100z

---

bundles/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmActiveBinding.java

[DSC Alarm] fixed NPE

---

bundles/binding/org.openhab.binding.zwave/database/nexia/db100z.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Fix errors with manufacturer data in database

---

bundles/action/org.openhab.action.pebble/.project

removed maven nature to remove ws errors

---

bundles/binding/org.openhab.binding.astro/.project
bundles/binding/org.openhab.binding.dscalarm/.project
bundles/binding/org.openhab.binding.harmonyhub/.project
bundles/binding/org.openhab.binding.homematic/.project
bundles/binding/org.openhab.binding.netatmo/.project

renamed legacy projects to be compatible with the IDE

---

bundles/binding/org.openhab.binding.powermax/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.powermax/build.properties

Signed-off-by: lolodomo lg.hc@free.fr

Added configuration meta-data for powermax binding

---

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComWindMessage.java

Add the average speed value for all wind sensors : cf #1922

RFXCOM Add Average speed for all wind sensors

---

distribution/openhabhome/configurations/openhab_default.cfg

See https://community.openhab.org/t/ecobee-3-setup/10413

[ecobee] Remove leading spaces to avoid confusion

---

bundles/binding/org.openhab.binding.ecobee/ESH-INF/binding.xml
bundles/binding/org.openhab.binding.ecobee/build.properties

[ecobee] Added config metadata to binding

---

bundles/binding/org.openhab.binding.zwave/database/ge/12727.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add GE12727

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/zse40.xml

ZWave database update

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgms001-32.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

ZWave Database Update - add FGMS001 V3.2

---

bundles/binding/org.openhab.binding.zwave/database/homeseer/hswd100.xml
bundles/binding/org.openhab.binding.zwave/database/homeseer/hsws100.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Z-Wave Database: 
- Added support for Homeseer HS-WS100 binary switch.
- Updated Homeseer HS-WD100 dimmer device configuration params to match documentation and added command classes based on auto-discovery/NIF.

Z-Wave: Homeseer HS-WS100, HS-WD100

---

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusGenericBindingProvider.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java

This is a new version of pull request https://github.com/openhab/openhab/pull/4291 . Please refer to the discussion there.
It is now configurable per slave whether an item change should be published on every update or only when the item value really changes.

Improved modbus item update handling

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved systeminfo binding to legacy add-ons

---

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Camera.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Thermostat.java

See [Nest API Release Notes](https://developers.nest.com/documentation/cloud/release-notes) for May 2016.

[nest] May 2016 API updates

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/tcp.cfg
features/openhab-addons/src/main/feature/feature.xml

[tcp] make installable from Paper UI

---

bundles/core/org.openhab.core.jsr223/src/main/java/org/openhab/core/jsr223/internal/engine/scriptmanager/ScriptManager.java

There was a small typo in the error message.

Typo corrected

---

bundles/binding/org.openhab.binding.zwave/database/ge/zw4002.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Z-Wave: 
- added GE In-Wall Smart Fan Control (ZW4002) to database

Z-Wave: added GE In-Wall Smart Fan Control (ZW4002)

---

bundles/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxBinding.java

Signed-off-by: Laurent Garnier lg.hc@free.fr

Freebox binding: fix phone calls handling (fix #4363)

---

bundles/binding/org.openhab.binding.fritzboxtr064/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.modbus.test/META-INF/MANIFEST.MF

fixed version in manifests

---

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java

made modbus binding compilable with Java 7

---

distribution/openhabhome/configurations/openhab_default.cfg

Updated the notes for the weather binding and added the woeid configuration attribute.

Updated notes and attributes for the weather binding.

---

bundles/binding/org.openhab.binding.zwave/database/enerwave/zwn-rsm2.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Updating XML definition as discussed in issue
https://github.com/openhab/openhab/issues/2595

Z-Wave: adding new device Enerwave ZWN-RSM2

---

bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java

See https://github.com/openhab/openhab/pull/4226#issuecomment-220678996
Test JAR [here](https://dl.dropboxusercontent.com/u/4286376/modbus-updated-method/org.openhab.binding.modbus-1.9.0-SNAPSHOT.jar).

[modbus] Only setProperlyConfigured when known

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/connection/KNXConnection.java
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/src/main/resources/conf/knx.cfg

Set up a configuration setting for Network Address Translation.
Should resolve #3629

[knx] Allow the use of Network Address Translation for connections.

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw100-17.xml

ZWave database update (ZW100)

---

features/openhab-addons-external/src/main/resources/conf/prowl.cfg
features/openhab-addons-external/src/main/resources/conf/twitter.cfg
features/openhab-addons/src/main/feature/feature.xml

added prowl and twitter actions

---

features/openhab-addons-external/pom.xml

I forgot adding this in https://github.com/openhab/openhab/pull/4420

added missing entries in pom.xml

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/nikobus.cfg
features/openhab-addons/src/main/feature/feature.xml

Have been using this binding in OH2 and seems to work fine.

Adding feature for Nikobus.

---

bundles/binding/org.openhab.binding.sonance/src/main/java/org/openhab/binding/sonance/internal/SonanceBinding.java
bundles/binding/org.openhab.binding.sonance/src/main/java/org/openhab/binding/sonance/internal/SonanceConsts.java

The manifacture recently added direct IP absolute volume commands, so
those are implemented. It required a specific firmware as described in
the Wiki of the binding.
Signed-off-by: Laurens Van Acker laurens-at-van-dot-acker-dot-be

Sonance binding: volume direct IP commands

---

features/openhab-addons/src/main/feature/feature.xml

added xbmc config file to feature

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/lgtv.cfg
features/openhab-addons/src/main/feature/feature.xml

[Forum thread](https://community.openhab.org/t/installing-lgtv-bundle-in-oh2-fails/7948).

[lgtv] Make installable from Paper UI

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveClockConverter.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveClockCommandClass.java

ZWave addition of clock command class

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

Include Aeon ZW112 - Door/Window Sensor 6

---

distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/src/main/resources/conf/modbus.cfg

- advanced connection parameters documented as comments
- added serial slave example as comments
Fixes #4486

Updated modbus config template

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveConverterHandler.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java

Update clock command class and converter

---

features/openhab-addons/src/main/feature/feature.xml

[mqtt] Add openhab-action-mqtt feature for OH2 install

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/mochadx10.cfg
features/openhab-addons/src/main/feature/feature.xml

Add mochadX10 binding to OH2 distro

[mochadx10] Add binding to OH2 distro

---

bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/MonitorSessionThread.java
bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OpenWebNet.java
bundles/binding/org.openhab.binding.bticino/src/main/java/com/myhome/fcrisciani/connector/MyHomeJavaConnector.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoDevice.java

Added support for INCREASE, DECREASE and PERCENT type commands for
lighting.
Added some log messages.
Corrected a few typos and grammar issues.
Should resolve #4438. Tested by @e4glenight.

[Bticino] Add additional lighting support.

---

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

I can not fix the formatter issue, I give up! The changed lines are (in the updated file):
70, 80, 155-167, 595-623
Signed-off-by: Karel Goderis <karel.goderis@me.com>

RRD4j - remove dependency on TimerTasks

---

features/pom.xml

updated ESH version to 0.9.0-SNAPSHOT

---

bundles/binding/org.openhab.binding.smarthomatic/src-gen/main/java/readme.txt

Delete erroneously created readme.

---

bundles/binding/org.openhab.binding.davis/src/main/java/org/openhab/binding/davis/datatypes/DataTypeBarometricTrend.java
bundles/binding/org.openhab.binding.frontiersiliconradio/src/main/java/org/openhab/binding/frontiersiliconradio/internal/FrontierSiliconRadioBinding.java
bundles/binding/org.openhab.binding.intertechno/src/main/java/org/openhab/binding/intertechno/internal/parser/REVParser.java
bundles/binding/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubGenericBindingProvider.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/DigitalActorDigitalOut4Impl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/DigitalActorIO16Impl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/DigitalActorIO4Impl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickDCImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletLEDStripImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletSolidStateRelayImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MDualRelayImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MIndustrialQuadRelayImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MLCD20x4BacklightImpl.java
bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MServoImpl.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveThermostatFanModeCommandClass.java

Fix a bunch of 'unknown' misspellings.

---

distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/src/main/resources/conf/modbus.cfg

Just some small fixes in the config files.

Fixed some spelling & copy+paste mistakes in modbus config

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveCentralSceneConverter.java

Z-Wave: fixed central scene converter to implement correct central scene command class interface

Z-Wave: fixed central scene converter

---

bundles/binding/org.openhab.binding.autelis/.project

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

Renames the eclipse project for the 1.x version of the autelis binding

---

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProviderTest.java
bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/config/KNXBindingProvider.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/bus/KNXBinding.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

A solution for issue #635 to support dimming with start/stop telegrams (DPT 3.007).

KNX start/stop dimming #635

---

bundles/action/org.openhab.action.squeezebox/src/main/java/org/openhab/action/squeezebox/internal/Squeezebox.java

Fixes issue: https://github.com/openhab/openhab/issues/4560
Signed-off-by: Brett Jenkins <brett@brettjenkins.co.uk> (github: brettyj)

Fix for SqueezeboxSpeak volume.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

ZWave update kfob codes

---

bundles/binding/org.openhab.binding.onkyo/.project
features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

made Onkyo binding 1.x legacy as there is now a 2.0 version

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/ConverterFactory.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/ConverterType.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/property/FeetConverter.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/property/JsonStandardDateConverter.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Clouds.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Condition.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Precipitation.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/ProviderName.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Station.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Weather.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/parser/AbstractWeatherParser.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/MeteoBlueProvider.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherProviderFactory.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/utils/UnitUtils.java
bundles/binding/org.openhab.binding.weather/src/main/resources/weather/common-id-mappings.xml

Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>
New Weather provider: https://www.meteoblue.com

Added new weather provider: MeteoBlue

---

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBinding.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java

This PR introduces some minor changes in thread management.

[satel] Thread interruption changes.

---

bundles/binding/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpGenericBindingProvider.java

[+] snmp binding: added remote port support via url ("ip/port" with specified port or just "ip" with default 161 port). I use "/" symbol instead ":" because do not want to change schemes `(a:b:c:...)`
[-] snmp binding: fixed version/url parameters order in OUT_BINDING_PATTERN_VERSION. Second parameter was version, but the code expects address
For now, you can configure only listening port. Remote port hardcoded as 161.
Current patch allows manual remote port setting.

snmp binding: added remote port support via url and OUT_BINDING_PATTERN_VERSION bugfix

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveConfigurationCommandClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java

ZWave fix bug setting parameter to write_only

---

bundles/io/pom.xml
features/openhab-addons/src/main/feature/feature.xml

Removed mary tts from features as it is now part of OH2.

---

bundles/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmniLinkBinding.java

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

Adds Aux messages, catches errors when generating items.

---

bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/config/IntegraStateBindingConfig.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/DoorsControl.java
bundles/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/ZoneControl.java

This PR adds ability to:
- bypass a zone,
- unbypass a zone,
- isolate a zone,
- open doors.

[satel] Added ability to control zones and doors

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw098.xml
bundles/binding/org.openhab.binding.zwave/database/leviton/vri10-1lz.xml
bundles/binding/org.openhab.binding.zwave/database/linear/wdz500-1.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/config/ZWaveDbCommandClass.java
bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeStageAdvancer.java

Update database and add handling of versions

---

bundles/binding/org.openhab.binding.zwave/database/philio/pan03.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Added zwave devic description for Zipato Philio PAN03 module.
Refrence is https://www.zipato.com/wp-content/uploads/2015/09/ph-pan03-Zipato-Micromodule-Single-Switch-Max.Load-11A-User-Manual-v1.0.pdf .

Added ZWave Philio PAN03 1x3.0kW meter/switch

---

bundles/io/pom.xml

re-enabled the build of the TTS bundles

---

bundles/binding/org.openhab.binding.plugwise/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.plugwise/build.properties
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/plugwise.cfg
features/openhab-addons/src/main/feature/feature.xml

While implementing #4565 I've done a lot of testing with the Plugwise Binding on OH2. So here are the OH2 feature addon and binding definition.

[Plugwise] Add openHAB 2 feature addon

---

bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

Added a new version of the 8-button mini remote 2342-222 for the insteonplm binding.
https://community.openhab.org/t/insteon-2342-2-8-button-remote-issues/13226/7
I don't have the device to test, but it should work (see above link), and the commit is low risk.

insteonplm binding: added mini remote 2342-222

---

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Structure.java

[nest] Fixes #4635

---

bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/Connection.java

and decrease one log entry to debug.

[garadget] Remove misleading text on exception logs

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgfs101-32.xml
bundles/binding/org.openhab.binding.zwave/database/popp/009402.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Database update

---

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Circle.java

When you have a lot of Circles they may not all get calibrated at startup. Either the `CalibrationRequestMessage` may never be received by a Circle, or the `CalibrationResponseMessage` may get lost. Also Circles may be offline during startup. As a result the 'current power' of an uncalibrated Circle will always remain 0 W. 
This PR fixes it by resending a `CalibrationRequestMessage` whenever a `PowerInformationResponseMessage` is received for an uncalibrated Circle.
Signed-off-by: Wouter Born <github@maindrain.net> (github: wborn)

[Plugwise] Fix Circles not always calibrated

---

bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/RpcCall.java
bundles/binding/org.openhab.binding.xbmc/src/main/java/org/openhab/binding/xbmc/rpc/XbmcConnector.java

[xbmc] Minor formatting

---

bundles/io/org.openhab.io.net/src/main/java/org/openhab/io/net/http/HttpUtil.java

Hopefully this commit was done properly into my own fork...

Fix #4665 by emitting an error when an HTTP command fails to be created.

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/ipx800.cfg
features/openhab-addons/src/main/feature/feature.xml

Compatibility against OH2 has been verified. Everything's ok.

[ipx800] Allow installation from Paper UI

---

bundles/persistence/org.openhab.persistence.dynamodb.test/META-INF/MANIFEST.MF
bundles/persistence/org.openhab.persistence.dynamodb.test/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java

Fixes Java7 compatibility issues in dynamodb tests. See PR #4542 for the original discussion
ping @9037568

[dynamodb] Java 7 compatibility fixes in tests

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/qubino/zmnhid.xml

Add ZMNHID

---

bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBinding.java
bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/Stick.java
bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/InitialiseResponseMessage.java
bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/protocol/NodeAvailableResponseMessage.java

Fixes:
* Locks that are not released when exceptions occur
* Potential NPEs
* Wrong String.format parameters
Signed-off-by: Wouter Born <github@maindrain.net>

[Plugwise] FindBugs issues fix

---

bundles/binding/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MpdGenericBindingProvider.java

First part to solve issue #3060

[mpd] respect playerId in getItemNamesByPlayerAndPlayerCommand

---

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModelResponse.java

Per @mrguessed's suggestion [here](https://community.openhab.org/t/nest-binding-updates/15536/12?u=watou).
Test JAR can be found [here](https://dl.dropboxusercontent.com/u/4286376/nest-400-error-message/org.openhab.binding.nest-1.9.0-SNAPSHOT.jar).

[nest] Log error returned in request for data model if there was an error.

---

bundles/binding/org.openhab.binding.knx.test/.classpath

calimero-core-2.2.0-SNAPSHOT.jar -> calimero-core-2.3-beta.jar
Addition to #4724

corrected link to calimero:

---

bundles/persistence/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

See issue #4734 and community discussion https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761/126

influxdb: change default retention policy name to "autogen"; honour retention policy in queries

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java

Also replaced a couple occurrences of string concatenation with parameterized log calls.

Fixed some typos in jdbc log messages.

---

bundles/binding/org.openhab.binding.zwave/database/ge/zw6302.xml

Fix ZW6302 definition

---

bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java

multiple "CATEGORIES" lines can be present in an event. Added a loop to
iterate all of the lines matching (instead of the first line previously)
fixes #4764

correction of issue #4764

---

bundles/binding/org.openhab.binding.samsungac/src/main/java/org/openhab/binding/samsungac/internal/AirConditioner.java
bundles/binding/org.openhab.binding.samsungac/src/main/java/org/openhab/binding/samsungac/internal/SamsungAcBinding.java
bundles/binding/org.openhab.binding.samsungac/src/main/java/org/openhab/binding/samsungac/internal/SsdpDiscovery.java

Also replaced a few writes to System.out with logger calls.
Signed-off-by: John Cocula john@cocula.com

[samsungac] Allow port to be specified in cfg other than default 2878

---

bundles/persistence/org.openhab.persistence.jdbc/ESH-INF/config/config.xml

https://github.com/openhab/openhab/issues/4671

Changing 'user' and 'password' to optional parameters in PaperUI

---

bundles/binding/org.openhab.binding.garadget/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.garadget/build.properties

To address forum comment [here](https://community.openhab.org/t/garadget-binding/7650/23?u=watou).

[garadget] add config metadata

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveSecurityCommandClass.java

keep a whitelist of which command classes it should be applied to.

ZWave: Secure duplicate message check was being applied to broadly; changed logic to

---

pom.xml

Eliminate excessive messages during OSGi driver activation.
Closes #4779
Signed-off-by: John Holland jotihojr@gmail.com (github: jotihojr)

Bump jdbc postgressql 9.4 version to 1212

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java

Allow OH1 to use databases with no username/password, same as OH2 (see #4671).
Also reduced nesting within the updateConfig() method in JdbcConfiguration.

Updated OH1 JDBC to allow databases with no username and password.

---

bundles/binding/org.openhab.binding.nest/ESH-INF/binding/binding.xml

added service id to binding configuration description

---

bundles/binding/org.openhab.binding.zwave/database/products.xml

[zwave] Added another ID for Trane Thermostat

---

bundles/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/config/DmxItem.java

[dmx] allow newline and tab inside of dmx binding config

---

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

I'm sorry for the reformatting. Did the Eclipse settings change regarding the trailing spaces?

[knx] adds DPT 6 / Signed 8bit (feature request #4095) and unit tests

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved exec binding to the legacy add-ons

---

bundles/binding/org.openhab.binding.garadget/src/main/java/org/openhab/binding/garadget/internal/GaradgetBinding.java

Fixes problem reported [here](https://community.openhab.org/t/garadget-binding/7650/54?u=watou).

[garadget] stop command is actually stopped

---

bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java

This changes support the new (and still support current/old) message format 
This commit was already checked by @Speederc  on #4150

rfxcom : support for new interface message for firmware >= 1001

---

bundles/binding/org.openhab.binding.expire/.classpath
bundles/binding/org.openhab.binding.expire/.gitignore
bundles/binding/org.openhab.binding.expire/.project
bundles/binding/org.openhab.binding.expire/.settings/org.eclipse.jdt.core.prefs
bundles/binding/org.openhab.binding.expire/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.expire/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.expire/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.expire/build.properties
bundles/binding/org.openhab.binding.expire/pom.xml
bundles/binding/org.openhab.binding.expire/src/etc/header.txt
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/ExpireBindingProvider.java
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/internal/ExpireBinding.java
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/internal/ExpireGenericBindingProvider.java
bundles/binding/org.openhab.binding.upb/.settings/org.eclipse.core.resources.prefs
bundles/binding/org.openhab.binding.upb/.settings/org.eclipse.jdt.core.prefs
bundles/binding/pom.xml

expire="12h30m50s". This binding will set the state to Undefined if it's
not updated within the given time.

New "expire" binding. Just add to your item: expire="10s" or

---

bundles/binding/org.openhab.binding.fritzbox/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.fritzbox/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.fritzbox/build.properties
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/fritzbox.cfg
features/openhab-addons/src/main/feature/feature.xml

added fritzbox binding to the OH2 distro

---

bundles/binding/org.openhab.binding.fritzboxtr064/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.fritzboxtr064/OSGI-INF/genericbindingprovider.xml
bundles/binding/org.openhab.binding.fritzboxtr064/README.md
bundles/binding/org.openhab.binding.fritzboxtr064/build.properties
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallEvent.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallMonitor.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064Binding.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Helper.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhoneBookEntry.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/fritzboxtr064.cfg
features/openhab-addons/src/main/feature/feature.xml

made fritzboxtr064 binding compatible with OH2

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/tkb/tz69.xml

Add TZ69 to ZWave database

---

bundles/binding/org.openhab.binding.expire/.classpath
bundles/binding/org.openhab.binding.expire/.settings/org.eclipse.jdt.core.prefs
bundles/binding/org.openhab.binding.expire/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.expire/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.expire/pom.xml
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/ExpireBindingProvider.java
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/internal/ExpireBinding.java
bundles/binding/org.openhab.binding.expire/src/main/java/org/openhab/binding/expire/internal/ExpireGenericBindingProvider.java
bundles/binding/pom.xml
features/openhab-addons/src/main/feature/feature.xml

small bug fixes, re-added to parent pom.xml

[expire] Remove Java 1.8 dependency; add command support, minor refactoring

---

bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavConfig.java

Correct build error introduced by https://github.com/openhab/openhab/pull/4766.

Fix caldav-personal hashCode usage.

---

features/openhab-addons/src/main/feature/feature.xml

fixed feature references after renaming

---

bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/AbstractDevice.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/AlarmState.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Camera.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/DataModel.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/SmokeCOAlarm.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Structure.java
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Thermostat.java

Updates to the Nest binding to match the [November 2016 API Update](https://developers.nest.com/documentation/cloud/release-notes).

[nest] November 2016 API Update

---

bundles/binding/org.openhab.binding.onewire/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBindingConfigFactory.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireGenericBindingProvider.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/connection/OneWireConnection.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyBindingConfig.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyWritableBindingConfig.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/scheduler/OneWireUpdateScheduler.java
distribution/openhabhome/configurations/openhab_default.cfg

Fixes #4859.
Also converted log messages to parameterized calls.

Update the onewire binding to retry failed connections.

---

features/openhab-addons/src/main/feature/feature.xml

See forum discussion [here](https://community.openhab.org/t/we-need-your-help-on-testing/298/164?u=watou).

[satel] Add action feature for OH2

---

bundles/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBinding.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/Eiscp.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpEventNotifier.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpInterface.java
bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpSerial.java

Added serial port support for Onkyo receivers

[onkyo] Added Serial port support

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/scheduler/WeatherJobScheduler.java

Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

Weather: Fixed exception during scheduler restart

---

distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/gcal-persistence.cfg
features/openhab-addons-external/src/main/resources/conf/gcal.cfg
features/openhab-addons/src/main/feature/feature.xml

Signed-off-by: Mark Hilbush <mark@hilbush.com>

[gcal] Add io and persistence feature to OH2

---

bundles/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5MessageTest.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java

Add support for IT message to support the Flamingo FA500 and others
Running it in my production env since the 24th of november, this month it will be switching the christmas lights ;-)
Fixes https://github.com/openhab/openhab2-addons/issues/1019

Add support for IT message to support the Flamingo FA500 and others

---

bundles/binding/org.openhab.binding.plex/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.plex/build.properties
bundles/binding/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexBinding.java
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/plex.cfg
features/openhab-addons/src/main/feature/feature.xml

This PR adds a feature for the Plex binding and makes it configurable in the Paper UI.

Feature for Plex binding

---

bundles/binding/org.openhab.binding.panasonictv/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.panasonictv/build.properties
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/panasonictv.cfg
features/openhab-addons/src/main/feature/feature.xml

Add panasonictv binding to compatible 1.x addons

---

bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java
distribution/openhabhome/configurations/openhab_default.cfg

This fixes an issue #4038 where it takes 5 minutes for Netatmo items to get the initial values. Implemented solution similar to what @watou implemented for Ecobee

Netatmo: fix for issue #4038

---

bundles/io/org.openhab.io.openhabcloud/OSGI-INF/openhabcloud.xml
bundles/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudServiceImpl.java

Fixes [this issue](https://community.openhab.org/t/myopenhab-replaces-my-openhab/18258/86?u=kai)

refactored openhabcloud connector bundle to also push auto-update state changes to the cloud

---

bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoBinding.java
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/bticino.cfg
features/openhab-addons/src/main/feature/feature.xml

Based on [feedback](https://community.openhab.org/t/bticino-oh2/18363/4?u=watou) that it works under openHAB 2.

[bticino] Add to openHAB 2

---

features/pom.xml

upgraded Karaf to 4.0.8

---

bundles/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java
bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java

Enabled the Contact and Signal level outputs for Lighting4 and added tests for Lighting4
@Jamstah sorry I will have less time to develop in the new year ;-)

Enabled the Contact and Signal level outputs for Lighting4

---

features/openhab-addons-external/src/main/resources/conf/netatmo.cfg

This was accidentally missed with PR https://github.com/openhab/openhab/pull/4906.

netatmo: added new paramteter for oh2 config file

---

bundles/io/org.openhab.io.squeezeserver/src/main/java/org/openhab/io/squeezeserver/SqueezeServer.java
distribution/openhabhome/configurations/openhab_default.cfg

Add capability to retry failed connections at startup.
Fixes #4611.

[Squeezebox] Add capability to retry failed connections at startup

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgs222.xml

@cdjackson most likely unrelated but while searching I found one

Corrected CDATA tag for  Z-Wave device

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zooz/zse40.xml

Related to https://community.openhab.org/t/zooz-zse40-4-in-1-sensor/8174/23.

Add new Mfg/Device ID for Zooz 4-in-1 sensor

---

bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java

Again, there is a lot of reformatting. The only change besides that is in l. 238.
This fixes the data points with too early (#4559) or too late timestamps. However, it can still happen that the last datapoint/timestamp is duplicated. This outside the scope of the RRD4J binding but must be fixed in the REST implementation.
There are a lot of warning (e.g. l. 169) about wrong type casts in the logger. Can someone with deeper JAVA knowledge advice on that?

[RRD4J] Fix rrd interval #4559

---

bundles/binding/org.openhab.binding.denon/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonBinding.java
bundles/binding/org.openhab.binding.denon/src/main/java/org/openhab/binding/denon/internal/DenonConnector.java

Avoid a null pointer exception in 4777.
Enhance logging a bit and eliminate noisy failure in 3243.

Denon: Enhancements/fixes for #3243 and #4777.

---

bundles/binding/org.openhab.binding.http/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.http/build.properties
bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java

[http] Configure binding from Paper UI

---

bundles/binding/org.openhab.binding.zwave/database/aeon/mses.xml
bundles/binding/org.openhab.binding.zwave/database/aeon/zw056.xml
bundles/binding/org.openhab.binding.zwave/database/aeon/zw096.xml

mses.xml modified in database
zw056.xml modified in database
zw096.xml modified in database
Each of these were edited in the online database and this is the resulting OH1 export.

Updated 3 Aeon Labs devices

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

fixed some issues in feature definitions

---

bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200SwitchProgramService.java

+ Add a new cycle with the max. cycle number +1 (only to the end)
+ Delete a cycle if both cwitching points are set to max time (1430Min., only the last one)

Added the capability to add and remove switch cycles

---

bundles/persistence/org.openhab.persistence.jpa/java/org/openhab/persistence/jpa/internal/JpaConfiguration.java
bundles/persistence/org.openhab.persistence.jpa/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java

Reduce the severity of a couple of log messages to DEBUG to avoid unneeded alarums.
Fixes #4959.

[Jpa] Lower severity of a couple of log messages

---

bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyBindingConfig.java
bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/deviceproperties/AbstractOneWireDevicePropertyWritableBindingConfig.java

[Onewire] Restore mistakenly dropped imports.

---

bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveBatteryCommandClass.java

[ZWAVE] Reduce battery low log message from WARN to DEBUG.

---

bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Binding.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Comm.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ErrorService.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200GenericBindingProvider.java

* New virtual subservice errorString. This is returning a string with all error parameters
* New virtual subservice nbrErrors and error to check the number of errors and choose the error number for the error string output.
* Some code cleanup (if/switch replacements)

Added handling for error lists (usually /notifications service)

---

bundles/binding/org.openhab.binding.asterisk/src/main/java/org/openhab/binding/asterisk/AsteriskBindingProvider.java
bundles/binding/org.openhab.binding.asterisk/src/main/java/org/openhab/binding/asterisk/internal/AsteriskBinding.java
bundles/binding/org.openhab.binding.asterisk/src/main/java/org/openhab/binding/asterisk/internal/AsteriskGenericBindingProvider.java

[Asterisk] Clean up formatting and convert log message to parameterized.

---

bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRBinding.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRPort.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRPortSettings.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/cosem/CosemDate.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/messages/OBISMessage.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/messages/OBISMsgFactory.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/messages/OBISMsgType.java
bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/p1telegram/P1TelegramParser.java

- Added DSMR port settings (fixes issue #4175)
- Quicker poll rate (fixes issue #4792 - overflow)
- Added actual voltage messages (fixes issue #4792 - unsupported
messages)

[dsmr] Fixes for issue #4175 and #4792

---

bundles/binding/org.openhab.binding.km200/.project
bundles/binding/org.openhab.binding.km200/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.km200/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.km200/build.properties
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Binding.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Comm.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ErrorService.java
bundles/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200SwitchProgramService.java
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/km200.cfg
features/openhab-addons/src/main/feature/feature.xml

[km200] Bug fixes; install/config in OH2

---

bundles/binding/org.openhab.binding.http.test/src/test/java/org/openhab/binding/http/internal/HttpGenericBindingProviderTest.java
bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpGenericBindingProvider.java

Add new test for same.
Fixes #4992.

[HTTP binding] Fix logic for handling headers in binding config.

---

bundles/io/org.openhab.io.harmonyhub/src/main/java/org/openhab/io/harmonyhub/HarmonyHubDiscovery.java
bundles/io/org.openhab.io.harmonyhub/src/main/java/org/openhab/io/harmonyhub/HarmonyHubGateway.java

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

adds optional host to help with discovery across subnets

---

bundles/binding/org.openhab.binding.zwave/database/leviton/vrcs4-m0z.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

[Z-Wave] Added Leviton VRCS4-M0Z

---

bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
bundles/persistence/pom.xml
distribution/pom.xml

Attempt to fix #5030
Also restores building of dynamodb (reverts f7787764b93748c2e8465a697b7f0688c424acb8)

[dynamodb] java8 compatibility

---

bundles/binding/org.openhab.binding.zwave/database/aeon/zw056.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/zooz/zen06.xml

Added Zooz ZEN06 Smart Plug
Updated paramter 43 of aeon/zw056.xml to include unknown value

zwave updates

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/schlage/be469.xml

Added the Schlage BE469 Touschscreen deadbolt lock.  Added reference section to products.xml and created new be469.xml.  http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devices with a changes to the <Help [[... tags

Added to device database,  Schlage BE469 Touschscreen deadbolt lock

---

bundles/binding/org.openhab.binding.km200/README.md

Added the first version of the README.md file (created from wiki).

First version of the README.md file

---

bundles/binding/org.openhab.binding.anel/README.md

Fix parsed title, clarified first paragraph.

[anel] Update README.md

---

bundles/binding/org.openhab.binding.weather/README.md

[weather] Markdown fixes to README.md

---

bundles/binding/org.openhab.binding.exec/README.md

[exec] Improve clarity, give examples in context

---

bundles/action/org.openhab.action.nma/README.md

Add all NMA signature methods in order to provide all possible choices regarding user needs.

Add missing signatures description for NMA calls

---

bundles/binding/org.openhab.binding.iec6205621meter/OSGI-INF/binding.xml
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/Iec6205621MeterBindingProvider.java
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/Iec6205621MeterActivator.java
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/Iec6205621MeterBinding.java
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/Iec6205621MeterGenericBindingProvider.java
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/Meter.java
bundles/binding/org.openhab.binding.iec6205621meter/src/main/java/org/openhab/binding/iec6205621meter/internal/MeterConfig.java

Update logging statements to use parameterized logging.
Convert config gets to use Objects.toString().
Eclipse formatting.

[IEC] Code cleanup

---

bundles/binding/org.openhab.binding.mqtt/README.md

Markdown fixes; improve clarity of where to configure different services.

[mqtt] Update README.md

---

bundles/binding/org.openhab.binding.piface/README.md
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/piface.cfg
features/openhab-addons/src/main/feature/feature.xml

Fixes #5032
Also improved doc to match code.

[piface] Add feature and config file

---

bundles/binding/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/EKeyBinding.java
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/ekey.cfg
features/openhab-addons/src/main/feature/feature.xml

Also small cleanups in binding source.
Fixes #5015

[ekey] add feature and config file

---

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ReadRegistersTestCase.java

Introducing test case for int32_swap. After this there is at least one test for the "swapped" data types of modbus binding.

[modbus] test for int32_swap valuetype

---

bundles/binding/org.openhab.binding.modbus/README.md

@ssalonen The Markdown renderer at docs.openhab.org is less forgiving than the one here, so I made some edits that should result in a legible and linkable version [here](http://docs.openhab.org/addons/bindings/modbus1/readme.html#writing-data).
Please update this file further with any outstanding PRs (and copy/paste to the old wiki if you want).
Thank you!

[modbus] Fixed README.md for docs site

---

bundles/binding/org.openhab.binding.modbus/README.md

[modbus] Fixed remaining formatting issues in README.md

---

bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletLCD20x4Impl.java

move setText method code to write method

---

bundles/binding/org.openhab.binding.myq/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.myq/README.md
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQResponseCode.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqBinding.java
bundles/binding/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyqData.java
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/src/main/resources/conf/myq.cfg

Fixed issues:#5096 and included fixes from previous pull request:#5052. Also updated README.md to better explain new 1.9 features.
Signed-off-by: Scott (github: computergeek1507 forum:scooter_seh)

Fixed issues:5096 and included fixes from previous pull request:5052

---

bundles/io/org.openhab.io.gcal/src/main/java/org/openhab/io/gcal/internal/GCalEventDownloader.java

See [discussion](https://community.openhab.org/t/gcal-bindings-refreshed-version/16400/55?u=watou).

[gcal] Fix misspellings of calendar

---

bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java

Updated pushover to allow the main pushover call to use default values when not supplied.
Signed-off-by: Chris Graham crackerstealth@gmail.com (github: CrackerStealth)

[Pushover] Default Value Usage Fix

---

bundles/binding/org.openhab.binding.zwave/database/sensative/strips11-01-011.xml

ZWave: Update sensitive strips database entry

---

bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java

Closes #5140
Signed-off-by: Martin Renner <martin+github@planet-renner.net>

Telegram.sendTelegram() now returns "false" if an exception is thrown.

---

bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/telldus/tzwp-100.xml

Add TZWP-100

---

bundles/binding/org.openhab.binding.enocean/README.md

The example did not work.
see also: https://community.openhab.org/t/getting-started-with-enocean-devices-configuration/5971/6
Signed-off-by: Christoph Wempe cw-git@wempe.net (github: CWempe)

[Wiki] correct Contact Sensors example

---

bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/SwegonVentilationCommandType.java
bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/protocol/SwegonVentilationDataParser.java

Swegon improvements

---

bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ConfigUpdatedTestCase.java
bundles/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/TestCaseSupport.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusSerialTransaction.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusTCPTransaction.java
bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPConnectionHandler.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSlave.java
bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java

Also regression test introduced.
Fixes #5078
Signed-off-by: Sami Salonen <ssalonen@gmail.com>
Pre-compiled version for testing available below in the [new comment](https://github.com/openhab/openhab1-addons/pull/5088#issuecomment-279857656)
(old download link for reference
```
( _Old buggy version (4ef8d43): [org.openhab.binding.modbus-1.10.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab1-addons/files/772494/org.openhab.binding.modbus-1.10.0-SNAPSHOT.jar.zip)_ )
````
)

[modbus] Eventually close borrowed connections also when config changes

---

bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java

Eliminate null pointer exceptions caused by null event summaries.
Fixes #5008

[CalDAV] Avoid null pointer exceptions in the loadEvents() method

---

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java

Added a couple new items that work with the 5030UB projector

[epsonprojector] Add additional ColorMode and AspectRatio values (from 5030UB projector)

---

bundles/binding/org.openhab.binding.serial/README.md
bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java
bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java

Modified Serial binding for ON/OFF commands to be used in conjunction with Switch item (faster). 
This can also be used with a Switch configured as a button (using mappings)

[Serial] Modified Serial binding for ON/OFF commands

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java

Tested: the thermostat works with this fix. Whether it still works for the smoke bridge I don't know since I don't own the device.

insteonplm: fixed bug introduced with PR #5054

---

bundles/binding/org.openhab.binding.enocean/build.properties

[Enocean] Removed the unneeded 'additional.bundles' property.

---

bundles/binding/org.openhab.binding.satel/README.md

[satel] Documentation updated

---

bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/InsteonDevice.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageDispatcher.java
bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml

This fixes a bug reported here:
https://community.openhab.org/t/insteon-manualchange-event-not-recognised-correctly-oh2/26728/8
Here is the link to a jar file that should be a drop-in for OH 1.8:
https://drive.google.com/file/d/0B8OtzwATWQSWdThWRWttOFBCVUU/view?usp=sharing

insteonplm: fixed bug with start/stop manual change

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java

[weather] Added converter mps -> km/h to OpenWeatherMap wind speed property

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java

Signed-off-by: Andrew Nagle <kabili@zyrenth.com>

[weather] Add feels like temperature for ForecastIO

---

bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/CalDavBindingProvider.java
bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavActivator.java
bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBinding.java
bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavBindingProviderImpl.java
bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavNextEventConfig.java
bundles/binding/org.openhab.binding.caldav-command/src/main/java/org/openhab/binding/caldav_command/internal/CalDavType.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/EventUtils.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/EventStorage.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/Util.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java

Allow the Unicode Line Separator character to serve as a line delimiter for commands.
For #4355.

[CalDAV] Allow the Unicode Line Separator character

---

bundles/binding/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpBinding.java

Fixed Memory leak in SNMP Binding

5202 snmp memory leak fix

---

bundles/binding/org.openhab.binding.isy/.project
bundles/binding/org.openhab.binding.mcp23017/.project
bundles/binding/org.openhab.binding.mcp3424/.project
bundles/binding/org.openhab.binding.upb/.project

removed m2e nature to avoid errors in the IDE

---

features/openhab-addons-verify/pom.xml

removed esh addons from feature verification

---

pom.xml

This should fix the broken build (https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1474/) again.

updated dependencies for correctly resolving the target platform

---

bundles/binding/org.openhab.binding.s300th.test/.settings/org.eclipse.jdt.core.prefs

fixed source level config

---

features/openhab-addons-verify/pom.xml
pom.xml

updated feature verification configuration

---

bundles/pom.xml
distribution/pom.xml
features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml
features/pom.xml
pom.xml

Use openhab-core parent pom for build configuration

---

bundles/binding/org.openhab.binding.maxcul/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.maxcul/build.properties
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/maxcul.cfg
features/openhab-addons/src/main/feature/feature.xml

Tested OH1 maxcul binding with OH2 and added the feature description for this binding

Max! CUL compatibility for OpenHAB2

---

bundles/binding/org.openhab.binding.iec6205621meter/ESH-INF/binding/binding.xml
bundles/binding/org.openhab.binding.iec6205621meter/build.properties
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/iec6205621meter.cfg
features/openhab-addons/src/main/feature/feature.xml

add tested IEC 62056-21 meter 1.x version to OH2

---

bundles/binding/org.openhab.binding.zwave/database/popp/pope700168.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Add ZWave Popp rain

---

bundles/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/MCP23017Binding.java

Made mcp23017 binding start even if native libraries cannot be loaded

---

bundles/binding/org.openhab.binding.caldav-command/README.md

Closes: https://github.com/openhab/openhab1-addons/issues/5248

[Caldav] Readme enhancements

---

bundles/binding/org.openhab.binding.snmp/README.md

extended the item configuration, displaying of String items works fine.
Fixes #5251

[SNMP] Update README.md to show support for String items

---

bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OWNUtilities.java

Formatting and add comments

---

bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OWNUtilities.java

Clean up the formatting, per the Eclipse formatter.

[bticino] Formatting fixes.

---

bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OWNUtilities.java
bundles/io/pom.xml
features/pom.xml

Fix bad encoding value in pom files

---

features/pom.xml

Should hopefully make the build pass again.

updated ohc version

---

bundles/binding/org.openhab.binding.http/README.md

* Added `HTTP Basic authentication` section

[http] Updated README.md - Added `HTTP Basic authentication` section

---

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java

[Anel] Compatibility with Anel Firmware 6.1.

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgkf601.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

ZWave: Add Fibaro key fob

---

bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java
bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java

Also eliminated compiler warnings and cleaned up log messages.
Fixes #5272.

[CalDav] Fix problem with resource paths containing curly braces.

---

bundles/binding/org.openhab.binding.nest/.project
features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved nest 1.x binding to legacy addons

---

bundles/persistence/org.openhab.persistence.mysql/java/org/openhab/persistence/mysql/internal/MysqlPersistenceService.java

[mySQL persistence] Fix a few inconsistencies in log messsages.

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java

[weather] Added mapping for OpenWeatherMap for channel 'gust'

---

bundles/binding/org.openhab.binding.withings/README.md
bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAccount.java
bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAuthenticator.java

It appears a number of updates to the binding code were never documented properly. This should improve the README.
Fixes #5281.

[Withings] Fix some problems with the README.

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved tellstick binding to legacy add-ons

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved DMX binding to legacy add-ons

---

bundles/binding/org.openhab.binding.zwave/database/fibaro/fgdw002.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml
bundles/binding/org.openhab.binding.zwave/database/vision/pid15903.xml
bundles/binding/org.openhab.binding.zwave/database/vision/yrd220.xml
bundles/binding/org.openhab.binding.zwave/database/yale/yrd220.xml

Add new ZWave devices FGDW002 and PID15903

---

bundles/io/org.openhab.io.dropbox/META-INF/MANIFEST.MF
bundles/io/org.openhab.io.dropbox/OSGI-INF/synchronizer.xml
bundles/io/org.openhab.io.dropbox/README.md
bundles/io/org.openhab.io.dropbox/build.properties
bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxActivator.java
bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxService.java
bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxSyncMode.java
bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxSynchronizer.java
bundles/io/org.openhab.io.dropbox/src/main/java/org/openhab/io/dropbox/internal/DropboxUtils.java

This required only setting non-null values for the appKey and appSecret
that would be acceptable to the com.dropbox API.
Fixes #5246

Fixed the Dropbox startup failure

---

bundles/binding/org.openhab.binding.weather/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/parser/AbstractWeatherParser.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/parser/JsonWeatherParser.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/parser/WeatherParser.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java

[weather] Replaced org.apache.commons.httpclient dependency with ESH HttpUtil

---

bundles/binding/org.openhab.binding.rwesmarthome/README.md

Signed-off-by: Oliver Kuhl oliver.kuhl@gmail.com (github: ollie-dev)

Added warning regarding TLSv1 configuration to README

---

bundles/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRBinding.java

fixed compilation error in IDE

---

bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/SwegonVentilationBinding.java
bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/protocol/SwegonVentilationConnector.java
bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/protocol/SwegonVentilationUDPConnector.java

Added support for RAW PDU which allows to use any serial port UDP converters.

[Swegon] Support for RAW PDUs

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java

[weather] Added NPE safe-guard if HTTP request fails

---

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBinding.java

[epson] Fixed logging

---

bundles/action/org.openhab.action.pushbullet/.classpath
bundles/action/org.openhab.action.pushbullet/.project
bundles/action/org.openhab.action.pushbullet/META-INF/MANIFEST.MF
bundles/action/org.openhab.action.pushbullet/OSGI-INF/action.xml
bundles/action/org.openhab.action.pushbullet/README.md
bundles/action/org.openhab.action.pushbullet/about.html
bundles/action/org.openhab.action.pushbullet/build.properties
bundles/action/org.openhab.action.pushbullet/pom.xml
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletAPIConnector.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletActionService.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletActivator.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletBot.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletConstants.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/model/Push.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/model/PushError.java
bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/model/PushResponse.java
bundles/action/org.openhab.action.pushbullet/src/main/resources/readme.txt
bundles/action/pom.xml
features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/pushbullet.cfg
features/openhab-addons/src/main/feature/feature.xml

I have used this action for quite some time locally in my OH2 setup. @kubawolanin reported success, too.
Topic: https://community.openhab.org/t/pushbullet-binding-and-action/3409/34?u=hakan
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>

[pushbullet] initial action contribution

---

bundles/binding/org.openhab.binding.zwave/database/fireangle/zst630.xml
bundles/binding/org.openhab.binding.zwave/database/products.xml

Also reformatted the main products file using Eclipse so it's a common format.

Add Z-Wave Fireangle ZST630

---

bundles/binding/org.openhab.binding.anel/README.md
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelCommandType.java
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java
bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelState.java

The AnelDataParser is growing, so I refactored it a little bit to enhance readability.
New read-only Anel binding items:
- SENSOR_TEMPERATURE
- SENSOR_HUMIDITY
- SENSOR_BRIGHTNESS
Fixes #5338.

Support for Anel sensor data as discussed in #5338.

---

bundles/action/org.openhab.action.pushover/README.md

The changes reflect this PR:
https://github.com/openhab/openhab1-addons/pull/5123
Signed-off-by: Siegfried Huismann >sihui@gmx.de>

Update README.md for Pushover action

---

bundles/binding/org.openhab.binding.zwave/database/fireangle/zst630.xml

Update ZST-630 association groups

---

bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatpumpConnector.java

Also did some minor cleanup of logging statements.
Fixes #5377.

[NovelanHeatpump] Prevent null pointer exceptions during disconnect.

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java

The relevant code change is only line 189.

avoid NPE and applied code formatter

---

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallMonitor.java

reduced logging level as we already log success/failure anyhow

---

pom.xml

Add snapshot repository on distributionManagement

---

bundles/action/org.openhab.action.telegram/README.md

With chat.id it's also possible to add the bot to a group

[Telegram] Correct chat id in README.md for Telegram action

---

bundles/binding/org.openhab.binding.lgtv/src/main/java/org/openhab/binding/lgtv/lginteraction/LgTvMessageReader.java

Also cleaned up and improved logging.
Fixes #5381.

[LgTv] Trap IllegalArgumentException during deactivate()

---

bundles/binding/org.openhab.binding.caldav-personal/src/main/java/org/openhab/binding/caldav_personal/internal/CalDavBinding.java

[CalDav] Fix NPE during updateItemsForEvent

---

README.md

Signed-off-by:Brad Gilmer <brad@gilmer.tv>

[Intro] Correct linter errors only

---

bundles/action/org.openhab.action.ciscospark/README.md

[Ciscospark] Correct linter errors only

---

bundles/action/org.openhab.action.dscalarm/README.md

- Signed-off-by: Brad Gilmer <brad@gilmer.tv>

[DSCAlarm Action] Correct linter errors only

---

bundles/action/org.openhab.action.ecobee/README.md

[Ecobee Action] Correct linter errors only

---

bundles/action/org.openhab.action.harmonyhub/README.md
bundles/action/org.openhab.action.homematic/README.md

[HarmonyHub][Homematic] Correct linter errors only

---

bundles/action/org.openhab.action.mail/README.md
bundles/action/org.openhab.action.mios/README.md
bundles/action/org.openhab.action.mqtt/README.md

[Mail Action][Mios Action][MQTT Action] Correct linter errors only.

---

bundles/action/org.openhab.action.nma/README.md

[NMA Action] Correct linter errors only.

---

bundles/action/org.openhab.action.openwebif/README.md

[OpenWebIF Action] Correct linter errors only

---

bundles/action/org.openhab.action.prowl/README.md

[Prowl Action] Correct linter errors only

---

bundles/action/org.openhab.action.pushbullet/README.md

[Pushbullet Action] Correct linter errors only

---

bundles/action/org.openhab.action.pushsafer/README.md

[Pushsafer Action] Correct linter errors only

---

bundles/action/org.openhab.action.satel/README.md
bundles/action/org.openhab.action.squeezebox/README.md

[Satel Action][Squeezebox Action] Correct linter errors only

---

bundles/action/org.openhab.action.twitter/README.md

[Twitter Action] Correct linter errors only

---

bundles/action/org.openhab.action.weather/README.md

[Weather Action] Correct linter errors only

---

bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java

Uses @sciamachy's suggested change.
Fixes #5255.

[JDBC persistence] Fix storage of time values for DATETIMEITEM.

---

bundles/action/org.openhab.action.pebble/README.md

[Pebble Action] Correct linter errors only

---

bundles/action/org.openhab.action.pushover/README.md

[Pushover Action] Correct linter errors only

---

bundles/action/org.openhab.action.telegram/README.md

[Telegram Action] Correct linter errors only

---

bundles/action/org.openhab.action.tinkerforge/README.md

[TinkerForge Action] Correct linter errors

---

bundles/binding/org.openhab.binding.fatekplc/README.md
bundles/binding/org.openhab.binding.fatekplc/src/main/java/org/openhab/binding/fatekplc/items/FatekSwitchItem.java

Fixes #5420
Signed-off-by: Slawomir Jaranowski <s.jaranowski@gmail.com> (github: slawekjaranowski)

Fatek PLC Switch item with two registers

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md

As I'm using the 7590 successfully, I've added it to the list in order for others to know.

Add 7590 as tested

---

bundles/action/org.openhab.action.astro/README.md

- Second linter pass
- My linter now configured correctly

[Astro Action] Fix linter errors

---

bundles/action/org.openhab.action.ciscospark/README.md

[Ciscospark Action] Fix linter errors

---

bundles/action/org.openhab.action.dscalarm/README.md

[DSCAlarm Action] Fix linter errors

---

bundles/action/org.openhab.action.ecobee/README.md

[Ecobee Action] Fix linter errors

---

bundles/action/org.openhab.action.harmonyhub/README.md

[Harmonyhub Action] Fix linter errors

---

bundles/action/org.openhab.action.homematic/README.md

[Homematic Action] Fix linter errors

---

bundles/action/org.openhab.action.mail/README.md

[Mail Action] Fix linter errors

---

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java

[Epsonprojector] Fixed timeouts to meet specification

---

bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBinding.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcGenericBindingProvider.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcClient.java
bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/ws/IhcResourceInteractionService.java

Additionally, couple of compiler warnings fixed and another minor
improvements

[IHC] NPE fix

---

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java

fix for #5331 
Improved error handling: Closing and resetting connection in case of error and initialize again.
Signed-off-by: Oliver Probst <OliverProbst@gmx.de> (github: oprobst)

[Fritzboxtr064] Close connection and re-init in case of failure (#5331)

---

bundles/action/org.openhab.action.mios/README.md

[Mios Action] Fix linter errors

---

bundles/action/org.openhab.action.mqtt/README.md

[MQTT Action] Fix linter errors

---

bundles/action/org.openhab.action.nma/README.md

[NMA Action] Fix linter errors

---

bundles/action/org.openhab.action.openwebif/README.md

[Openwebif Action] Fix linter errors

---

bundles/action/org.openhab.action.prowl/README.md

[Prowl Action] Fix linter errors

---

bundles/action/org.openhab.action.pushbullet/README.md

[Pushbullet Action] Fix linter errors

---

bundles/action/org.openhab.action.pushsafer/README.md

[Pushsafer Action] Fix linter errors

---

bundles/action/org.openhab.action.satel/README.md

[Satel Action] Fix linter errors

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/mystromecopower.cfg
features/openhab-addons/src/main/feature/feature.xml

[MystromEcoPower] Add feature and config files to support OH2 compatibility

---

bundles/action/org.openhab.action.twitter/README.md

[Twitter Action] Fix linter errors

---

bundles/action/org.openhab.action.weather/README.md

[Weather Action] Fix linter errors

---

bundles/action/org.openhab.action.xbmc/README.md

[XBMC Action] Fix linter errors

---

features/openhab-addons-external/pom.xml
features/openhab-addons-external/src/main/resources/conf/ucprelayboard.cfg
features/openhab-addons/src/main/feature/feature.xml

Signed-off-by: Robert Michalak <rbrt.michalak@gmail.com>

[UCPRelayboard] Add configurations for OH2 compatibility

---

bundles/binding/org.openhab.binding.novelanheatpump/README.md

HeatPump_Stat had two declarations

[NovelanHeatpump] Fix double item declaration

---

bundles/binding/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/InfoResponse.java
bundles/binding/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubBinding.java

In some cases the neohub will return 255 and 127 values
Also handle unregistered neostats

[Neohub] Handle out of range values for temperatures

---

bundles/action/org.openhab.action.telegram/README.md
bundles/action/org.openhab.action.telegram/pom.xml
bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java

I have extended the Telegram action with sending an base64 image from rules. This comes in handy when you have images stored in an Image Item.

[Telegram Action] Send base64 image with Telegram message

---

bundles/binding/org.openhab.binding.knx.test/.classpath
bundles/binding/org.openhab.binding.knx.test/.project
bundles/binding/org.openhab.binding.knx/.project
features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

renamed project to knx1 and moved it to legacy

---

bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

for DTP:
5.004: Percent (8 Bit)
6.001: Percent (8 Bit)
9.007: Humidity
Synchronized with https://github.com/sjka/openhab2-addons/pull/3

[KNX] Added file description and specific mappings

---

bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java

Tests for:
for DTP:
5.004: Percent (8 Bit)
6.001: Percent (8 Bit)
9.007: Humidity
Needed for https://github.com/openhab/openhab1-addons/pull/5513

[KNX1] Test AssertionErrors

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved Satel to legacy add-ons

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

Related to https://github.com/openhab/openhab2-addons/pull/2284

moved IRtrans to legacy add-ons

---

bundles/binding/org.openhab.binding.knx.test/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/config/KNXTypeMapper.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java
bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

KNXCoreTypeMapper searches now for all usable DTP provided by calimero and maps it to openHAB types.

[KNX] Update generic KNXCoreTypeMapper

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

Related to https://github.com/openhab/openhab2-addons/pull/1960.

moved Nibe heatpump binding to legacy add-ons

---

bundles/binding/org.openhab.binding.novelanheatpump/README.md
bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/HeatpumpCommandType.java
bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java

Add new simple state without time to optimize persist data and minimize database write operations and data.

[Novelanheatpump] Add new simple state without time

---

bundles/action/org.openhab.action.telegram/README.md

Added example for sending Image Item with telegram action. I had some diffeculty finding the way to do it, so adding it to the readme would possibly help others.

Minor update to readme with Image Item example

---

bundles/binding/org.openhab.binding.fritzboxtr064/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.fritzboxtr064/build.properties
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallEvent.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallMonitor.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064Binding.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhoneBookEntry.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java

Fix the ArrayIndexOutOfBoundsException from #5522 .
Also:
clean up the logging and doc comments
eliminate compiler warnings

[FritzboxTr064] Fix the ArrayIndexOutOfBoundsException

---

bundles/action/org.openhab.action.telegram/README.md

Update the README to indicate the action methods return boolean values. (Fixes #5531)
Added a list of each action method and its parameters, to be more compliant with the other action READMEs.

[Telegram] Update README.md

---

bundles/binding/org.openhab.binding.bticino/README.md
bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/MonitorSessionThread.java
bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OWNUtilities.java
bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OpenWebNet.java
bundles/binding/org.openhab.binding.bticino/src/main/java/com/myhome/fcrisciani/connector/MyHomeJavaConnector.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoBinding.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoDevice.java
bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoGenericBindingProvider.java
distribution/openhabhome/configurations/openhab_default.cfg
features/openhab-addons-external/src/main/resources/conf/bticino.cfg

+ add parameter to define max. heating zones
+ add Feedback for Heating Actors
+ add Categorisation for Heating Control Modes
// hStatus
// -------
// 0: Status Probe / Actuators
// 1: Status Operation Mode
// 2: Status Control Mode
// 3: Status Main Unit
+ add some null checks to prevent errors
+ add OWN specifics for heating mode controls
+ update ConvertTemperature to be working with temperature offset
+ add ContactItem & StringItem to be used for Heating Actors & Modes
+ add Diagnostic frames for Heating Control (Main Unit, Temperature Probes, Actors)
+ add Heating Control Status Actors
+ add Heating Control Modes
+ add Heating Control Temperatures
Enhancement Open Door Lock  …
+ add Posibility to open Door Lock
Enhancement Shutter  …
+ add that the shutter also reacts to pecentType …

[Bticino] Several enhancements for Heating Control / Door Lock / Shutter / Dimmer

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md

Adjusted presence.map content to real values
Changed <present> icon to <presence>
Added remark to install Map Transformation Addon for using mapping of presence.map
Fixed variable in item configuration

[FritzboxTr064] Fixed some examples in FritzBox TR064-Readme

---

bundles/io/org.openhab.io.transport.mqtt/src/main/java/org/openhab/io/transport/mqtt/MqttService.java

Improve error handling for config processing.
Fixes #5553

[MQTT] Improve error handling for config processing

---

bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/SwegonVentilationBinding.java
bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/ValueCache.java

 [Swegonventilation] Added value cache to minimize item updates

---

bundles/binding/org.openhab.binding.nest/README.md
bundles/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/messages/Structure.java

> Security API
> A new endpoint, [wwn_security_state](https://developers.nest.com/documentation/cloud/api-structure#wwn_security_state), has been added to the Nest API. This state works with Nest Cam to enable Works with Nest integrations to simulate occupancy and deter intruders.
>
> See [Security](https://developers.nest.com/documentation/cloud/security-guide) for more information on the API and [Product Review Guidelines](https://developers.nest.com/documentation/cloud/product-review-guidelines) for related updates.

[Nest] January 2018 API update

---

bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/internal/OpenEnergyMonitorBinding.java
bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/internal/ValueCache.java

 [openenergymonitor] Added value cache to minimize item updates

---

pom.xml

Use newest version of maven-deploy-plugin

---

bundles/binding/org.openhab.binding.tcp/README.md

Removed spurious bracket in Example.
Signed-off-by: Udo Hartmann udo1toni@gmail.com

[TCP][Documentation] Update Readme.md

---

bundles/binding/org.openhab.binding.mqtt/META-INF/MANIFEST.MF
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttEventBusBinding.java
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttMessagePublisher.java
bundles/binding/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttMessageSubscriber.java
bundles/io/org.openhab.io.transport.mqtt/src/main/java/org/openhab/io/transport/mqtt/internal/MqttBrokerConnection.java

Also clean up logging, eliminate a warning, and fix a few common programming errors.
Fixes #5569.

[MQTT] Fix UTF-8 encoding issues.

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md

Presence MAC with transformation: syntax correction

[FritzboxTr064][Documentation] Add missing quote in README.md

---

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java

[FritzboxTr064] replaced printStackTrace statement by proper logging

---

bundles/action/org.openhab.action.twitter/src/main/java/org/openhab/action/twitter/internal/Twitter.java

Reference: https://community.openhab.org/t/twitter-action-character-limit/46650?u=confectrician
This was just a quick fix with the GitHub Editor.
Please don't hurt me if i missed something. 😄 
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

[Twitter Action] Updated to new Character Limit

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java

This patch enables uvindex and wind gust values from forecast.io

[Weather][ForecastIo] Get UV-Index and Wind Gust from forecast.io

---

bundles/binding/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/connector/EpsonProjectorSerialConnector.java

[EpsonProjector] Prevent NullPointerException

---

bundles/binding/org.openhab.binding.mpd/README.md

`s/Exec/MPD` and change a bit of the wording. Also add download link to `.jar` file.

[MPD][Documentation] Fix an error and change a bit of wording

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved modbus1 binding to legacy now that we have a 2.x version

---

bundles/binding/org.openhab.binding.epsonprojector/README.md

Add documentation to the existing tcp option the binding supports
Signed-off-by: Christoph Wempe cw-git@wempe.net (github: CWempe)

[epsonpjorector] Add tcp option to README

---

bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java

most important thing here is the trimming of the address book entries. sometimes there are some special characters like linebreaks, which did not match correctly.
additionally there is a little refactoring to avoid boilerplate code

[fritzboxtr064] fixed name resolution of address book entries

---

bundles/binding/org.openhab.binding.ecobee/README.md

Include location of Java preferences file on macOS.

[Ecobee] Update README.md

---

bundles/persistence/org.openhab.persistence.influxdb/OSGI-INF/influxdb.xml

Fixes https://github.com/openhab/openhab1-addons/issues/5658

Make the ItemRegistry a static reference

---

features/openhab-addons-external/src/main/resources/conf/rrd4j.cfg

comment that only the first aggregation function is support seems to be outdated, insert a pointer to online docu

comment fix / link for rrd4j.cfg

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

Related to https://github.com/openhab/openhab2-addons/pull/2225 (/cc @lolodomo)

moved Powermax binding to legacy add-ons

---

bundles/binding/org.openhab.binding.maxcul/README.md

Signed-off-by: Jan Haffner <info@jan-haffner.de>

[DOCUMENTATION] Fix spelling in maxcul binding readme

---

pom.xml

Same fix as https://github.com/openhab/openhab-core/pull/408

fixed version of maven-install-plugin

---

bundles/action/org.openhab.action.pushbullet/README.md

Closes https://github.com/openhab/openhab1-addons/issues/5581
Signed-off-by: Angelos Fountoulakis agf@wired-net.gr (github: AngelosF)

[Pushbullet] Update README.md with configuration parameters

---

bundles/persistence/org.openhab.persistence.mysql/.classpath

Replaced library in classpath because of errors in Eclipse, related to #5699

[Persistence/Mysql] Corrected project config for mysql related to #5699

---

bundles/action/org.openhab.action.prowl/README.md

-  Corrects prowl configuration file location
-  Corrects prowl configuration file name
Signed-off-by: Brad Gilmer <brad@gilmer.tv> (github:bgilmer77)

[Prowl] Correct configuration info in README

---

bundles/binding/org.openhab.binding.vdr/README.md

Provide more details for binding configuration, especially when using OpenHAB 2.

[VDR] Update README.md

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved MQTT 1.x binding to legacy addons

---

bundles/persistence/org.openhab.persistence.dynamodb/README.md

For developers. Inspired by PR #5722
Signed-off-by: Sami Salonen <ssalonen@gmail.com>

[dynamodb] Note in README on integration tests

---

bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java

Fixed typo in error message (retreive instead of retrieve)
Signed-off-by: Metin Savignano ms@savignano.net (github: cubistico)

[weather] Fix typo in error message

---

bundles/binding/org.openhab.binding.fritzbox/README.md

Add note that telnet is not supported any more and that the TR064 binding should be used
Signed-off-by: Metin Savignano ms@savignano.net (github: cubistico)

[Fritzbox] Update README.md with notes about removed Telnet support

---

bundles/persistence/org.openhab.persistence.influxdb/README.md

[Persistence] Corrected the InfluxDB web page link

---

bundles/binding/org.openhab.binding.anel/README.md

Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states

[Anel] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.ecotouch/README.md

[Ecotouch] Formatting changes for README

---

bundles/binding/org.openhab.binding.iec6205621meter/README.md

[Iec6205621meter] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.isy/README.md

Changed indention to ``` for better readability on openhab.org

[Isy] Formatting changes for README

---

bundles/binding/org.openhab.binding.koubachi/README.md

[Koubachi] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.lgtv/README.md

[LGTV] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.maxcube/README.md

[Maxcube] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.mios/README.md

[Mios] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.piface/README.md

[Piface] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.tinkerforge/README.md

[Tinkerforge] Update README with better sendCommand alternative

---

bundles/persistence/org.openhab.persistence.rrd4j/README.md

Updated the documentation in order to:
-show  and explain contents of the default rrd4j.cfg
-give explanation for needed item-list in rrd4j.cfg AND rrd4j.persist.
-remove mismatch of text and posted example
-give usable example for 2 archive configurations
Signed-off-by: Juergen Baginski [opus42@gmx.de](mailto:opus42@gmx.de) (github: JueBag)

[rrd4j] Enhance README with better examples

---

bundles/binding/org.openhab.binding.plex/README.md

[Plex] Update README with better sendCommand alternative

---

bundles/binding/org.openhab.binding.bticino/README.md

Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states

[bticino] Update README.md with better sendCommand alternative

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

Related to https://github.com/openhab/openhab2-addons/pull/3708

Move IHC 1.x binding to legacy addons

---

bundles/action/org.openhab.action.pushbullet/README.md

For some time now (may 2019) only 100 messages per month are allowed.

Only 100 messages per month are allowed.

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java

Add the possibility to reboot the FritzBox by sending ON command to an item.

[fritzboxtr064] add reboot action

---

bundles/binding/org.openhab.binding.velux/README.md
bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/handler/VeluxBridgeHandlerOH1.java

[Jens](https://community.openhab.org/u/jewesta) recognized a [non-smooth change of actuator positions](https://community.openhab.org/t/binding-connects-to-klf200-but-doesnt-seem-to-be-able-to-retrieve-information/68886/27). This occurs due to interference of target positions with current positions.

[Velux] bug fixes: race condition during startup. Smooth change of actuator positions.

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

openhab2 has a mail binding now

move mail action to legacy

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved legacy bindings to the correct feature

---

distribution/pom.xml

removed sense persistence service from distro pom

---

bundles/binding/org.openhab.binding.anel/README.md

[anel] updated product links

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md

Signed-off-by: Dirk Benecke dirkbe@users.noreply.github.com

Update README.md adding FB 6490

---

features/openhab-addons-legacy/src/main/feature/feature.xml
features/openhab-addons/src/main/feature/feature.xml

moved networkupstools to legacy addons

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md

* Translate log message
* Wifi => Wi-Fi, see https://en.wikipedia.org/wiki/Wi-Fi
* Use capital letter after bullet point
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

[Fritzboxtr064] Improve README

---

bundles/binding/org.openhab.binding.fritzboxtr064/README.md
bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java

[fritzboxtr064] Added uptime

---

bundles/binding/org.openhab.binding.serial/README.md

Added CHARSET inline example.
Removed erroneous parens from BASE64 argument.

[Serial] Update README.md with improved config info

---

bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConnectorThread.java

fixed compilation error

---

bundles/binding/org.openhab.binding.davis/README.md

[Davis] Formatting changes for README

---

bundles/binding/org.openhab.binding.daikin/README.md

changed pre to ``` for better readability on openhab.org

[Daikin] Formatting changes for README

---

bundles/binding/org.openhab.binding.caldav-personal/README.md

changed pre to ``` for better readability on openhab.org

[CalDAV-Personal] Minor cleanup for README

---

bundles/action/org.openhab.action.squeezebox/README.md

[Squeezebox Action] Fix linter errors

---

bundles/binding/org.openhab.binding.bticino/README.md

https://developer.legrand.com/uploads/2019/12/OWN_Intro_ENG.pdf

[Bticino] Update OpenWebNet link in README, current link is dead

---

bundles/binding/org.openhab.binding.insteonhub/README.md
bundles/binding/org.openhab.binding.insteonplm/README.md

Also indicate that the Insteon binding has replaced the both bindings.

Update documentation for insteonhub and insteonplm to indicate not supported.
